### ISSUE TITLE
No module named 'diffusers.pipelines.stable_diffusion.convert_from_ckpt'

### ISSUE THREAD

**Issue by don-vip** [nod-ai/SHARK#1002]
I run SHARK from source on Windows 11. It was running fine a few weeks ago, it doesn't launch anymore after I pulled the latest changes:
```
C:\git\SHARK> .\setup_venv.ps1
Python version found is
Python 3.10.9
Installing Build Dependencies

...

Building SHARK...
Looking in links: https://llvm.github.io/torch-mlir/package-index/, https://nod-ai.github.io/SHARK-Runtime/pip-release-links.html
Obtaining file:///C:/git/SHARK
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\git\shark\shark.venv\lib\site-packages (from nodai-SHARK==0.0.5) (1.24.1)
Requirement already satisfied: PyYAML in c:\git\shark\shark.venv\lib\site-packages (from nodai-SHARK==0.0.5) (6.0)
Requirement already satisfied: torch-mlir>=20221021.633 in c:\git\shark\shark.venv\lib\site-packages (from nodai-SHARK==0.0.5) (20230111.715)
Requirement already satisfied: torch==2.0.0.dev20230106 in c:\git\shark\shark.venv\lib\site-packages (from torch-mlir>=20221021.633->nodai-SHARK==0.0.5) (2.0.0.dev20230106+cpu)
Requirement already satisfied: typing-extensions in c:\git\shark\shark.venv\lib\site-packages (from torch==2.0.0.dev20230106->torch-mlir>=20221021.633->nodai-SHARK==0.0.5) (4.4.0)
Requirement already satisfied: networkx in c:\git\shark\shark.venv\lib\site-packages (from torch==2.0.0.dev20230106->torch-mlir>=20221021.633->nodai-SHARK==0.0.5) (3.0)
Requirement already satisfied: sympy in c:\git\shark\shark.venv\lib\site-packages (from torch==2.0.0.dev20230106->torch-mlir>=20221021.633->nodai-SHARK==0.0.5) (1.11.1)
Requirement already satisfied: mpmath>=0.19 in c:\git\shark\shark.venv\lib\site-packages (from sympy->torch==2.0.0.dev20230106->torch-mlir>=20221021.633->nodai-SHARK==0.0.5) (1.2.1)
Building wheels for collected packages: nodai-SHARK
  Building editable for nodai-SHARK (pyproject.toml) ... done
  Created wheel for nodai-SHARK: filename=nodai_SHARK-0.0.5-0.editable-py3-none-any.whl size=12206 sha256=4b2640a6852022cd31270637ab0141a75b861d3345b981c65b21bbc1091616b6
  Stored in directory: C:\Users\vippy\AppData\Local\Temp\pip-ephem-wheel-cache-5j_o67hy\wheels\a5\3a\86\f8fbd3499b15eec74030ba8702e3e48d40a450029bc5af815a
Successfully built nodai-SHARK
Installing collected packages: nodai-SHARK
  Attempting uninstall: nodai-SHARK
    Found existing installation: nodai-SHARK 0.0.5
    Uninstalling nodai-SHARK-0.0.5:
      Successfully uninstalled nodai-SHARK-0.0.5
Successfully installed nodai-SHARK-0.0.5
Build and installation completed successfully
Source your venv with ./shark.venv/Scripts/activate

(shark.venv) PS C:\git\SHARK> cd .\apps\stable_diffusion\web\
(shark.venv) PS C:\git\SHARK\apps\stable_diffusion\web> python .\index.py
shark_tank local cache is located at C:\Users\vippy\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Traceback (most recent call last):
  File "C:\git\SHARK\apps\stable_diffusion\web\index.py", line 13, in <module>
    from apps.stable_diffusion.src import args
  File "C:\git\SHARK\apps\stable_diffusion\src\__init__.py", line 1, in <module>
    from apps.stable_diffusion.src.utils import (
  File "C:\git\SHARK\apps\stable_diffusion\src\utils\__init__.py", line 14, in <module>
    from apps.stable_diffusion.src.utils.utils import (
  File "C:\git\SHARK\apps\stable_diffusion\src\utils\utils.py", line 18, in <module>
    from diffusers.pipelines.stable_diffusion.convert_from_ckpt import (
ModuleNotFoundError: No module named 'diffusers.pipelines.stable_diffusion.convert_from_ckpt'
```

**Comment by don-vip** [comment]
Found out the issue: my old environment had diffusers 0.11.1 but SHARK requires 0.12.1 now.
Solved it by upragind the package with pip (pip install --upgrade diffusers / pip install --upgrade -r requirements.txt)
