### ISSUE TITLE
Trying out custom model gsdf/Counterfeit-V2.5, results in model compile error

### ISSUE THREAD

**Issue by GTD-Carthage** [nod-ai/SHARK#1013]
I am currently playing out with custom models - one that got me interested is gsdf/Counterfeit-V2.5.

Using the following settings of 512x512, Euler Ancestral at 20 steps, the following console output was produced (starting from when I hit generate) but eventually ends in a system exit error:

This is using the WebUI from commit `307f033`

It may be relevant that I only have 16GB of system RAM.

```
Found device AMD Radeon RX 5700 XT. Using target triple rdna2-unknown-windows.
Tuned models are currently not supported for this setting.
Downloading (…)cheduler_config.json: 100%|█████████████████████████████████████████████| 341/341 [00:00<00:00, 331kB/s]
loading existing vmfb from: D:\StableDiffusionNODAI\inference\euler_scale_model_input_1_512_512fp16.vmfb
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
loading existing vmfb from: D:\StableDiffusionNODAI\inference\euler_step_1_512_512fp16.vmfb
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
Inferring base model configuration.
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:

pip install accelerate

.
Downloading (…)_pytorch_model.bin";: 100%|████████████████████████████████████████| 3.44G/3.44G [05:17<00:00, 10.8MB/s]
Downloading (…)ain/unet/config.json: 100%|█████████████████████████████████████████████| 901/901 [00:00<00:00, 301kB/s]
Traceback (most recent call last):
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\models\model_wrappers.py", line 327, in __call__
    compiled_clip, compiled_unet, compiled_vae = self.compile_all(model_id, need_vae_encode)
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\models\model_wrappers.py", line 267, in compile_all
    compiled_unet = self.get_unet()
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\models\model_wrappers.py", line 225, in get_unet
    shark_unet = compile_through_fx(
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\utils\utils.py", line 100, in compile_through_fx
    mlir_module, func_name = import_with_fx(
  File "D:\StableDiffusionNODAI\main\shark\shark_importer.py", line 382, in import_with_fx
    fx_g = make_fx(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 716, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 450, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 778, in trace
    (self.create_arg(fn(*args)),),
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 466, in wrapped
    out = f(*tensors)
  File "<string>", line 1, in <lambda>
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 756, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 416, in call_module
    return forward(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 749, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\models\model_wrappers.py", line 212, in forward
    unet_out = self.unet.forward(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 481, in forward
    sample, res_samples = downsample_block(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 756, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 416, in call_module
    return forward(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 749, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 789, in forward
    hidden_states = attn(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 756, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 416, in call_module
    return forward(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 749, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\diffusers\models\transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 756, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 416, in call_module
    return forward(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 749, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\diffusers\models\attention.py", line 307, in forward
    attn_output = self.attn2(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 756, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 416, in call_module
    return forward(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 749, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\diffusers\models\cross_attention.py", line 160, in forward
    return self.processor(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\diffusers\models\cross_attention.py", line 234, in __call__
    key = attn.to_k(encoder_hidden_states)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 756, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 416, in call_module
    return forward(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 749, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\utils\_stats.py", line 15, in wrapper
    return fn(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 494, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 519, in inner_torch_dispatch
    out = proxy_call(self, func, args, kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 352, in proxy_call
    out = func(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: mat1 and mat2 shapes cannot be multiplied (128x1024 and 768x320)
Retrying with a different base model configuration
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:

pip install accelerate

.
D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\node.py:244: UserWarning: Trying to prepend a node to itself. This behavior has no effect on the graph.
  warnings.warn("Trying to prepend a node to itself. This behavior has no effect on the graph.")
No vmfb found. Compiling and saving to D:\StableDiffusionNODAI\inference\unet1_64_512_512_fp16_Counterfeit-V2_vulkan-00000000-0300-0000-0000-000000000000.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\StableDiffusionNODAI\inference\unet1_64_512_512_fp16_Counterfeit-V2_vulkan-00000000-0300-0000-0000-000000000000.vmfb.
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:

pip install accelerate

.
Downloading (…)_pytorch_model.bin";:  28%|███████████▌                             | 94.4M/335M [00:09<00:21, 11.2MB/s]Traceback (most recent call last):
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\urllib3\response.py", line 444, in _error_catcher
    yield
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\urllib3\response.py", line 567, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\urllib3\response.py", line 533, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\urllib3\response.py", line 628, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\urllib3\response.py", line 566, in read
    with self._error_catcher():
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\urllib3\response.py", line 449, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\diffusers\models\modeling_utils.py", line 797, in _get_model_file
    model_file = hf_hub_download(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\huggingface_hub\file_download.py", line 1282, in hf_hub_download
    http_get(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\huggingface_hub\file_download.py", line 530, in http_get
    for chunk in r.iter_content(chunk_size=10 * 1024 * 1024):
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\requests\models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\models\model_wrappers.py", line 327, in __call__
    compiled_clip, compiled_unet, compiled_vae = self.compile_all(model_id, need_vae_encode)
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\models\model_wrappers.py", line 270, in compile_all
    compiled_vae = self.get_vae()
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\models\model_wrappers.py", line 183, in get_vae
    vae = VaeModel()
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\models\model_wrappers.py", line 167, in __init__
    self.vae = AutoencoderKL.from_pretrained(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\diffusers\models\modeling_utils.py", line 506, in from_pretrained
    model_file = _get_model_file(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\diffusers\models\modeling_utils.py", line 842, in _get_model_file
    raise EnvironmentError(
OSError: Can't load the model for 'gsdf/Counterfeit-V2.5'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'gsdf/Counterfeit-V2.5' is the correct path to a directory containing a file named diffusion_pytorch_model.bin
Retrying with a different base model configuration
Downloading (…)_pytorch_model.bin";:  28%|███████████▌                             | 94.4M/335M [00:20<00:51, 4.66MB/s]
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:

pip install accelerate

.
Traceback (most recent call last):
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\models\model_wrappers.py", line 327, in __call__
    compiled_clip, compiled_unet, compiled_vae = self.compile_all(model_id, need_vae_encode)
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\models\model_wrappers.py", line 267, in compile_all
    compiled_unet = self.get_unet()
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\models\model_wrappers.py", line 225, in get_unet
    shark_unet = compile_through_fx(
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\utils\utils.py", line 100, in compile_through_fx
    mlir_module, func_name = import_with_fx(
  File "D:\StableDiffusionNODAI\main\shark\shark_importer.py", line 382, in import_with_fx
    fx_g = make_fx(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 716, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 450, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 778, in trace
    (self.create_arg(fn(*args)),),
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 466, in wrapped
    out = f(*tensors)
  File "<string>", line 1, in <lambda>
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 756, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 416, in call_module
    return forward(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 749, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\models\model_wrappers.py", line 212, in forward
    unet_out = self.unet.forward(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 475, in forward
    sample = self.conv_in(sample)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 756, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 416, in call_module
    return forward(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 749, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\utils\_stats.py", line 15, in wrapper
    return fn(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 494, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 519, in inner_torch_dispatch
    out = proxy_call(self, func, args, kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 352, in proxy_call
    out = func(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
Retrying with a different base model configuration
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:

pip install accelerate

.
Traceback (most recent call last):
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\models\model_wrappers.py", line 327, in __call__
    compiled_clip, compiled_unet, compiled_vae = self.compile_all(model_id, need_vae_encode)
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\models\model_wrappers.py", line 267, in compile_all
    compiled_unet = self.get_unet()
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\models\model_wrappers.py", line 225, in get_unet
    shark_unet = compile_through_fx(
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\utils\utils.py", line 100, in compile_through_fx
    mlir_module, func_name = import_with_fx(
  File "D:\StableDiffusionNODAI\main\shark\shark_importer.py", line 382, in import_with_fx
    fx_g = make_fx(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 716, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 450, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 778, in trace
    (self.create_arg(fn(*args)),),
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 466, in wrapped
    out = f(*tensors)
  File "<string>", line 1, in <lambda>
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 756, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 416, in call_module
    return forward(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 749, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\models\model_wrappers.py", line 212, in forward
    unet_out = self.unet.forward(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 475, in forward
    sample = self.conv_in(sample)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 756, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 416, in call_module
    return forward(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 749, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\utils\_stats.py", line 15, in wrapper
    return fn(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 494, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 519, in inner_torch_dispatch
    out = proxy_call(self, func, args, kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 352, in proxy_call
    out = func(*args, **kwargs)
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\torch\_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
Retrying with a different base model configuration
Traceback (most recent call last):
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\gradio\routes.py", line 344, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\gradio\blocks.py", line 1012, in process_api
    result = await self.call_function(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\gradio\blocks.py", line 830, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\StableDiffusionNODAI\main\shark.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\scripts\txt2img.py", line 214, in txt2img_inf
    txt2img_obj = Text2ImagePipeline.from_pretrained(
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 220, in from_pretrained
    clip, unet, vae = mlir_import()
  File "D:\StableDiffusionNODAI\main\apps\stable_diffusion\src\models\model_wrappers.py", line 350, in __call__
    sys.exit(
SystemExit: Cannot compile the model. Please re-run the command with `--enable_stack_trace` flag and create an issue with detailed log at https://github.com/nod-ai/SHARK/issues
```

**Comment by GTD-Carthage** [comment]
Just reporting that as of commit `c4b4728`, this issue has been rectified!
