### ISSUE TITLE
can't use Custom Model  anymore

### ISSUE THREAD

**Issue by osefcorp** [nod-ai/SHARK#1017]
Hello,

All version of exe on every model device AMD Radeon RX 6900 XT

C:\Users\marc\Desktop\stablev8>shark_sd_20230214_527.exe --clear_all
shark_tank local cache is located at C:\Users\marc\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
CLEARING ALL, EXPECT SEVERAL MINUTES TO RECOMPILE
CLEARING ALL, EXPECT SEVERAL MINUTES TO RECOMPILE
vulkan devices are available.
cuda devices are not available.
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
Found device AMD Radeon RX 6900 XT. Using target triple rdna2-unknown-windows.
Tuned models are currently not supported for this setting.
torch\jit\_check.py:172: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
No vmfb found. Compiling and saving to C:\Users\marc\Desktop\stablev8\euler_scale_model_input_1_512_512fp16.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in C:\Users\marc\Desktop\stablev8\euler_scale_model_input_1_512_512fp16.vmfb.
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_VERBOSE does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_DEBUG does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
No vmfb found. Compiling and saving to C:\Users\marc\Desktop\stablev8\euler_step_1_512_512fp16.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in C:\Users\marc\Desktop\stablev8\euler_step_1_512_512fp16.vmfb.
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_VERBOSE does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_DEBUG does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
Diffusers' checkpoint will be identified here :  C:/Users/marc/Desktop/stablev8/models/deliberate_v11
Loading diffusers' pipeline from original stable diffusion checkpoint
global_step key not found in model
'wget' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
Traceback (most recent call last):
  File "gradio\routes.py", line 374, in run_predict
  File "gradio\blocks.py", line 1017, in process_api
  File "gradio\blocks.py", line 835, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "apps\stable_diffusion\scripts\txt2img.py", line 214, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 220, in from_pretrained
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 303, in __call__
  File "apps\stable_diffusion\src\utils\utils.py", line 406, in preprocessCKPT
  File "diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 881, in load_pipeline_from_original_stable_diffusion_ckpt
  File "omegaconf\omegaconf.py", line 189, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\marc\\Desktop\\stablev8\\tmpvwo26sa4\\inferenc.yaml'

thanks

**Comment by osefcorp** [comment]
found part of solution on discord

wget inferenc.yml missing with custom models
powderluvOP
 — 
03/02/2023 01:13
Please download wget https://eternallybored.org/misc/wget/ and place it in c:\windows\system32 to fix this issue. We have upstreamed a fix in diffusers and should remove the need for wget in the future.
