### ISSUE TITLE
Cant compile model

### ISSUE THREAD

**Issue by abtfz** [nod-ai/SHARK#1052]
vulkan devices are available.
cuda devices are not available.
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
Found device Radeon RX 580 Series. Using target triple rdna2-unknown-windows.
Tuned models are currently not supported for this setting.
torch\jit\_check.py:172: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
loading existing vmfb from: A:\Downloads\Programs\shark\euler_scale_model_input_1_512_512fp16.vmfb
loading existing vmfb from: A:\Downloads\Programs\shark\euler_step_1_512_512fp16.vmfb
Diffusers' checkpoint will be identified here :  A:/Downloads/Programs/shark/models/model
Loading diffusers' pipeline from original stable diffusion checkpoint
Traceback (most recent call last):
  File "gradio\routes.py", line 374, in run_predict
  File "gradio\blocks.py", line 1017, in process_api
  File "gradio\blocks.py", line 835, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "apps\stable_diffusion\scripts\txt2img.py", line 116, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 223, in from_pretrained
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 340, in __call__
  File "apps\stable_diffusion\src\utils\utils.py", line 441, in preprocessCKPT
  File "diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 976, in load_pipeline_from_original_stable_diffusion_ckpt
  File "torch\serialization.py", line 810, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\serialization.py", line 1173, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "torch\serialization.py", line 1166, in find_class
    return super().find_class(mod_name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pytorch_lightning'
Found device Radeon RX 580 Series. Using target triple rdna2-unknown-windows.
Using tuned models for Linaqruf/anything-v3.0/fp16/vulkan://00000000-0100-0000-0000-000000000000.
Downloading (…)cheduler_config.json: 100%|█████████████████████████████████████████████| 341/341 [00:00<00:00, 173kB/s]
loading existing vmfb from: A:\Downloads\Programs\shark\euler_scale_model_input_1_512_512fp16.vmfb
loading existing vmfb from: A:\Downloads\Programs\shark\euler_step_1_512_512fp16.vmfb
Inferring base model configuration.
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:
```
pip install accelerate
```
.
Downloading (…)_pytorch_model.bin";: 100%|████████████████████████████████████████| 3.44G/3.44G [52:17<00:00, 1.10MB/s]
Downloading (…)ain/unet/config.json: 100%|█████████████████████████████████████████████| 901/901 [00:00<00:00, 899kB/s]
Retrying with a different base model configuration
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:
```
pip install accelerate
```
.
torch\fx\node.py:250: UserWarning: Trying to prepend a node to itself. This behavior has no effect on the graph.
  warnings.warn("Trying to prepend a node to itself. This behavior has no effect on the graph.")
Loading Winograd config file from  C:\Users\abtahi\.local/shark_tank/configs/unet_winograd_vulkan.json
Retrying with a different base model configuration
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:
```
pip install accelerate
```
.
Retrying with a different base model configuration
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:
```
pip install accelerate
```
.
Retrying with a different base model configuration
Traceback (most recent call last):
  File "gradio\routes.py", line 374, in run_predict
  File "gradio\blocks.py", line 1017, in process_api
  File "gradio\blocks.py", line 835, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "apps\stable_diffusion\scripts\txt2img.py", line 116, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 223, in from_pretrained
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 383, in __call__

**Comment by yzhang93** [comment]
Looks like similar issue to https://github.com/nod-ai/SHARK/issues/1042. Can you try to set the local shark tank to another directory with `--local_tank_cache= flag`?

**Comment by abtfz** [comment]
Okay i'll try that

**Comment by abtfz** [comment]
It worked! Thanks for the help!

**Comment by yzhang93** [comment]
Glad it works! Close the issue.
