### ISSUE TITLE
port is not closed properly

### ISSUE THREAD

**Issue by markg85** [nod-ai/SHARK#1060]
`OSError: Port 8181 is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all().`

I had set it to 8181 and crashed SHARK. Next run gave me that error and a non-running SHARK.

**Comment by sogartar** [comment]
This can be reproduced with
```
cd apps/stable_diffusion/web
python index.py
```
wait for the server to start then `Ctrl+C` to interrupt the server process.
Restart with
```
python index.py
```

Error:
```
Traceback (most recent call last):
  File "/home/petkantchin/ws/shark/shark_venv/lib/python3.11/site-packages/gradio/networking.py", line 119, in start_server
    s.bind((LOCALHOST_NAME, server_port))
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/petkantchin/ws/shark/repo/apps/stable_diffusion/web/index.py", line 138, in <module>
    sd_web.launch(
  File "/home/petkantchin/ws/shark/shark_venv/lib/python3.11/site-packages/gradio/blocks.py", line 1388, in launch
    server_name, server_port, local_url, app, server = networking.start_server(
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petkantchin/ws/shark/shark_venv/lib/python3.11/site-packages/gradio/networking.py", line 122, in start_server
    raise OSError(
OSError: Port 8080 is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all().

```
