### ISSUE TITLE
cannot compile SD 1.5 model

### ISSUE THREAD

**Issue by markg85** [nod-ai/SHARK#1061]
```
Traceback (most recent call last):
  File "/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1024, in process_api
    result = await self.call_function(
  File "/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/gradio/blocks.py", line 836, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/mark/shark-sd-ui/apps/stable_diffusion/scripts/txt2img.py", line 116, in txt2img_inf
    txt2img_obj = Text2ImagePipeline.from_pretrained(
  File "/home/mark/shark-sd-ui/apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_utils.py", line 223, in from_pretrained
    clip, unet, vae = mlir_import()
  File "/home/mark/shark-sd-ui/apps/stable_diffusion/src/models/model_wrappers.py", line 383, in __call__
    sys.exit(
SystemExit: Cannot compile the model. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues
```

Git version of SHARK (hash 6d2a485264e37f9271ca14313a1b88f72fa20c63)
Model: runwayml/stable-diffusion-v1-5 filled in as "HuggingFace Model ID", left side is set to None.
Other then that it's a clean SHARK install on Arch linux with AMD 7900XT.

**Comment by yzhang93** [comment]
Can you share your command and all the printouts?

**Comment by markg85** [comment]
The way i run it might be more helpful instead i think.

I tried running this on a beefy desktop PC on which i remote SSH connected too.
The stacktrace you see is from the session where i remote SSH'd into that machine.

The reason i think it's important is because the logging also complained about the DISPLAY variable not being set. Which it's only when you're running a console within a GUI desktop environment, not when you SSH into it.

That being said, is SHARK even possible to run in this very setup (ssh into the pc)? As i get a feeling it isn't.
The stacktrace still points at a crash which should be gracefully handled instead of crashing. So there's a bug for sure. Just not sure if fixing this specific bug is going to make SHARK work in this setup?

**Comment by yzhang93** [comment]
If you checkout our github repo, you can try with this command `python .\apps\stable_diffusion\scripts\txt2img.py --precision="fp16" --prompt="tajmahal, snow, sunflowers, oil on canvas" --device="vulkan" --hf_model_id="runwayml/stable-diffusion-v1-5"` for windows.

**Comment by markg85** [comment]
Sorry, can't do. Linux here (as mentioned before with "Arch linux"). Do you have a linux version of the command line?

**Comment by markg85** [comment]
```
Traceback (most recent call last):
  File "/home/mark/shark-sd-ui/apps/stable_diffusion/scripts/txt2img.py", line 5, in <module>
    from apps.stable_diffusion.src import (
ModuleNotFoundError: No module named 'apps'
```
?

**Comment by yzhang93** [comment]
Make sure you follow the README and create the virtual environment by running `./setup_venv.sh`

**Comment by powderluv** [comment]
We get that error when you aren't in the venv.

**Comment by markg85** [comment]
Right, should've known to follow the hidden collapsed readme sections...

This is the full log:

```❯ python apps/stable_diffusion/scripts/txt2img.py --precision=fp16 --device=vulkan --prompt="tajmahal, oil on canvas, sunflowers, 4k, uhd" --hf_model_id="runwayml/stable-diffusion-v1-5"
shark_tank local cache is located at /home/mark/.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Found device AMD Radeon RX 7900 XT (RADV GFX1100). Using target triple rdna3-7900-linux.
Using tuned models for runwayml/stable-diffusion-v1-5/fp16/vulkan://00000000-0c00-0000-0000-000000000000.
/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/torch/jit/_check.py:172: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
No vmfb found. Compiling and saving to /home/mark/shark-sd-ui/euler_scale_model_input_1_512_512fp16.vmfb
Using target triple -iree-vulkan-target-triple=rdna3-7900-linux from command line args
Saved vmfb in /home/mark/shark-sd-ui/euler_scale_model_input_1_512_512fp16.vmfb.
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 1.  Skipping ICD.
'DISPLAY' environment variable not set... skipping surface info
/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/torch/jit/_check.py:172: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
No vmfb found. Compiling and saving to /home/mark/shark-sd-ui/euler_step_1_512_512fp16.vmfb
Using target triple -iree-vulkan-target-triple=rdna3-7900-linux from command line args
Saved vmfb in /home/mark/shark-sd-ui/euler_step_1_512_512fp16.vmfb.
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 1.  Skipping ICD.
'DISPLAY' environment variable not set... skipping surface info
Inferring base model configuration.
/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/safetensors/torch.py:98: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/torch/storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Retrying with a different base model configuration
/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/torch/fx/node.py:250: UserWarning: Trying to prepend a node to itself. This behavior has no effect on the graph.
  warnings.warn("Trying to prepend a node to itself. This behavior has no effect on the graph.")
/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/torch/jit/_check.py:172: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
Loading Winograd config file from  /home/mark/.local/shark_tank/configs/unet_winograd_vulkan.json
Retrying with a different base model configuration
Retrying with a different base model configuration
Retrying with a different base model configuration
Cannot compile the model. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues
```

**Comment by yzhang93** [comment]
Can you check if `/home/mark/.local/shark_tank/` folder is created? If not, can you manually create it or change the directory to somewhere else by setting the `--local_tank_cache=` flag?

**Comment by powderluv** [comment]
As a Gentoo user myself I wouldn't read the instruction too 😀. We moved the instructions into the collapsible after normal users who don't know what Python is was trying to setup venv. So for us power users we moved it down.

Let's go step by step by if it is ok. Based on your last log looks like you have the RADV driver can you please confirm with vulkaninfo. It should read AMD LLPC or so for the driverInfo. 

Also feel free to ping on discord so we can troubleshoot live.

**Comment by powderluv** [comment]
Also please try with Python 3.11 - we moved to 3.11 last week.

**Comment by markg85** [comment]
I'm using Arch, a rolling release. It's on python 3.10.x, i'll update when the repository contains 3.11.x. Not anytime sooner. This passive stance is just to prevent other apps from breaking.

Anyhow, that folder `/home/mark/.local/shark_tank/` didn't exist (another bug perhaps?). Creating it did bring me a step further though still with a crash at the end.
```
❯ python apps/stable_diffusion/scripts/txt2img.py --precision=fp16 --device=vulkan --prompt="tajmahal, oil on canvas, sunflowers, 4k, uhd" --hf_model_id="runwayml/stable-diffusion-v1-5"
shark_tank local cache is located at /home/mark/.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Found device AMD Radeon RX 7900 XT (RADV GFX1100). Using target triple rdna3-7900-linux.
Using tuned models for runwayml/stable-diffusion-v1-5/fp16/vulkan://00000000-0c00-0000-0000-000000000000.
/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/torch/jit/_check.py:172: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
loading existing vmfb from: /home/mark/shark-sd-ui/euler_scale_model_input_1_512_512fp16.vmfb
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 1.  Skipping ICD.
'DISPLAY' environment variable not set... skipping surface info
/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/torch/jit/_check.py:172: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
loading existing vmfb from: /home/mark/shark-sd-ui/euler_step_1_512_512fp16.vmfb
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 1.  Skipping ICD.
'DISPLAY' environment variable not set... skipping surface info
Deleted:  /home/mark/shark-sd-ui/unet1_64_512_512_fp16_tuned_stable-diffusion-v1-5_vulkan-00000000-0c00-0000-0000-000000000000.vmfb
Inferring base model configuration.
/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/safetensors/torch.py:98: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/torch/storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Retrying with a different base model configuration
/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/torch/fx/node.py:250: UserWarning: Trying to prepend a node to itself. This behavior has no effect on the graph.
  warnings.warn("Trying to prepend a node to itself. This behavior has no effect on the graph.")
/home/mark/shark-sd-ui/shark.venv/lib/python3.10/site-packages/torch/jit/_check.py:172: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
Loading Winograd config file from  /home/mark/.local/shark_tank/configs/unet_winograd_vulkan.json
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 9.34kB/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 10.1kB/s]
Loading lowering config file from  /home/mark/.local/shark_tank/configs/unet_v1_4_fp16_vulkan.json
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32.2k/32.2k [00:00<00:00, 1.72MB/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32.2k/32.2k [00:00<00:00, 2.44MB/s]
Applying tuned configs on unet1_64_512_512_fp16_tuned_stable-diffusion-v1-5_vulkan-00000000-0c00-0000-0000-000000000000
No vmfb found. Compiling and saving to /home/mark/shark-sd-ui/unet1_64_512_512_fp16_tuned_stable-diffusion-v1-5_vulkan-00000000-0c00-0000-0000-000000000000.vmfb
Using target triple -iree-vulkan-target-triple=rdna3-7900-linux from command line args
Saved vmfb in /home/mark/shark-sd-ui/unet1_64_512_512_fp16_tuned_stable-diffusion-v1-5_vulkan-00000000-0c00-0000-0000-000000000000.vmfb.
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 1.  Skipping ICD.
'DISPLAY' environment variable not set... skipping surface info
[1]    12080 segmentation fault (core dumped)  python apps/stable_diffusion/scripts/txt2img.py --precision=fp16   
```

**Comment by powderluv** [comment]
Good you were able to get to this spot. I think this is a driver crash in Mesa. Would it be possible to try the AMD pro vulkan driver ? You can setup VK_ICD_FILENAMES= to point to your amd-pro JSON file so you can leave your system settings alone.

**Comment by markg85** [comment]
I'm afraid that's not an option for me. As this gpu is fairly new, Linux support is fairly.. well.. sucky. The current mesa version i use is the only version that also works as a desktop version. At least that i could figure out. Switching drives often is a multi-day endeavor with likely even recompiling llvm and potentially the kernel. I'm not feeling adventurous enough to try that.

Why would i need that though? Isn't the open source vulkan driver as good (or better) then the amdgpu pro version?

**Comment by powderluv** [comment]
Yeah the Mesa FP16 support was broken when I last tested on Gentoo (with Mesa dev). You may have luck with fp32 on Mesa but I haven't tested it.

Also the pro vulkan driver may just work in any user directory (no need to mess with your system Mesa drivers) if your amdgpu kernel driver is recent (I'm assuming that to be the case with 7900xtx)

**Comment by markg85** [comment]
Yeah, still not going to try it.
Last time i tried such an update it required an updated llvm too which then forced me to recompile mesa with that llvm and that required xorg...

And that llvm requirement then cause other applications to not work anymore because they had been compile with an older llvm. So no, i'll wait, lol :)
