### ISSUE TITLE
Unable to run any model - 6900xt

### ISSUE THREAD

**Issue by HonkinWaffles** [nod-ai/SHARK#1063]
Issue: 
Able to launch the application and get into the GUI. However attempting to run any model results in the same error. A popup comes up multiple times suggesting to install `accelerate` but after installing it I still get the same message. Additionally, someone else posted in the discord earlier today with the same error and also on a 6900xt. 

System Information:
* Windows 11 
* GPU : 6900xt 
* Driver Version: 23.2.1
* Python Version: 3.11
* SHARK Version : 539 (Also tried newest 545)

Full Logs: 
```
shark_tank local cache is located at C:\Users\honkinwaffle\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
vulkan devices are available.
cuda devices are not available.
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
Found device AMD Radeon RX 6900 XT. Using target triple rdna2-unknown-windows.
Using tuned models for stabilityai/stable-diffusion-2-1/fp16/vulkan://00000000-0900-0000-0000-000000000000.
torch\jit\_check.py:172: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
loading existing vmfb from: C:\Users\honkinwaffle\Programs\Stable Diffusion\euler_scale_model_input_1_512_512fp16.vmfb
loading existing vmfb from: C:\Users\honkinwaffle\Programs\Stable Diffusion\euler_step_1_512_512fp16.vmfb
Inferring base model configuration.
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:


pip install accelerate

.
safetensors\torch.py:98: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
torch\fx\node.py:250: UserWarning: Trying to prepend a node to itself. This behavior has no effect on the graph.
  warnings.warn("Trying to prepend a node to itself. This behavior has no effect on the graph.")
Loading Winograd config file from  C:\Users\honkinwaffle\.local/shark_tank/configs/unet_winograd_vulkan.json
Retrying with a different base model configuration
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:


pip install accelerate

.
Retrying with a different base model configuration
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:


pip install accelerate

.
Retrying with a different base model configuration
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:


pip install accelerate

.
Retrying with a different base model configuration
Traceback (most recent call last):
  File "gradio\routes.py", line 374, in run_predict
  File "gradio\blocks.py", line 1017, in process_api
  File "gradio\blocks.py", line 835, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "apps\stable_diffusion\scripts\txt2img.py", line 116, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 223, in from_pretrained
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 383, in __call__
SystemExit: Cannot compile the model. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues
```

**Comment by SamNukem** [comment]
I've had this issue a couple of times.

I deleted .cache in C:\Users\username and deleted related Temp folders in C:\Users\username\AppData\Local\Temp (usually _MEI).

Once they've been deleted, try running the exe as administrator. Had above issue just now with Anything v4, but managed to resolve just by running the exe as administrator. I have the same GPU as you, so I don't think it's GPU related.

Good luck!

**Comment by HonkinWaffles** [comment]
> Run it with this command, make a cache folder before (you can make a batch file). Worked for me. Make sure the version is correct:
> 
> shark_sd_20230218_544.exe --local_tank_cache=C:\Users\YourPCUsername\AppData\Local\shark_tank

Confirmed that the steps provided by Spitfire035 got things working now. Thank you.
