### ISSUE TITLE
Build 561 Fails With FileNotFoundError

### ISSUE THREAD

**Issue by nonemouse** [nod-ai/SHARK#1093]
On Windows 10, when I try to run shark_sd_20230223_561.exe, the executable immediately exits with the following error:
```
shark_tank local cache is located at C:\Users\***\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Traceback (most recent call last):
  File "transformers\utils\import_utils.py", line 1110, in _get_module
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "transformers\models\blip\processing_blip.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "transformers\processing_utils.py", line 34, in <module>
  File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1120, in load_module
  File "<frozen importlib._bootstrap_external>", line 945, in load_module
  File "<frozen importlib._bootstrap>", line 287, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\***\\AppData\\Local\\Temp\\_MEI29082\\transformers\\__init__.py'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "index.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "apps\stable_diffusion\src\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "apps\stable_diffusion\src\utils\__init__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "apps\stable_diffusion\src\utils\utils.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "diffusers\__init__.py", line 54, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "diffusers\pipelines\__init__.py", line 44, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "diffusers\pipelines\alt_diffusion\__init__.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "diffusers\pipelines\alt_diffusion\pipeline_alt_diffusion.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "diffusers\pipelines\stable_diffusion\__init__.py", line 80, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion_pix2pix_zero.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1231, in _handle_fromlist
  File "transformers\utils\import_utils.py", line 1101, in __getattr__
  File "transformers\utils\import_utils.py", line 1100, in __getattr__
  File "transformers\utils\import_utils.py", line 1112, in _get_module
RuntimeError: Failed to import transformers.models.blip.processing_blip because of the following error (look up to see its traceback):
[Errno 2] No such file or directory: 'C:\\Users\\***\\AppData\\Local\\Temp\\_MEI29082\\transformers\\__init__.py'
[13840] Failed to execute script 'index' due to unhandled exception!
```

Build 551 (shark_sd_20230221_551.exe) does not experience the error.

**Comment by Gizzje** [comment]
Same, but on Windows 11. I got a different number after MEI, but that's probably random?

[Errno 2] No such file or directory: 'C:\\Users\\***\\AppData\\Local\\Temp\\_MEI89442\\transformers\\__init__.py'

**Comment by powderluv** [comment]
Can you please post the full error message on 568 ?

**Comment by Gizzje** [comment]
@powderluv I just solved the problem on my end, so I don't have the full error message anymore. Sorry for the confusion.

I got the problem by downloading build 568 and trying to use a model I previously downloaded (dreamshaper_331BakedVae.safetensors) on the first try. After first choosing one of the 'recommended' models in the drop down menu to generate the first image within build 568 and only then switching to dreamshaper for the second image, everything works fine.

**Comment by nonemouse** [comment]
@powderluv , I just tried and I didn't experience the issue with 568.  I had generated an image or two with 551 after the problem, so possibly it was corrected similar to @Gizzje ?
