### ISSUE TITLE
shark_sd_20230224_565.exe --clear_all failed

### ISSUE THREAD

**Issue by GoZippy** [nod-ai/SHARK#1095]
launch preprelease 565 with --clear_all fails..

`PS E:\ImageAI\shark> .\shark_sd_20230224_565.exe --clear_all
shark_tank local cache is located at C:\Users\me\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Traceback (most recent call last):
  File "index.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "apps\stable_diffusion\src\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "apps\stable_diffusion\src\utils\__init__.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "apps\stable_diffusion\src\utils\utils.py", line 22, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "diffusers\__init__.py", line 108, in <module>
ImportError: cannot import name 'StableDiffusionPix2PixZeroPipeline' from 'diffusers.pipelines' (C:\Users\me\AppData\Local\Temp\_MEI353042\diffusers\pipelines\__init__.pyc)
[29252] Failed to execute script 'index' due to unhandled exception!
PS E:\ImageAI\shark>
`

**Comment by GoZippy** [comment]
running without any flags fails as well.

` E:\ImageAI\shark> .\shark_sd_20230224_565.exe
shark_tank local cache is located at C:\Users\me\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Traceback (most recent call last):
  File "index.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "apps\stable_diffusion\src\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "apps\stable_diffusion\src\utils\__init__.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "apps\stable_diffusion\src\utils\utils.py", line 22, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "diffusers\__init__.py", line 108, in <module>
ImportError: cannot import name 'StableDiffusionPix2PixZeroPipeline' from 'diffusers.pipelines' (C:\Users\me\AppData\Local\Temp\_MEI350602\diffusers\pipelines\__init__.pyc)
[30208] Failed to execute script 'index' due to unhandled exception!
PS E:\ImageAI\shark>
`
