### ISSUE TITLE
bug bug bug

### ISSUE THREAD

**Issue by yoshyteru** [nod-ai/SHARK#1097]
it gives a lot of headache these installations a thousand errors

**Comment by monorimet** [comment]
Hey there, please provide at minimum a description of the issue and steps to reproduce the issue: OS, Hardware specs, what steps you followed to install,
etc.

**Comment by yoshyteru** [comment]
hi, so i have a rx 6600, ryzen 5 5600x processor, 32 gb of ram, i can't use some models like stable 2.1 or some others, i can't increase more than 512x512, nor batch size, count


Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Ean ***@***.***>
Enviado:sábado, 25 de fevereiro de 2023 16:20
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [nod-ai/SHARK] bug bug bug (Issue #1097)


Hey there, please provide at minimum a description of the issue and steps to reproduce the issue: OS, Hardware specs, what steps you followed to install,
etc.

**Comment by njsharpe** [comment]
Hey, so there is still some missing information before we can help you. Are you able to provide us with an error message? What installation of SHARK are you using (EXE, CLI EXE, GitHub Source Code)? What version number of SHARK do you have (for GitHub, what commit number)?

**Comment by yoshyteru** [comment]
to GitHub, which commit number)? I don't know how to tell you, I don't understand much
I tried by exe 631 I can't use lora training , I tried by source code and I get this

Traceback (most recent call last):
  File "C:\Users\SoDeusNaCausaNovaEra\SHARK\apps\stable_diffusion\web\index.py", line 3, in <module>
    import transformers
  File "C:\Users\SoDeusNaCausaNovaEra\SHARK\shark.venv\Lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Users\SoDeusNaCausaNovaEra\SHARK\shark.venv\Lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Users\SoDeusNaCausaNovaEra\SHARK\shark.venv\Lib\site-packages\transformers\utils\__init__.py", line 30, in <module>
    from .generic import (
  File "C:\Users\SoDeusNaCausaNovaEra\SHARK\shark.venv\Lib\site-packages\transformers\utils\generic.py", line 33, in <module>
    import jax.numpy as jnp
  File "C:\Users\SoDeusNaCausaNovaEra\SHARK\shark.venv\Lib\site-packages\jax\__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "C:\Users\SoDeusNaCausaNovaEra\SHARK\shark.venv\Lib\site-packages\jax\config.py", line 17, in <module>
    from jax._src.config import config  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SoDeusNaCausaNovaEra\SHARK\shark.venv\Lib\site-packages\jax\_src\config.py", line 24, in <module>
    from jax._src import lib
  File "C:\Users\SoDeusNaCausaNovaEra\SHARK\shark.venv\Lib\site-packages\jax\_src\lib\__init__.py", line 26, in <module>
    raise ModuleNotFoundError(
ModuleNotFoundError: jax requires jaxlib to be installed. See https://github.com/google/jax#installation for installation instructions.

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Nelson ***@***.***>
Enviado:quinta-feira, 2 de março de 2023 13:08
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [nod-ai/SHARK] bug bug bug (Issue #1097)


Hey, so there is still some missing information before we can help you. Are you able to provide us with an error message? What installation of SHARK are you using (EXE, CLI EXE, GitHub Source Code)? What version number of SHARK do you have (for GitHub, what commit number)?

**Comment by workpioupiou** [comment]
Same here, I can use some models, but I can't change the height and width, the batch size or use image2image or others tabs.
