### ISSUE TITLE
darkstorm2150/Protogen_x3.4_Official_Release -> shark_sd_20230225_568.exe

### ISSUE THREAD

**Issue by SchmuseTigger** [nod-ai/SHARK#1107]
.local/shark_tank/configs\unet_winograd_vulkan.json
100%|█████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 5.40kB/s]
100%|█████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 6.07kB/s]
Retrying with a different base model configuration
Retrying with a different base model configuration
Retrying with a different base model configuration
Traceback (most recent call last):
  File "gradio\routes.py", line 384, in run_predict
  File "gradio\blocks.py", line 1024, in process_api
  File "gradio\blocks.py", line 836, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "apps\stable_diffusion\scripts\txt2img.py", line 117, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 232, in from_pretrained
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 398, in __call__
SystemExit: Cannot compile the model. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues

**Comment by SchmuseTigger** [comment]
duplicate: https://github.com/nod-ai/SHARK/issues/892
