### ISSUE TITLE
Generate Black images - force restart

### ISSUE THREAD

**Issue by victordalosto** [nod-ai/SHARK#1156]
I'm having a problem with different models, where after some successful runs if I restart shark, the next time I load the same model, it only generates black images.
No matter how many times I run it again, it always gives black images.
Note: if I restart shark with the flag --clear_all it doesn't help. I have to manually delete all files in temp folders and in shark folders in order for it to work.

Here is the full prompt of a run.
shark_sd_20230225_568.exe --clear_all
shark_tank local cache is located at C:\Users\victo\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
CLEARING ALL, EXPECT SEVERAL MINUTES TO RECOMPILE
vulkan devices are available.
cuda devices are not available.
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
Found device Radeon RX 590 Series. Using target triple rdna2-unknown-windows.
Using tuned models for CompVis/stable-diffusion-v1-4/fp16/vulkan://00000000-0800-0000-0000-000000000000.
torch\jit\_check.py:172: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
No vmfb found. Compiling and saving to D:\labs\image-generator-ai\engines\shark\euler_scale_model_input_1_512_512fp16.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\labs\image-generator-ai\engines\shark\euler_scale_model_input_1_512_512fp16.vmfb.
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
No vmfb found. Compiling and saving to D:\labs\image-generator-ai\engines\shark\euler_step_1_512_512fp16.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\labs\image-generator-ai\engines\shark\euler_step_1_512_512fp16.vmfb.
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
Checkpoint already loaded at :  D:/labs/image-generator-ai/engines/shark/models/myModel
Compiling all the models with the fetched base model configuration.
torch\fx\node.py:250: UserWarning: Trying to prepend a node to itself. This behavior has no effect on the graph.
  warnings.warn("Trying to prepend a node to itself. This behavior has no effect on the graph.")
Loading Winograd config file from  C:\Users\victo\.local/shark_tank/configs\unet_winograd_vulkan.json
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 3.79kB/s] 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 3.78kB/s] Loading lowering config file from  C:\Users\victo\.local/shark_tank/configs\unet_v1_4_fp16_vulkan_rdna2.json
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 24.6k/24.6k [00:00<00:00, 629kB/s] 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 24.6k/24.6k [00:00<00:00, 733kB/s] Applying tuned configs on unet1_64_512_512_fp16_tuned_myModel_vulkan-00000000-0800-0000-0000-000000000000
No vmfb found. Compiling and saving to D:\labs\image-generator-ai\engines\shark\unet1_64_512_512_fp16_tuned_myModel_vulkan-00000000-0800-0000-0000-000000000000.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\labs\image-generator-ai\engines\shark\unet1_64_512_512_fp16_tuned_myModel_vulkan-00000000-0800-0000-0000-000000000000.vmfb.
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
Loading Winograd config file from  C:\Users\victo\.local/shark_tank/configs\vae_winograd_vulkan.json
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 33.0/33.0 [00:00<00:00, 1.13kB/s] 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 33.0/33.0 [00:00<00:00, 1.13kB/s] No vmfb found. Compiling and saving to D:\labs\image-generator-ai\engines\shark\vae1_64_512_512_fp16_tuned_myModel_vulkan-00000000-0800-0000-0000-000000000000.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\labs\image-generator-ai\engines\shark\vae1_64_512_512_fp16_tuned_myModel_vulkan-00000000-0800-0000-0000-000000000000.vmfb.
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
No vmfb found. Compiling and saving to D:\labs\image-generator-ai\engines\shark\clip1_64_512_512_fp16_tuned_myModel_vulkan-00000000-0800-0000-0000-000000000000.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\labs\image-generator-ai\engines\shark\clip1_64_512_512_fp16_tuned_myModel_vulkan-00000000-0800-0000-0000-000000000000.vmfb.
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
50it [01:42,  2.04s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.03s/it]

**Comment by vacanickel** [comment]
I also got Black Images - Rx580 here

**Comment by vleeuwenmenno** [comment]
Same here black images with RX 580
Any progress on this? If you need any more detailed logs let me know.

**Comment by vleeuwenmenno** [comment]
Is it possible this requires a specific driver?

**Comment by Mzyxptlk** [comment]
Same problem, also using an RX 580. Everything works fine on 526 and older, but 531 and all newer tags I've tried (537, 544, 568, 592) fail.

However I'm not just here to high five y'all. With `AMD_ENABLE_LLPC=1`, the problem goes away! I have no idea what that environment variable does, but https://github.com/nod-ai/SHARK/commit/8c241b06cb54806ecdd37c917d60f7b62bf5dc08 appears to be the faulty commit.

**Comment by anomaliesintent112** [comment]
same problem here and it looks like AMD_ENABLE_LLPC=1 did not fix it. I am using an rx580 and when i uncheck low vram it gives me this error. 

Traceback (most recent call last):
  File "gradio\routes.py", line 401, in run_predict
  File "gradio\blocks.py", line 1302, in process_api
  File "gradio\blocks.py", line 1039, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "gradio\utils.py", line 491, in async_iteration
  File "ui\txt2img_ui.py", line 177, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 135, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 172, in decode_latents
  File "shark\shark_inference.py", line 138, in __call__
  File "shark\shark_runner.py", line 93, in run
  File "shark\iree_utils\compile_utils.py", line 385, in get_results
  File "iree\runtime\function.py", line 130, in __call__
  File "iree\runtime\function.py", line 154, in _invoke
RuntimeError: Error invoking function: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\vma_allocator.cc:693: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.device.queue.alloca; while calling import;

**Comment by powderluv** [comment]
What version of the driver and application are you on ?

**Comment by Mzyxptlk** [comment]
I tried recreating the bug with the latest pre-release (2023-06-08, tag 761) and drivers (v23.5.2), but now I get an OOM error when generating an image. Full output:
```
Using tuned models for stabilityai/stable-diffusion-2-1(fp16) on device vulkan://00000000-0800-0000-0000-000000000000.
loading existing vmfb from: D:\shark\2023-06-08\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
loading existing vmfb from: D:\shark\2023-06-08\euler_step_1_512_512_vulkan_fp16.vmfb
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
use_tuned? sharkify: True
_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
20it [00:17,  1.13it/s]
torch\fx\node.py:260: UserWarning: Trying to prepend a node to itself. This behavior has no effect on the graph.
  warnings.warn("Trying to prepend a node to itself. This behavior has no effect on the graph.")
No vmfb found. Compiling and saving to D:\shark\2023-06-08\vae_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb
Configuring for device:vulkan://00000000-0800-0000-0000-000000000000
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\shark\2023-06-08\vae_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb.
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
Traceback (most recent call last):
  File "gradio\routes.py", line 393, in run_predict
  File "gradio\blocks.py", line 1069, in process_api
  File "gradio\blocks.py", line 892, in call_function
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 549, in async_iteration
  File "ui\txt2img_ui.py", line 183, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 135, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 175, in decode_latents
  File "shark\shark_inference.py", line 138, in __call__
  File "shark\shark_runner.py", line 100, in run
  File "shark\iree_utils\compile_utils.py", line 391, in get_results
  File "iree\runtime\function.py", line 130, in __call__
  File "iree\runtime\function.py", line 154, in _invoke
RuntimeError: Error invoking function: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\vma_allocator.cc:693: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.device.queue.alloca; while calling import;
[ 1]   native hal.device.queue.alloca:0 -
[ 0] bytecode module@0:2972 -
```
No image is generated and 'Error' is displayed in the app. I'm not using SHARK any more, so this is about all the debugging I can do. Hope it helps anyway.
