### ISSUE TITLE
pytorch module not found

### ISSUE THREAD

**Issue by GoZippy** [nod-ai/SHARK#1160]
Have been seeing this a lot recently. 

```Found device AMD Radeon RX 6700 XT. Using target triple rdna2-unknown-windows.
Tuned models are currently not supported for this setting.
torch\jit\_check.py:172: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
No vmfb found. Compiling and saving to E:\ImageAI\shark\euler_scale_model_input_1_512_512fp16.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in E:\ImageAI\shark\euler_scale_model_input_1_512_512fp16.vmfb.
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
No vmfb found. Compiling and saving to E:\ImageAI\shark\euler_step_1_512_512fp16.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in E:\ImageAI\shark\euler_step_1_512_512fp16.vmfb.
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
Diffusers' checkpoint will be identified here :  E:/ImageAI/shark/models/v1-5-pruned
Loading diffusers' pipeline from original stable diffusion checkpoint
Traceback (most recent call last):
  File "gradio\routes.py", line 384, in run_predict
  File "gradio\blocks.py", line 1032, in process_api
  File "gradio\blocks.py", line 858, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "gradio\utils.py", line 448, in async_iteration
  File "apps\stable_diffusion\scripts\txt2img.py", line 122, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 355, in from_pretrained
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 489, in __call__
  File "apps\stable_diffusion\src\utils\utils.py", line 441, in preprocessCKPT
  File "diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1010, in load_pipeline_from_original_stable_diffusion_ckpt
  File "torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\serialization.py", line 1172, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "torch\serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pytorch_lightning'
```

**Comment by GoZippy** [comment]
I verified pytorch is installed

```
PS E:\ImageAI\shark> pip3 install torch torchvision
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
Requirement already satisfied: torch in c:\python310\lib\site-packages (1.13.1)
Requirement already satisfied: torchvision in c:\python310\lib\site-packages (0.14.1)
Requirement already satisfied: typing-extensions in c:\python310\lib\site-packages (from torch) (4.4.0)
Requirement already satisfied: requests in c:\users\gotad\appdata\roaming\python\python310\site-packages (from torchvision) (2.28.2)
Requirement already satisfied: numpy in c:\users\gotad\appdata\roaming\python\python310\site-packages (from torchvision) (1.24.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\python310\lib\site-packages (from torchvision) (9.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python310\lib\site-packages (from requests->torchvision) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\gotad\appdata\roaming\python\python310\site-packages (from requests->torchvision) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python310\lib\site-packages (from requests->torchvision) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\gotad\appdata\roaming\python\python310\site-packages (from requests->torchvision) (2022.12.7)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
PS E:\ImageAI\shark>
```

**Comment by GoZippy** [comment]
PS E:\ImageAI\shark> pip list --outdated
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
Package             Version     Latest   Type
------------------- ----------- -------- -----
boto3               1.26.73     1.26.86  wheel
botocore            1.29.73     1.29.86  wheel
charset-normalizer  3.0.1       3.1.0    wheel
flatbuffers         23.1.21     23.3.3   wheel
fsspec              2023.1.0    2023.3.0 wheel
huggingface-hub     0.12.0      0.13.0   wheel
lightning-utilities 0.6.0.post0 0.7.1    wheel
mpmath              1.2.1       1.3.0    wheel
onnxruntime         1.13.1      1.14.1   wheel
protobuf            4.21.12     4.22.1   wheel
pytorch-lightning   1.9.2       1.9.4    wheel
scipy               1.10.0      1.10.1   wheel
setuptools          63.2.0      67.6.0   wheel
soupsieve           2.3.2.post1 2.4      wheel
torchmetrics        0.11.1      0.11.3   wheel
tqdm                4.64.1      4.65.0   wheel
transformers        4.26.0      4.26.1   wheel
typing_extensions   4.4.0       4.5.0    wheel
wrapt               1.14.1      1.15.0   wheel
zipp                3.13.0      3.15.0   wheel
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
PS E:\ImageAI\shark>

**Comment by powderluv** [comment]
@Abhishek-Varma when you are messing with the .exe / spec files can you also add the lightning dependency ?

**Comment by Abhishek-Varma** [comment]
> @Abhishek-Varma when you are messing with the .exe / spec files can you also add the lightning dependency ?

Sure, I'll add that.

**Comment by Abhishek-Varma** [comment]
https://github.com/nod-ai/SHARK/pull/1211 addresses this.
Closing this thread.
