### ISSUE TITLE
625 hangs with 2.1 standard base model on RX6700

### ISSUE THREAD

**Issue by GoZippy** [nod-ai/SHARK#1226]
```
E:\ImageAI\shark> .\shark_sd_20230321_625.exe
shark_tank local cache is located at C:\Users\me\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
diffusers\models\cross_attention.py:30: FutureWarning: Importing from cross_attention is deprecated. Please import from diffusers.models.attention_processor instead.
vulkan devices are available.
cuda devices are not available.
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
Found device AMD Radeon RX 6700 XT. Using target triple rdna2-unknown-windows.
Using tuned models for stabilityai/stable-diffusion-2-1/fp16/vulkan://00000000-0300-0000-0000-000000000000.
loading existing vmfb from: E:\ImageAI\shark\euler_scale_model_input_1_512_512fp16.vmfb
loading existing vmfb from: E:\ImageAI\shark\euler_step_1_512_512fp16.vmfb
use_tuned? sharkify: True
_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base
Compiling all the models with the fetched base model configuration.
safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
torch\_utils.py:777: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
torch\storage.py:955: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Loading Winograd config file from  C:\Users\me\.local/shark_tank/configs\unet_winograd_vulkan.json
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 1.29kB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 6.69kB/s]
Loading lowering config file from  C:\Users\me\.local/shark_tank/configs\unet_v2_1base_fp16_vulkan_rdna2.json
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24.2k/24.2k [00:00<00:00, 210kB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24.2k/24.2k [00:00<00:00, 1.10MB/s]
Applying tuned configs on unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan
No vmfb found. Compiling and saving to E:\ImageAI\shark\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in E:\ImageAI\shark\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb.
torch\fx\node.py:250: UserWarning: Trying to prepend a node to itself. This behavior has no effect on the graph.
  warnings.warn("Trying to prepend a node to itself. This behavior has no effect on the graph.")
Loading Winograd config file from  C:\Users\me\.local/shark_tank/configs\vae_winograd_vulkan.json
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33.0/33.0 [00:00<00:00, 635B/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33.0/33.0 [00:00<00:00, 2.00kB/s]
No vmfb found. Compiling and saving to E:\ImageAI\shark\vae_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in E:\ImageAI\shark\vae_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb.
transformers\modeling_utils.py:402: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
No vmfb found. Compiling and saving to E:\ImageAI\shark\clip_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in E:\ImageAI\shark\clip_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb.
50it [00:11,  4.53it/s]
  0%|                                                                                                                                                     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "gradio\routes.py", line 394, in run_predict
  File "gradio\blocks.py", line 1075, in process_api
  File "gradio\blocks.py", line 898, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "gradio\utils.py", line 549, in async_iteration
  File "apps\stable_diffusion\scripts\txt2img.py", line 155, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 132, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 104, in decode_latents
  File "shark\shark_inference.py", line 138, in __call__
  File "shark\shark_runner.py", line 93, in run
  File "shark\iree_utils\compile_utils.py", line 384, in get_results
  File "iree\runtime\function.py", line 130, in __call__
  File "iree\runtime\function.py", line 154, in _invoke
RuntimeError: Error invoking function: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\vma_allocator.cc:693: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.device.queue.alloca; while calling import;
[ 1]   native hal.device.queue.alloca:0 -
[ 0] bytecode module.forward:3092 [
    <eval_with_key>.13:8:18,
    <eval_with_key>.13:11:20,
    <eval_with_key>.13:13:27,
    <eval_with_key>.13:14:15,
    <eval_with_key>.13:22:12,
```

**Comment by GoZippy** [comment]
looks like out of memory on any model I am trying now RDNA2

```use_tuned? sharkify: True
_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base
Loaded vmfbs from cache and successfully fetched base model configuration.
50it [00:10,  4.77it/s]
  0%|                                                                                                                                                     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "gradio\routes.py", line 394, in run_predict
  File "gradio\blocks.py", line 1075, in process_api
  File "gradio\blocks.py", line 898, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "gradio\utils.py", line 549, in async_iteration
  File "apps\stable_diffusion\scripts\txt2img.py", line 155, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 132, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 104, in decode_latents
  File "shark\shark_inference.py", line 138, in __call__
  File "shark\shark_runner.py", line 93, in run
  File "shark\iree_utils\compile_utils.py", line 384, in get_results
  File "iree\runtime\function.py", line 130, in __call__
  File "iree\runtime\function.py", line 154, in _invoke
RuntimeError: Error invoking function: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\vma_allocator.cc:693: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.device.queue.alloca; while calling import;
[ 1]   native hal.device.queue.alloca:0 -
[ 0] bytecode module.forward:3092 [
    <eval_with_key>.13:8:18,
    <eval_with_key>.13:11:20,
    <eval_with_key>.13:13:27,
```

**Comment by micnorian14** [comment]
RDNA2 support was broken in build 593 and appears to still be broken. Use the latest stable release 592 for now. I'm on WIN10 RX6700XT struggling to get in-painting to work. Most of the time it crashes. I've learned that switching models causes instability. I recommend you relaunch the app if you change your model. Hope that helps.
