### ISSUE TITLE
Intel Arc Fails to Compile

### ISSUE THREAD

**Issue by jarredwalton** [nod-ai/SHARK#1245]
It seems like Intel Arc support is supposed to be present — it shows up as a Vulkan device at least! But in trying to run this I get compile failures Here's the detailed log from the command prompt on Windows 11:

`
(base) C:\stable-diffusion\Shark0321.625>shark_sd_20230321_625.exe --clear_all
shark_tank local cache is located at C:\Users\jwalt\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
diffusers\models\cross_attention.py:30: FutureWarning: Importing from cross_attention is deprecated. Please import from diffusers.models.attention_processor instead.
vulkan devices are available.
cuda devices are not available.
CLEARING ALL, EXPECT SEVERAL MINUTES TO RECOMPILE
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
Found device Intel(R) Arc(TM) A750 Graphics. Using target triple .
Tuned models are currently not supported for this setting.
Using cached models from C:\Users\jwalt\.local/shark_tank/...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 39.2kB/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 54.5kB/s]
No vmfb found. Compiling and saving to C:\stable-diffusion\Shark0321.625\euler_scale_model_input_fp16.vmfb
Optimized kernel for your target device is not added yet.
        Contact SHARK Admin on discord[https://discord.com/invite/RUqY2h2s9u]
        or pull up an issue.
Target : deviceName        = Intel(R) Arc(TM) A750 Graphics
Saved vmfb in C:\stable-diffusion\Shark0321.625\euler_scale_model_input_fp16.vmfb.
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_VERBOSE does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_DEBUG does not conform to naming standard (Policy #LLP_LAYER_3)
ERROR: [Loader Message] Code 0 : Failed to open dynamic library "C:\WINDOWS\system32\VRFCAT-Plugins\.\VK_LAYER_FCAT_DT_overlay_x64.dll" with error 1114
Using cached models from C:\Users\jwalt\.local/shark_tank/...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 39.4kB/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 78.6kB/s]
No vmfb found. Compiling and saving to C:\stable-diffusion\Shark0321.625\euler_step_fp16.vmfb
Optimized kernel for your target device is not added yet.
        Contact SHARK Admin on discord[https://discord.com/invite/RUqY2h2s9u]
        or pull up an issue.
Target : deviceName        = Intel(R) Arc(TM) A750 Graphics
Saved vmfb in C:\stable-diffusion\Shark0321.625\euler_step_fp16.vmfb.
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_VERBOSE does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_DEBUG does not conform to naming standard (Policy #LLP_LAYER_3)
ERROR: [Loader Message] Code 0 : Failed to open dynamic library "C:\WINDOWS\system32\VRFCAT-Plugins\.\VK_LAYER_FCAT_DT_overlay_x64.dll" with error 1114
Using cached models from C:\Users\jwalt\.local/shark_tank/...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 39.9kB/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 38.1kB/s]
No vmfb found. Compiling and saving to C:\stable-diffusion\Shark0321.625\vae77_512_512_fp16_stabilityai_stable_diffusion_2_1_base.vmfb
Optimized kernel for your target device is not added yet.
        Contact SHARK Admin on discord[https://discord.com/invite/RUqY2h2s9u]
        or pull up an issue.
Target : deviceName        = Intel(R) Arc(TM) A750 Graphics
download pipeline failed, falling back to import_mlir
use_tuned? sharkify: False
_1_64_512_512_fp16_stable-diffusion-2-1-base
Inferring base model configuration.
safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
torch\_utils.py:777: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
torch\storage.py:955: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Given groups=1, weight of size [320, 4, 3, 3], expected input[4, 7, 512, 512] to have 4 channels, but got 7 channels instead
Retrying with a different base model configuration
No vmfb found. Compiling and saving to C:\stable-diffusion\Shark0321.625\unet_1_64_512_512_fp16_stable-diffusion-2-1-base_vulkan.vmfb
Optimized kernel for your target device is not added yet.
        Contact SHARK Admin on discord[https://discord.com/invite/RUqY2h2s9u]
        or pull up an issue.
Target : deviceName        = Intel(R) Arc(TM) A750 Graphics
Error invoking IREE compiler tool iree-compile.exe
Diagnostics:
<eval_with_key>.3:7:13: error: failed to legalize operation 'arith.sitofp' that was explicitly marked illegal
<eval_with_key>.3:15:12: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.3, [Shader, GroupNonUniform], [SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers]>, api=Vulkan, #spirv.resource_limits<max_compute_workgroup_size = [128, 128, 64], subgroup_size = 64, cooperative_matrix_properties_nv = []>>}>
<eval_with_key>.3:15:12: error: failed to serialize executables
<unknown>:0: error: failed to legalize operation 'vector.bitcast'
<eval_with_key>.3:28:12: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.3, [Shader, GroupNonUniform], [SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers]>, api=Vulkan, #spirv.resource_limits<max_compute_workgroup_size = [128, 128, 64], subgroup_size = 64, cooperative_matrix_properties_nv = []>>}>
<eval_with_key>.3:28:12: error: failed to serialize executables
<unknown>:0: error: failed to legalize operation 'vector.bitcast'
<eval_with_key>.3:33:14: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.3, [Shader, GroupNonUniform], [SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers]>, api=Vulkan, #spirv.resource_limits<max_compute_workgroup_size = [128, 128, 64], subgroup_size = 64, cooperative_matrix_properties_nv = []>>}>
<eval_with_key>.3:33:14: error: failed to serialize executables
<unknown>:0: error: failed to legalize operation 'vector.bitcast'
<eval_with_key>.3:71:14: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.3, [Shader, GroupNonUniform], [SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers]>, api=Vulkan, #spirv.resource_limits<max_compute_workgroup_size = [128, 128, 64], subgroup_size = 64, cooperative_matrix_properties_nv = []>>}>
<eval_with_key>.3:71:14: error: failed to serialize executables

Invoked with:
 iree-compile.exe C:\Users\jwalt\AppData\Local\Temp\_MEI73802\iree\compiler\tools\..\_mlir_libs\iree-compile.exe - --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --iree-llvmcpu-embedded-linker-path=C:\Users\jwalt\AppData\Local\Temp\_MEI73802\iree\compiler\tools\..\_mlir_libs\iree-lld.exe --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs --iree-preprocessing-pass-pipeline=builtin.module(func.func(iree-flow-detach-elementwise-from-named-ops,iree-flow-convert-1x1-filter-conv2d-to-matmul,iree-preprocessing-convert-conv2d-to-img2col,iree-preprocessing-pad-linalg-ops{pad-size=32}))

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.

Retrying with a different base model configuration
mat1 and mat2 shapes cannot be multiplied (128x768 and 1024x320)
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
Retrying with a different base model configuration
Traceback (most recent call last):
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 396, in from_pretrained
  File "apps\stable_diffusion\src\models\opt_params.py", line 89, in get_vae
  File "apps\stable_diffusion\src\utils\utils.py", line 85, in get_shark_model
  File "apps\stable_diffusion\src\utils\utils.py", line 56, in _compile_module
  File "shark\shark_inference.py", line 188, in save_module
  File "shark\iree_utils\compile_utils.py", line 345, in export_iree_module_to_vmfb
  File "shark\iree_utils\compile_utils.py", line 281, in compile_module_to_flatbuffer
  File "iree\compiler\tools\core.py", line 280, in compile_str
  File "iree\compiler\tools\binaries.py", line 198, in invoke_immediate
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile.exe
Diagnostics:
<unknown>:0: error: failed to legalize operation 'vector.bitcast'
<eval_with_key>.197:8:18: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.3, [Shader, GroupNonUniform], [SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers]>, api=Vulkan, #spirv.resource_limits<max_compute_workgroup_size = [128, 128, 64], subgroup_size = 64, cooperative_matrix_properties_nv = []>>}>
<eval_with_key>.197:8:18: error: failed to serialize executables
<unknown>:0: error: failed to legalize operation 'vector.bitcast'
<eval_with_key>.197:111:12: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.3, [Shader, GroupNonUniform], [SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers]>, api=Vulkan, #spirv.resource_limits<max_compute_workgroup_size = [128, 128, 64], subgroup_size = 64, cooperative_matrix_properties_nv = []>>}>
<eval_with_key>.197:111:12: error: failed to serialize executables
<unknown>:0: error: failed to legalize operation 'vector.bitcast'
<eval_with_key>.197:118:12: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.3, [Shader, GroupNonUniform], [SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers]>, api=Vulkan, #spirv.resource_limits<max_compute_workgroup_size = [128, 128, 64], subgroup_size = 64, cooperative_matrix_properties_nv = []>>}>
<eval_with_key>.197:118:12: error: failed to serialize executables
<unknown>:0: error: failed to legalize operation 'vector.bitcast'
<eval_with_key>.197:144:14: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.3, [Shader, GroupNonUniform], [SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers]>, api=Vulkan, #spirv.resource_limits<max_compute_workgroup_size = [128, 128, 64], subgroup_size = 64, cooperative_matrix_properties_nv = []>>}>
<eval_with_key>.197:144:14: error: failed to serialize executables
<unknown>:0: error: failed to legalize operation 'vector.bitcast'
<eval_with_key>.197:147:12: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.3, [Shader, GroupNonUniform], [SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers]>, api=Vulkan, #spirv.resource_limits<max_compute_workgroup_size = [128, 128, 64], subgroup_size = 64, cooperative_matrix_properties_nv = []>>}>
<eval_with_key>.197:147:12: error: failed to serialize executables
<unknown>:0: error: failed to legalize operation 'vector.bitcast'
<eval_with_key>.197:155:12: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.3, [Shader, GroupNonUniform], [SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers]>, api=Vulkan, #spirv.resource_limits<max_compute_workgroup_size = [128, 128, 64], subgroup_size = 64, cooperative_matrix_properties_nv = []>>}>
<eval_with_key>.197:155:12: error: failed to serialize executables

Invoked with:
 iree-compile.exe C:\Users\jwalt\AppData\Local\Temp\_MEI73802\iree\compiler\tools\..\_mlir_libs\iree-compile.exe - --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --iree-llvmcpu-embedded-linker-path=C:\Users\jwalt\AppData\Local\Temp\_MEI73802\iree\compiler\tools\..\_mlir_libs\iree-lld.exe --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs --iree-preprocessing-pass-pipeline=builtin.module(func.func(iree-flow-detach-elementwise-from-named-ops,iree-preprocessing-pad-linalg-ops{pad-size=32}))

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gradio\routes.py", line 394, in run_predict
  File "gradio\blocks.py", line 1075, in process_api
  File "gradio\blocks.py", line 898, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "gradio\utils.py", line 549, in async_iteration
  File "apps\stable_diffusion\scripts\txt2img.py", line 125, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 429, in from_pretrained
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 677, in __call__
SystemExit: Cannot compile the model. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues
Keyboard interruption in main thread... closing server.

(base) C:\stable-diffusion\Shark0321.625>`

**Comment by powderluv** [comment]
This is the same issue with some other hardware I filed earlier this week https://github.com/openxla/iree/issues/12708 

This is via the ARC vulkan driver. We also have the Level Zero driver for ARC and the code to run on it but it hasn't been tested on Windows yet.

**Comment by jarredwalton** [comment]
Cheers. I searched for "Intel Arc" and didn't get any hits, so I posted this as a new issue. If you need me to test anything, just let me know.

**Comment by powderluv** [comment]
@jarredwalton if possible can you please attach your `vulkaninfo` output. We will need to enable a target triple for it.

**Comment by jarredwalton** [comment]
Oh... I swapped GPUs from the A750 (used for the earlier report) to an A380. I'm not sure if they give identical vulkaninfo reports, though.

**Comment by powderluv** [comment]
I tried it on my A770 with base configs for a SIMT pipeline (like rdna2) and it failed with a black image. Will need to expose the Arc more cleanly to make sure it isn't a codegen problem and then follow up on the vulkan driver side of things.
