### ISSUE TITLE
Cannot compile the model. Please create an issue with the detailed log at

### ISSUE THREAD

**Issue by ildisc77** [nod-ai/SHARK#1261]
Retrying with a different base model configuration
Retrying with a different base model configuration
Retrying with a different base model configuration
Retrying with a different base model configuration
Traceback (most recent call last):
  File "gradio\routes.py", line 384, in run_predict
  File "gradio\blocks.py", line 1032, in process_api
  File "gradio\blocks.py", line 858, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "gradio\utils.py", line 448, in async_iteration
  File "apps\stable_diffusion\scripts\txt2img.py", line 122, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 356, in from_pretrained
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 543, in __call__
SystemExit:

**Comment by cstueckrath** [comment]
we follow that issue here:
https://discord.com/channels/973663919757492264/1090650063988068422/1090650063988068422

given information:
Shark (202030310_592) 
GPU (RX 590 8GB)
OS (WIN 10)
driver version (adrenalin edition 23.2.1 feb 14)

**Comment by cstueckrath** [comment]
issue resolved after removing some left overs in registry and running SHARK as admin once.
HF wanted to create a symlink and couldn't.
Maybe some additional download problems, too. Hard to say what exactly fixed the issue
