### ISSUE TITLE
img2img on 768x512 running out memory

### ISSUE THREAD

**Issue by ledroyy** [nod-ai/SHARK#1268]
Prompts on 768x512 or 512x768 will make one image but trying again will show this error "VK_ERROR_OUT_OF_DEVICE_MEMORY". If I try changing the model or size it crashes and closes shark. 
img2img on 512x512 has no errors

Version 648 - GPU RX 5700 XT 8G, 16G ram

**Comment by ledroyy** [comment]
Still running out of memory but at least I can change models and size without having to re-open shark everytime. Might have to change to 640x512 or change heap size 

```
Traceback (most recent call last):
  File "gradio\routes.py", line 393, in run_predict
  File "gradio\blocks.py", line 1108, in process_api
  File "gradio\blocks.py", line 929, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "gradio\utils.py", line 490, in async_iteration
  File "apps\stable_diffusion\scripts\img2img.py", line 253, in img2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_img2img.py", line 178, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 202, in produce_img_latents
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 103, in load_unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 586, in unet
  File "apps\stable_diffusion\src\utils\utils.py", line 611, in fetch_vmfb
  File "apps\stable_diffusion\src\utils\utils.py", line 602, in load_vmfb
  File "shark\shark_inference.py", line 207, in load_module
  File "shark\iree_utils\compile_utils.py", line 333, in load_flatbuffer
  File "shark\iree_utils\compile_utils.py", line 309, in get_iree_module
  File "iree\runtime\system_api.py", line 255, in add_vm_module
  File "iree\runtime\system_api.py", line 252, in add_vm_modules
RuntimeError: Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\vma_allocator.cc:693: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.allocator.allocate; while calling import;
[ 1]   native hal.allocator.allocate:0 -
[ 0] bytecode module@1:26852 -
```

![image](https://user-images.githubusercontent.com/108599556/230213138-6fe25a4e-a116-43a3-a376-a33c5f467d1c.png)

**Comment by jinchen62** [comment]
@ledroyy Hi, could you track your memory usage to see how it increases for the second generation?

**Comment by ledroyy** [comment]
For the first generation 6648MB VRAM  and Second generation 7667 MB VRAM
RAM stays at 10.4 GB
