### ISSUE TITLE
680 - broken on rdna2 rx6700 - API mismatch and misc other errors

### ISSUE THREAD

**Issue by GoZippy** [nod-ai/SHARK#1309]
Found device AMD Radeon RX 6700 XT. Using target triple rdna2-unknown-windows.
Using tuned models for CompVis/stable-diffusion-v1-4/fp16/vulkan://00000000-0300-0000-0000-000000000000.
loading existing vmfb from: E:\ImageAI\shark\euler_scale_model_input_1_512_512fp16.vmfb
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
Traceback (most recent call last):
  File "gradio\routes.py", line 401, in run_predict
  File "gradio\blocks.py", line 1302, in process_api
  File "gradio\blocks.py", line 1039, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "gradio\utils.py", line 491, in async_iteration
  File "ui\txt2img_ui.py", line 138, in txt2img_inf
  File "apps\stable_diffusion\src\schedulers\sd_schedulers.py", line 65, in get_schedulers
  File "apps\stable_diffusion\src\schedulers\shark_eulerdiscrete.py", line 110, in compile
  File "apps\stable_diffusion\src\schedulers\shark_eulerdiscrete.py", line 92, in _import
  File "apps\stable_diffusion\src\utils\utils.py", line 140, in compile_through_fx
  File "apps\stable_diffusion\src\utils\utils.py", line 47, in _compile_module
  File "shark\shark_inference.py", line 207, in load_module
  File "shark\iree_utils\compile_utils.py", line 333, in load_flatbuffer
  File "shark\iree_utils\compile_utils.py", line 305, in get_iree_module
ValueError: Error creating vm module from FlatBuffer: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\vm\bytecode\verifier.c:180: INVALID_ARGUMENT; bytecode version mismatch; runtime supports 15.0, module has 14.0

**Comment by monorimet** [comment]
Can you make sure SHARK is not using old .vmfb files? If you've recently updated SHARK-runtime version this is probably the cause.
They can be cleared with `--clear_all`.
If you have local .mlir files they might also be outdated
If your `local_tank_cache` is default these old .mlir would be at `C:\Users\username\.local\shark_tank\`

**Comment by GoZippy** [comment]
I did... I deleted everything and started over with 680 and it seems to be working with not using tuned. When I run now without that it brings back the blue artifacts. Either way I tend to crash current amd radeon drivers and have to reload after a few runs.

**Comment by GoZippy** [comment]
using --clear_all and --no_use_tuned   it seems to work for txt2img but not much else. With these two flags set - I can run with Low VRAM and it will only generate one image regardless of the batch settings. 

Without low vram set - it will generate the batch count number of images.

In each of these cases - with the --no_use_tuned the blue artifacts are gone or mostly gone from view from what I can tell now.

One other thing though - it will ONLY work with these 2 flags set with GPU. When I try to select CPU only it is broken and stops the script.

**Comment by GoZippy** [comment]
yeah no matter what I do - with 680 current amd driver crashes after any length of use... going to try in islated envirnment and nothing else running..

**Comment by GoZippy** [comment]
Using pre680 version, --no_use_tuned, unstable driver with 23.4.1 Radeon - "driver timeout" error with rdna2 device - rx 6700 xt

**Comment by monorimet** [comment]
Thanks for the updates. The `Low VRAM` option will force batch count to 1, as it loads and unloads the .vmfb data on demand.
@jinchen62 we should see if this is something that can be improved or worked around -- maybe it's possible to queue the batches outside of the load/unload schema, but I assume this will be a nontrivial change to the SD pipelines.
