### ISSUE TITLE
Build 680 - Could not compile Unet

### ISSUE THREAD

**Issue by xzuyn** [nod-ai/SHARK#1311]
RX 480 8GB `.\shark_sd_20230416_680.exe --vulkan_large_heap_block_size 0 --device_allocator caching --attention-slicing max --local_tank_cache="Z:\shark\SHARK_EXE\shark_tank" --output_dir="Z:\shark\SHARK_EXE\output" --api --server_port=8082` tried without the device allocator or attention slicing, same issue.

```
ERROR: [Loader Message] Code 0 : Failed to open dynamic library "C:\Program Files (x86)\Overwolf\0.221.0.4\.\owclient.dll" with error 1114
Loading Winograd config file from  Z:\shark\SHARK_EXE\shark_tank\configs\vae_winograd_vulkan.json
100%|█████████████████████████████████████████████████████████████████████████████████| 33.0/33.0 [00:00<00:00, 599B/s]
100%|█████████████████████████████████████████████████████████████████████████████████| 33.0/33.0 [00:00<00:00, 647B/s]
No vmfb found. Compiling and saving to Z:\shark\SHARK_EXE\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Error invoking IREE compiler tool iree-compile.exe
Diagnostics:
<eval_with_key>.16:597:20: error: failed to legalize operation 'arith.constant'
<eval_with_key>.16:597:20: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.6, [Shader, Float64, Float16, Int64, Int16, Int8, StorageBuffer16BitAccess, StorageUniform16, StoragePushConstant16, StorageBuffer8BitAccess, UniformAndStorageBuffer8BitAccess, StoragePushConstant8, GroupNonUniform, GroupNonUniformVote, GroupNonUniformArithmetic, GroupNonUniformBallot, GroupNonUniformShuffle, GroupNonUniformShuffleRelative, GroupNonUniformClustered, GroupNonUniformQuad, VariablePointers, VariablePointersStorageBuffer], [SPV_KHR_16bit_storage, SPV_KHR_8bit_storage, SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers]>, api=Vulkan, AMD:DiscreteGPU, #spirv.resource_limits<max_compute_shared_memory_size = 65536, max_compute_workgroup_invocations = 1024, max_compute_workgroup_size = [1024, 1024, 1024], subgroup_size = 64, min_subgroup_size = 32, max_subgroup_size = 64, cooperative_matrix_properties_nv = []>>}>
<eval_with_key>.16:597:20: error: failed to serialize executables
<eval_with_key>.16:637:13: error: failed to legalize operation 'arith.constant'
<eval_with_key>.16:637:13: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.6, [Shader, Float64, Float16, Int64, Int16, Int8, StorageBuffer16BitAccess, StorageUniform16, StoragePushConstant16, StorageBuffer8BitAccess, UniformAndStorageBuffer8BitAccess, StoragePushConstant8, GroupNonUniform, GroupNonUniformVote, GroupNonUniformArithmetic, GroupNonUniformBallot, GroupNonUniformShuffle, GroupNonUniformShuffleRelative, GroupNonUniformClustered, GroupNonUniformQuad, VariablePointers, VariablePointersStorageBuffer], [SPV_KHR_16bit_storage, SPV_KHR_8bit_storage, SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers]>, api=Vulkan, AMD:DiscreteGPU, #spirv.resource_limits<max_compute_shared_memory_size = 65536, max_compute_workgroup_invocations = 1024, max_compute_workgroup_size = [1024, 1024, 1024], subgroup_size = 64, min_subgroup_size = 32, max_subgroup_size = 64, cooperative_matrix_properties_nv = []>>}>
<eval_with_key>.16:637:13: error: failed to serialize executables
<eval_with_key>.16:671:13: error: failed to legalize operation 'arith.constant'
<eval_with_key>.16:671:13: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.6, [Shader, Float64, Float16, Int64, Int16, Int8, StorageBuffer16BitAccess, StorageUniform16, StoragePushConstant16, StorageBuffer8BitAccess, UniformAndStorageBuffer8BitAccess, StoragePushConstant8, GroupNonUniform, GroupNonUniformVote, GroupNonUniformArithmetic, GroupNonUniformBallot, GroupNonUniformShuffle, GroupNonUniformShuffleRelative, GroupNonUniformClustered, GroupNonUniformQuad, VariablePointers, VariablePointersStorageBuffer], [SPV_KHR_16bit_storage, SPV_KHR_8bit_storage, SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers]>, api=Vulkan, AMD:DiscreteGPU, #spirv.resource_limits<max_compute_shared_memory_size = 65536, max_compute_workgroup_invocations = 1024, max_compute_workgroup_size = [1024, 1024, 1024], subgroup_size = 64, min_subgroup_size = 32, max_subgroup_size = 64, cooperative_matrix_properties_nv = []>>}>
<eval_with_key>.16:671:13: error: failed to serialize executables


Invoked with:
 iree-compile.exe C:\Users\[USERNAME]\AppData\Local\Temp\_MEI149842\iree\compiler\tools\..\_mlir_libs\iree-compile.exe - --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --iree-llvmcpu-embedded-linker-path=C:\Users\[USERNAME]\AppData\Local\Temp\_MEI149842\iree\compiler\tools\..\_mlir_libs\iree-lld.exe --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-vulkan-target-env=#vk.target_env<v1.3, r(120), [VK_KHR_16bit_storage, VK_KHR_8bit_storage, VK_KHR_shader_float16_int8, VK_KHR_spirv_1_4, VK_KHR_storage_buffer_storage_class, VK_KHR_variable_pointers, VK_EXT_subgroup_size_control], AMD:DiscreteGPU, #vk.caps< maxComputeSharedMemorySize = 65536, maxComputeWorkGroupInvocations = 1024, maxComputeWorkGroupSize = dense<[1024, 1024, 1024]>: vector<3xi32>, subgroupSize = 64, subgroupFeatures = 255: i32, minSubgroupSize = 32, maxSubgroupSize = 64, shaderFloat16 = unit, shaderFloat64 = unit, shaderInt8 = unit, shaderInt16 = unit, shaderInt64 = unit, storageBuffer16BitAccess = unit, storagePushConstant16 = unit, uniformAndStorageBuffer16BitAccess = unit, storageBuffer8BitAccess = unit, storagePushConstant8 = unit, uniformAndStorageBuffer8BitAccess = unit, variablePointers = unit, variablePointersStorageBuffer = unit >> --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-vm-bytecode-module-strip-source-map=true --iree-util-zero-fill-elided-attrs -iree-vulkan-target-triple=rdna2-unknown-windows

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.

Retrying with a different base model configuration
mat1 and mat2 shapes cannot be multiplied (128x768 and 1024x320)
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[4, 7, 512, 512] to have 4 channels, but got 7 channels instead
Retrying with a different base model configuration
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 429, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 78, in __call__
  File "fastapi\applications.py", line 276, in __call__
  File "starlette\applications.py", line 122, in __call__
  File "starlette\middleware\errors.py", line 162, in __call__
  File "starlette\middleware\exceptions.py", line 68, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 18, in __call__
  File "starlette\routing.py", line 718, in __call__
  File "starlette\routing.py", line 276, in handle
  File "starlette\routing.py", line 66, in app
  File "fastapi\routing.py", line 237, in app
  File "fastapi\routing.py", line 165, in run_endpoint_function
  File "starlette\concurrency.py", line 41, in run_in_threadpool
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "ui\img2img_ui.py", line 299, in img2img_api
  File "ui\img2img_ui.py", line 231, in img2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_img2img.py", line 178, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 203, in produce_img_latents
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 103, in load_unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 631, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 626, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 60, in check_compilation
SystemExit: Could not compile Unet. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues
```

**Comment by monorimet** [comment]
Thanks for reporting this issue. I am debugging it this morning. It seems that the Unet lowering/tuning configs are not applied on first generation or with `--clear_all`. The lowering configs are necessary for certain RDNA targets, so without them we see this error with lowering `arith.constant`.

I should have a solution soon, but in the meantime, if you run into this error, you can immediately restart SHARK SD without the `--clear_all` flag and try img2img again -- it should apply the lowering config successfully.

You'll know it's getting the configs correctly if you see these lines when compiling Unet:

```
Loading Winograd config file from  C:\Users\ean\.local/shark_tank/configs\unet_winograd_vulkan.json
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 1.57kB/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 1.86kB/s]
Loading lowering config file from  C:\Users\ean\.local/shark_tank/configs\unet_v2_1base_fp16_vulkan_rdna2.json
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24.2k/24.2k [00:00<00:00, 264kB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24.2k/24.2k [00:00<00:00, 784kB/s]
```
