### ISSUE TITLE
Doesn't work on my 1060 with Vulkan, Cuda, or CPU using executable on Windows 10.

### ISSUE THREAD

**Issue by GeneralAwareness** [nod-ai/SHARK#1343]
Is there a log file somewhere I can post here?

CUDA
`Found 1 device(s).
Device: 0
  Name: NVIDIA GeForce GTX 1060 6GB
  Compute Capability: 6.1
Saved vmfb in D:\SHARK\unet_1_64_512_512_fp16_stable-diffusion-2-1-base_cuda.vmfb.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "gradio\routes.py", line 401, in run_predict
  File "gradio\blocks.py", line 1302, in process_api
  File "gradio\blocks.py", line 1039, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "gradio\utils.py", line 491, in async_iteration
  File "ui\txt2img_ui.py", line 173, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 122, in generate_images
    latents = self.produce_img_latents(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 207, in produce_img_latents
    latent_model_input = self.scheduler.scale_model_input(latents, t)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps\stable_diffusion\src\schedulers\shark_eulerdiscrete.py", line 134, in scale_model_input
    return self.scaling_model(
           ^^^^^^^^^^^^^^^^^^^
  File "shark\shark_inference.py", line 138, in __call__
    return self.shark_runner.run(function_name, inputs, send_to_host)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "shark\shark_runner.py", line 93, in run
    return get_results(
           ^^^^^^^^^^^^
  File "shark\iree_utils\compile_utils.py", line 385, in get_results
    result = compiled_vm[function_name](*device_inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "iree\runtime\function.py", line 130, in __call__
  File "iree\runtime\function.py", line 154, in _invoke
RuntimeError: Error invoking function: <vm>:0: UNKNOWN; device not supported in the compiled configuration;
[ 0] bytecode module@0:416 -
Tuned models are currently not supported for this setting.
failed to download model, falling back and using import_mlir
loading existing vmfb from: D:\SHARK\euler_scale_model_input_1_512_512fp16.vmfb
loading existing vmfb from: D:\SHARK\euler_step_1_512_512fp16.vmfb
use_tuned? sharkify: False`

Vulcan

`Found 1 device(s).
Device: 0
  Name: NVIDIA GeForce GTX 1060 6GB
  Compute Capability: 6.1
Saved vmfb in D:\SHARK\unet_1_64_512_512_fp16_stable-diffusion-2-1-base_cuda.vmfb.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "gradio\routes.py", line 401, in run_predict
  File "gradio\blocks.py", line 1302, in process_api
  File "gradio\blocks.py", line 1039, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "gradio\utils.py", line 491, in async_iteration
  File "ui\txt2img_ui.py", line 173, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 122, in generate_images
    latents = self.produce_img_latents(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 207, in produce_img_latents
    latent_model_input = self.scheduler.scale_model_input(latents, t)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps\stable_diffusion\src\schedulers\shark_eulerdiscrete.py", line 134, in scale_model_input
    return self.scaling_model(
           ^^^^^^^^^^^^^^^^^^^
  File "shark\shark_inference.py", line 138, in __call__
    return self.shark_runner.run(function_name, inputs, send_to_host)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "shark\shark_runner.py", line 93, in run
    return get_results(
           ^^^^^^^^^^^^
  File "shark\iree_utils\compile_utils.py", line 385, in get_results
    result = compiled_vm[function_name](*device_inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "iree\runtime\function.py", line 130, in __call__
  File "iree\runtime\function.py", line 154, in _invoke
RuntimeError: Error invoking function: <vm>:0: UNKNOWN; device not supported in the compiled configuration;
[ 0] bytecode module@0:416 -
Tuned models are currently not supported for this setting.
failed to download model, falling back and using import_mlir
loading existing vmfb from: D:\SHARK\euler_scale_model_input_1_512_512fp16.vmfb
loading existing vmfb from: D:\SHARK\euler_step_1_512_512fp16.vmfb
use_tuned? sharkify: False`

CPU
`_1_64_512_512_fp16_stable-diffusion-2-1-base
No vmfb found. Compiling and saving to D:\SHARK\clip_1_64_512_512_fp16_stable-diffusion-2-1-base_cpu.vmfb
Target triple found:x86_64-pc-windows-msvc
Saved vmfb in D:\SHARK\clip_1_64_512_512_fp16_stable-diffusion-2-1-base_cpu.vmfb.
No vmfb found. Compiling and saving to D:\SHARK\unet_1_64_512_512_fp16_stable-diffusion-2-1-base_cpu.vmfb
Target triple found:x86_64-pc-windows-msvc
Traceback (most recent call last):
  File "gradio\routes.py", line 401, in run_predict
  File "gradio\blocks.py", line 1302, in process_api
  File "gradio\blocks.py", line 1039, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "gradio\utils.py", line 491, in async_iteration
  File "ui\txt2img_ui.py", line 173, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 122, in generate_images
    latents = self.produce_img_latents(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 203, in produce_img_latents
    self.load_unet()
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 103, in load_unet
    self.unet = self.sd_model.unet()
                ^^^^^^^^^^^^^^^^^^^^
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 640, in unet
    sys.exit(e)
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 611, in unet
    compiled_unet, unet_mlir = self.compile_unet_variants(model)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 575, in compile_unet_variants
    return self.get_unet()
           ^^^^^^^^^^^^^^^
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 450, in get_unet
    shark_unet, unet_mlir = compile_through_fx(
                            ^^^^^^^^^^^^^^^^^^^
  File "apps\stable_diffusion\src\utils\utils.py", line 157, in compile_through_fx
    _compile_module(shark_module, extended_model_name, extra_args),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps\stable_diffusion\src\utils\utils.py", line 66, in _compile_module
    path = shark_module.save_module(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "shark\shark_inference.py", line 188, in save_module
    return export_iree_module_to_vmfb(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "shark\iree_utils\compile_utils.py", line 346, in export_iree_module_to_vmfb
    flatbuffer_blob = compile_module_to_flatbuffer(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "shark\iree_utils\compile_utils.py", line 274, in compile_module_to_flatbuffer
    flatbuffer_blob = ireec.compile_str(
                      ^^^^^^^^^^^^^^^^^^
  File "iree\compiler\tools\core.py", line 280, in compile_str
  File "iree\compiler\tools\binaries.py", line 196, in invoke_immediate
SystemExit: Error invoking IREE compiler tool iree-compile.exe
Diagnostics:
iree-lld: error: undefined symbol: fmaxf
>>> referenced by <eval_with_key>.38:191
>>>               C:\Users\MobRules\AppData\Local\Temp\llvm_module_linked_llvm_cpu-b75877.o:(forward_dispatch_47_softmax_2x5x4096x4096xf16)
>>> referenced by <eval_with_key>.38:191
>>>               C:\Users\MobRules\AppData\Local\Temp\llvm_module_linked_llvm_cpu-b75877.o:(forward_dispatch_47_softmax_2x5x4096x4096xf16)
>>> referenced by <eval_with_key>.38:191
>>>               C:\Users\MobRules\AppData\Local\Temp\llvm_module_linked_llvm_cpu-b75877.o:(forward_dispatch_47_softmax_2x5x4096x4096xf16)
>>> referenced 837 more times
>>> did you mean: fmaf
>>> defined in: C:\Users\MobRules\AppData\Local\Temp\llvm_module_linked_llvm_cpu-b75877.o
Linking failed; escaped command line returned exit code 1:

set LLD_VERSION=IREE && C:\Users\MobRules\AppData\Local\Temp\_MEI141802\iree\compiler\tools\..\_mlir_libs\iree-lld.exe -flavor gnu -o C:\Users\MobRules\AppData\Local\Temp\llvm_module_linked_llvm_cpu-b75877.so --build-id=none -nostdlib -static -shared --no-undefined --no-allow-shlib-undefined --allow-multiple-definition --gc-sections -z now -z relro --discard-all --icf=all --ignore-data-address-equality --ignore-function-address-equality --hash-style=sysv C:\Users\MobRules\AppData\Local\Temp\llvm_module_linked_llvm_cpu-b75877.o

<unknown>:0: error: failed to link executable and generate target dylib (check above for more specific error messages)
<unknown>:0: error: failed to serialize executable for target backend llvm-cpu
<unknown>:0: error: failed to serialize executables

Invoked with:
 iree-compile.exe C:\Users\MobRules\AppData\Local\Temp\_MEI141802\iree\compiler\tools\..\_mlir_libs\iree-compile.exe - --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-embedded-linker-path=C:\Users\MobRules\AppData\Local\Temp\_MEI141802\iree\compiler\tools\..\_mlir_libs\iree-lld.exe --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-llvmcpu-target-triple=x86_64-pc-windows-msvc --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-vm-bytecode-module-strip-source-map=true --iree-util-zero-fill-elided-attrs --iree-preprocessing-pass-pipeline=builtin.module(func.func(iree-flow-detach-elementwise-from-named-ops,iree-flow-convert-1x1-filter-conv2d-to-matmul,iree-preprocessing-convert-conv2d-to-img2col,iree-preprocessing-pad-linalg-ops{pad-size=32}))

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.`

**Comment by GeneralAwareness** [comment]
Tried it with a model I use all the time and

`Traceback (most recent call last):
  File "torch\serialization.py", line 443, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "torch\serialization.py", line 670, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
RuntimeError: [enforce fail at ..\caffe2\serialize\inline_container.cc:474] . PytorchStreamWriter failed writing file data/89: file write failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gradio\routes.py", line 401, in run_predict
  File "gradio\blocks.py", line 1302, in process_api
  File "gradio\blocks.py", line 1039, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "gradio\utils.py", line 491, in async_iteration
  File "ui\txt2img_ui.py", line 142, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 308, in from_pretrained
    sd_model = SharkifyStableDiffusionModel(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 143, in __init__
    preprocessCKPT(self.custom_weights, self.is_inpaint)
  File "apps\stable_diffusion\src\utils\utils.py", line 502, in preprocessCKPT
    pipe.save_pretrained(path_to_diffusers)
  File "diffusers\pipelines\pipeline_utils.py", line 531, in save_pretrained
  File "diffusers\models\modeling_utils.py", line 315, in save_pretrained
  File "torch\serialization.py", line 442, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "torch\serialization.py", line 293, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at ..\caffe2\serialize\inline_container.cc:335] . unexpected pos 3435657408 vs 3435657296`

**Comment by powderluv** [comment]
I think for 1060 best option is Vulkan. But looks like there were old .vmfb files in the directory. Can you please try build 696 or higher and delete all vmfb and report any errors with Vulkan ?

**Comment by GeneralAwareness** [comment]
Just going to close this ticket as this is never going to work with my card as there are just too many issues as we spoke on discord.

Thanks again.

**Comment by powderluv** [comment]
I just pushed a fix for compiling on [Pascal](https://github.com/nod-ai/SHARK/commit/09e3f63d5b900a2acd0d386086a343d39bee1c38). Please give it a try and report any issues. I am able to compile as 1060 on my 4090.
