### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by MalkGabe** [nod-ai/SHARK#1363]
Getting this error:

Exception in thread Thread-11 (_readerthread):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "subprocess.py", line 1552, in _readerthread
MemoryError

Not sure what to do with it.

**Comment by Robbson** [comment]
Same here, tested several versions (including stable) using Vulkan while ROCm shows a different error. 
And then you have to restart the server again, waiting again a minute or so... 🙄.
No way to get it working on a Radeon RX 6800 with 16GB VRAM.
The app from automatic1111 is pretty slow but at least it works.

**Comment by Robbson** [comment]
UPDATE: Seems like 32GB system memory isn't enough. After closing the browser and other software the developer's version build from source doesn't show this error but crashs with a different issue later.

Interesting: Using the prebuild executables still leads to the memory issue as if they even need more memory.
