### ISSUE TITLE
714 broke - 712 still launches ok

### ISSUE THREAD

**Issue by GoZippy** [nod-ai/SHARK#1397]
**ModuleNotFoundError: No module named 'iree.compiler._mlir_libs._mlir.ir'**

714 on 6700XT
Won't load...

```
PS E:\ImageAI\shark> .\shark_sd_20230504_714.exe
Traceback (most recent call last):
  File "index.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "apps\stable_diffusion\src\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "apps\stable_diffusion\src\utils\__init__.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "apps\stable_diffusion\src\utils\sd_annotation.py", line 3, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "shark\model_annotation.py", line 33, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "iree\compiler\ir.py", line 5, in <module>
ModuleNotFoundError: No module named 'iree.compiler._mlir_libs._mlir.ir'
[7500] Failed to execute script 'index' due to unhandled exception!
PS E:\ImageAI\shark>
```

**Comment by monorimet** [comment]
714 is broken, there was an upstream change that breaks some python bindings for IREE.
There is a fix in the works, it is high priority.

**Comment by GoZippy** [comment]
ok - FYI that bug on initial launch where I had to hit enter to get the server to proceed is back... 

Launch in window, the auto open browser is not working now - so I open new browser window and go there manually - seems to respond ok and open the webui - plug in initial prompts and setting and GENERATE and it just sits there - the cmd window does not see anything... then I hit ENTER on cmd window and it starts moving again - the next thing it shows on screen is that it found the AMD device and it starts working...


```
PS E:\ImageAI\shark> .\shark_sd_20230503_712.exe
shark_tank local cache is located at C:\Users\gotad\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
vulkan devices are available.
cuda devices are not available.
diffusers\models\cross_attention.py:30: FutureWarning: Importing from cross_attention is deprecated. Please import from diffusers.models.attention_processor instead.
Sucessfully loaded the tokenizer to the memory
shark_tank local cache is located at C:\Users\gotad\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
```
**then it just sits here without any user interaction - and I have to hit ENTER and it then kicks into gear again..**

```

Found device AMD Radeon RX 6700 XT. Using target triple rdna2-unknown-windows.
Using tuned models for CompVis/stable-diffusion-v1-4/fp16/vulkan://00000000-0300-0000-0000-000000000000.
loading existing vmfb from: E:\ImageAI\shark\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
loading existing vmfb from: E:\ImageAI\shark\euler_step_1_512_512_vulkan_fp16.vmfb
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
use_tuned? sharkify: True
_1_64_512_512_fp16_tuned_realisticVisionV13_v13
Diffusers' checkpoint will be identified here :  E:/ImageAI/shark/models/diffusers/realisticVisionV13_v13

```
