### ISSUE TITLE
SystemExit: Could not compile Unet.

### ISSUE THREAD

**Issue by pedroquintanilla** [nod-ai/SHARK#1438]
Microsoft Windows [Versión 10.0.19045.3030]
(c) Microsoft Corporation. Todos los derechos reservados.

C:\stable-diffusion\shark>C:\stable-diffusion\shark\shark_sd_20230513_727.exe
shark_tank local cache is located at C:\Users\PC\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
vulkan devices are available.
cuda devices are not available.
gradio\components.py:153: UserWarning: Unknown style parameter: columns
gradio\components.py:153: UserWarning: Unknown style parameter: object_fit
diffusers\models\cross_attention.py:30: FutureWarning: Importing from cross_attention is deprecated. Please import from diffusers.models.attention_processor instead.
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
shark_tank local cache is located at C:\Users\PC\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Found device Radeon RX550/550 Series. Using target triple rdna2-unknown-windows.
Using tuned models for stabilityai/stable-diffusion-2-1-base/fp16/vulkan://00000000-0100-0000-0000-000000000000.
loading existing vmfb from: C:\stable-diffusion\shark\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
loading existing vmfb from: C:\stable-diffusion\shark\euler_step_1_512_512_vulkan_fp16.vmfb
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
use_tuned? sharkify: True
_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
Loading Winograd config file from  C:\Users\PC\.local/shark_tank/configs\unet_winograd_vulkan.json
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 1.07kB/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 1.05kB/s]
list index out of range
Retrying with a different base model configuration
mat1 and mat2 shapes cannot be multiplied (128x768 and 1024x320)
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[4, 7, 512, 512] to have 4 channels, but got 7 channels instead
Retrying with a different base model configuration
Traceback (most recent call last):
  File "gradio\routes.py", line 393, in run_predict
  File "gradio\blocks.py", line 1069, in process_api
  File "gradio\blocks.py", line 892, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "gradio\utils.py", line 549, in async_iteration
  File "ui\txt2img_ui.py", line 180, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 122, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 203, in produce_img_latents
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 103, in load_unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 656, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 651, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 62, in check_compilation
SystemExit: Could not compile Unet. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues

**Comment by dtroupe2** [comment]
I get this same error on any version post 724.

**Comment by Sparko10** [comment]
Getting same thing on version 819. Started with a fresh copy of shark in empty folder. every time it tries to start up and compile the models it ends up crashing with Could not compile unet. Also some other errors along the way. Canceling and starting over keeps ending at the same thing. Windows 11, Ryzen 3200G, AMD Radeon 6700 XT, 16GB RAM. 
Full run log:

________________
Microsoft Windows [Version 10.0.22621.1992]
(c) Microsoft Corporation. All rights reserved.

D:\Sharkai>sharke.exe
'sharke.exe' is not recognized as an internal or external command,
operable program or batch file.

D:\Sharkai>ls
'ls' is not recognized as an internal or external command,
operable program or batch file.

D:\Sharkai>dir
 Volume in drive D is Data
 Volume Serial Number is D84E-ABEA

 Directory of D:\Sharkai

07/13/2023  11:47 AM    <DIR>          .
07/13/2023  11:47 AM     1,361,881,473 clip_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb
07/13/2023  11:45 AM             6,160 euler_scale_model_input_1_512_512_vulkan_fp16.vmfb
07/13/2023  11:45 AM             6,136 euler_step_1_512_512_vulkan_fp16.vmfb
07/13/2023  11:44 AM    <DIR>          models
07/13/2023  09:52 AM       457,803,296 Shark.exe
07/13/2023  11:43 AM    <DIR>          shark_tmp
               4 File(s)  1,819,697,065 bytes
               3 Dir(s)  1,859,615,715,328 bytes free


shark_tank local cache is located at C:\Users\pixel\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
gradio temporary image cache located at D:\Sharkai\shark_tmp/gradio. You may change this by setting the GRADIO_TEMP_DIR environment variable.
No temporary images files to clear.
vulkan devices are available.
shark_tank local cache is located at C:\Users\pixel\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
metal devices are not available.
cuda devices are not available.
local-sync devices are available.
shark_tank local cache is located at C:\Users\pixel\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
local-task devices are available.
shark_tank local cache is located at C:\Users\pixel\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
diffusers\models\cross_attention.py:30: FutureWarning: Importing from cross_attention is deprecated. Please import from diffusers.models.attention_processor instead.
['AMD Ryzen 3 3200G with Radeon Vega Graphics => local-task://0', 'AMD Radeon RX 6700 XT => vulkan://0']
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
shark_tank local cache is located at C:\Users\pixel\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Found device AMD Radeon RX 6700 XT. Using target triple rdna2-unknown-windows.
Using tuned models for stabilityai/stable-diffusion-2-1-base(fp16) on device vulkan://00000000-0300-0000-0000-000000000000.
loading existing vmfb from: D:\Sharkai\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
Loading flatbuffer at D:\Sharkai\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb as a mmapped file
loading existing vmfb from: D:\Sharkai\euler_step_1_512_512_vulkan_fp16.vmfb
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
Loading flatbuffer at D:\Sharkai\euler_step_1_512_512_vulkan_fp16.vmfb as a mmapped file
use_tuned? sharkify: True
_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
Loading flatbuffer at D:\Sharkai\clip_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Loading Winograd config file from  C:\Users\pixel\.local/shark_tank/configs\unet_winograd_vulkan.json
100%|█████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 2.77kB/s]
Loading lowering config file from  C:\Users\pixel\.local/shark_tank/configs\unet_v2_1base_fp16_vulkan_rdna2_512x512.json
100%|██████████████████████████████████████████████████████████████████████████| 19.2k/19.2k [00:00<00:00, 143kB/s]
Applying tuned configs on unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan

Retrying with a different base model configuration
mat1 and mat2 shapes cannot be multiplied (128x768 and 1024x320)
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[4, 7, 512, 512] to have 4 channels, but got 7 channels instead
Retrying with a different base model configuration
Traceback (most recent call last):
  File "gradio\routes.py", line 439, in run_predict
  File "gradio\blocks.py", line 1384, in process_api
  File "gradio\blocks.py", line 1103, in call_function
  File "gradio\utils.py", line 343, in async_iteration
  File "gradio\utils.py", line 336, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 319, in run_sync_iterator_async
  File "gradio\utils.py", line 688, in gen_wrapper
  File "ui\txt2img_ui.py", line 186, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 134, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 235, in produce_img_latents
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 114, in load_unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 826, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 821, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 63, in check_compilation
SystemExit: Could not compile Unet. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues

**Comment by Sparko10** [comment]
I think I fixed it on my machine. If I remove all of the vmfb files and then run Shark with the flag "--no-use_tuned" then it seems to work.  Sometimes it will crash on the first run on a new model but then I run again and it seems to carry on and work.
