### ISSUE TITLE
Exception 0xC0000005 in iree-compiler.dll in version .750  (tuned)

### ISSUE THREAD

**Issue by one-lithe-rune** [nod-ai/SHARK#1483]
Getting the following compiling .vmfbs in the .750 .exe and a branch from recent commits.

```
To create a public link, set `share=True` in `launch()`.
Found device AMD Radeon VII. Using target triple rdna2-unknown-windows.
Using tuned models for CompVis/stable-diffusion-v1-4/fp16/vulkan://00000000-0c00-0000-0000-000000000000.
loading existing vmfb from: C:\develop\SHARK\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_VERBOSE does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_DEBUG does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
loading existing vmfb from: C:\develop\SHARK\euler_step_1_512_512_vulkan_fp16.vmfb
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_VERBOSE does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_DEBUG does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
use_tuned? sharkify: True
_1_77_512_512_fp16_tuned_stable-diffusion-v1-5
Diffusers' checkpoint will be identified here :  C:/develop/SHARK/models/vae/diffusers/vae-ft-mse-840000-ema-pruned
Loading diffusers' pipeline from original stable diffusion checkpoint
global_step key not found in model
Processing standalone Vae checkpoint
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_VERBOSE does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_DEBUG does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
Loading Winograd config file from  C:\Users\skapusniak\.local/shark_tank/configs\unet_winograd_vulkan.json
100%|█████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 3.24kB/s]
100%|█████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 3.96kB/s]
Loading lowering config file from  C:\Users\skapusniak\.local/shark_tank/configs\unet_v1_4_fp16_vulkan_rdna2.json
100%|██████████████████████████████████████████████████████████████████████████████| 24.6k/24.6k [00:00<00:00, 599kB/s]
100%|██████████████████████████████████████████████████████████████████████████████| 24.6k/24.6k [00:00<00:00, 572kB/s]
Applying tuned configs on unet_1_77_512_512_fp16_tuned_stable-diffusion-v1-5_vulkan
No vmfb found. Compiling and saving to C:\develop\SHARK\unet_1_77_512_512_fp16_tuned_stable-diffusion-v1-5_vulkan.vmfb
Configuring for device:vulkan://00000000-0c00-0000-0000-000000000000
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Traceback (most recent call last):
  File "C:\develop\shark\shark.venv\Lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\gradio\blocks.py", line 1069, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\gradio\blocks.py", line 892, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\gradio\utils.py", line 549, in async_iteration
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\web\ui\txt2img_ui.py", line 183, in txt2img_inf
    out_imgs = global_obj.get_sd_obj().generate_images(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 122, in generate_images
    latents = self.produce_img_latents(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 206, in produce_img_latents
    self.load_unet()
  File "C:\develop\SHARK\apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 104, in load_unet
    self.unet = self.sd_model.unet()
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\models\model_wrappers.py", line 656, in unet
    sys.exit(e)
  File "C:\develop\SHARK\apps\stable_diffusion\src\models\model_wrappers.py", line 627, in unet
    compiled_unet, unet_mlir = self.compile_unet_variants(model)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\models\model_wrappers.py", line 591, in compile_unet_variants
    return self.get_unet()
           ^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\models\model_wrappers.py", line 462, in get_unet
    shark_unet, unet_mlir = compile_through_fx(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\utils\utils.py", line 161, in compile_through_fx
    _compile_module(shark_module, extended_model_name, extra_args),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\utils\utils.py", line 71, in _compile_module
    path = shark_module.save_module(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark\shark_inference.py", line 188, in save_module
    return export_iree_module_to_vmfb(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark\iree_utils\compile_utils.py", line 352, in export_iree_module_to_vmfb
    flatbuffer_blob = compile_module_to_flatbuffer(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark\iree_utils\compile_utils.py", line 280, in compile_module_to_flatbuffer
    flatbuffer_blob = ireec.compile_str(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\tools\core.py", line 289, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\tools\binaries.py", line 196, in invoke_immediate
    raise CompilerToolError(process)
SystemExit: Error invoking IREE compiler tool iree-compile.exe
Diagnostics:
Please report issues to https://github.com/openxla/iree/issues and include the crash backtrace.
Exception Code: 0xC0000005
Exception Code: 0xC0000005
0x00007FF86AFCBA83, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x10FBA83 byte(s), ireeOptRunMain() + 0x101B843 byte(s)
0x00007FF86C05DFAF, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x218DFAF byte(s), ireeOptRunMain() + 0x20ADD6F byte(s)
0x00007FF86AB94D9F, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0xCC4D9F byte(s), ireeOptRunMain() + 0xBE4B5F byte(s)
0x00007FF86A058FAF, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x188FAF byte(s), ireeOptRunMain() + 0xA8D6F byte(s)
0x00007FF86BD6C7E8, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1E9C7E8 byte(s), ireeOptRunMain() + 0x1DBC5A8 byte(s)
0x00007FF86BD6DCB6, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1E9DCB6 byte(s), ireeOptRunMain() + 0x1DBDA76 byte(s)
0x00007FF86BD5C8B7, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1E8C8B7 byte(s), ireeOptRunMain() + 0x1DAC677 byte(s)
0x00007FF86BD5B122, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1E8B122 byte(s), ireeOptRunMain() + 0x1DAAEE2 byte(s)
0x00007FF86BD5CFD8, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1E8CFD8 byte(s), ireeOptRunMain() + 0x1DACD98 byte(s)
0x00007FF86BD5BD91, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1E8BD91 byte(s), ireeOptRunMain() + 0x1DABB51 byte(s)
0x00007FF86AB96A82, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0xCC6A82 byte(s), ireeOptRunMain() + 0xBE6842 byte(s)
0x00007FF86BDA85BA, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1ED85BA byte(s), ireeOptRunMain() + 0x1DF837A byte(s)
0x00007FF86BDAD640, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1EDD640 byte(s), ireeOptRunMain() + 0x1DFD400 byte(s)
0x00007FF86BDAEE01, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1EDEE01 byte(s), ireeOptRunMain() + 0x1DFEBC1 byte(s)
0x00007FF86BDA8A60, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1ED8A60 byte(s), ireeOptRunMain() + 0x1DF8820 byte(s)
0x00007FF86BDAE837, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1EDE837 byte(s), ireeOptRunMain() + 0x1DFE5F7 byte(s)
0x00007FF86BDA85A5, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1ED85A5 byte(s), ireeOptRunMain() + 0x1DF8365 byte(s)
0x00007FF86BDAD640, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1EDD640 byte(s), ireeOptRunMain() + 0x1DFD400 byte(s)
0x00007FF86BDAEE01, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1EDEE01 byte(s), ireeOptRunMain() + 0x1DFEBC1 byte(s)
0x00007FF86BDAA214, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1EDA214 byte(s), ireeOptRunMain() + 0x1DF9FD4 byte(s)
0x00007FF86BDA8547, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1ED8547 byte(s), ireeOptRunMain() + 0x1DF8307 byte(s)
0x00007FF86A9E3952, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0xB13952 byte(s), ireeOptRunMain() + 0xA33712 byte(s)
0x00007FF86BDA85BA, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1ED85BA byte(s), ireeOptRunMain() + 0x1DF837A byte(s)
0x00007FF86BDAD640, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1EDD640 byte(s), ireeOptRunMain() + 0x1DFD400 byte(s)
0x00007FF86BDAEE01, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1EDEE01 byte(s), ireeOptRunMain() + 0x1DFEBC1 byte(s)
0x00007FF86BDA8A60, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1ED8A60 byte(s), ireeOptRunMain() + 0x1DF8820 byte(s)
0x00007FF86BDAE837, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1EDE837 byte(s), ireeOptRunMain() + 0x1DFE5F7 byte(s)
0x00007FF86BDA85A5, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1ED85A5 byte(s), ireeOptRunMain() + 0x1DF8365 byte(s)
0x00007FF86BDAD640, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1EDD640 byte(s), ireeOptRunMain() + 0x1DFD400 byte(s)
0x00007FF86BDAEE01, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1EDEE01 byte(s), ireeOptRunMain() + 0x1DFEBC1 byte(s)
0x00007FF86BDAA214, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1EDA214 byte(s), ireeOptRunMain() + 0x1DF9FD4 byte(s)
0x00007FF86BDA8547, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1ED8547 byte(s), ireeOptRunMain() + 0x1DF8307 byte(s)
0x00007FF86A9E3626, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0xB13626 byte(s), ireeOptRunMain() + 0xA333E6 byte(s)
0x00007FF86BDA85BA, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1ED85BA byte(s), ireeOptRunMain() + 0x1DF837A byte(s)
0x00007FF86BDAD640, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1EDD640 byte(s), ireeOptRunMain() + 0x1DFD400 byte(s)
0x00007FF86BDAEE01, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1EDEE01 byte(s), ireeOptRunMain() + 0x1DFEBC1 byte(s)
0x00007FF86BDAA448, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1EDA448 byte(s), ireeOptRunMain() + 0x1DFA208 byte(s)
0x00007FF86BD42FCC, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x1E72FCC byte(s), ireeOptRunMain() + 0x1D92D8C byte(s)
0x00007FF86E1AD3D2, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x42DD3D2 byte(s), ireeCompilerRunLldMain() + 0x2119FC2 byte(s)
0x00007FF86E1AC9A8, C:\develop\shark\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF869ED0000) + 0x42DC9A8 byte(s), ireeCompilerRunLldMain() + 0x2119598 byte(s)
0x00007FF8D4A91BB2, C:\WINDOWS\System32\ucrtbase.dll(0x00007FF8D4A70000) + 0x21BB2 byte(s), _configthreadlocale() + 0x92 byte(s)
0x00007FF8D67F7614, C:\WINDOWS\System32\KERNEL32.DLL(0x00007FF8D67E0000) + 0x17614 byte(s), BaseThreadInitThunk() + 0x14 byte(s)
0x00007FF8D73E26A1, C:\WINDOWS\SYSTEM32\ntdll.dll(0x00007FF8D7390000) + 0x526A1 byte(s), RtlUserThreadStart() + 0x21 byte(s)
```

**Comment by one-lithe-rune** [comment]
I don't get this with `--no-use_tuned`, so changed the issue title.

**Comment by one-lithe-rune** [comment]
Closing, as fixed by https://github.com/nod-ai/SHARK/commit/1dbcc736ebb30425546ea3b616bbdba2644d5911
