### ISSUE TITLE
First start, VK_ERROR_OUT_OF_DEVICE_MEMORY; 

### ISSUE THREAD

**Issue by DanBrus** [nod-ai/SHARK#1601]
First start.

Log from console:

shark_tank local cache is located at C:\Users\Daniil\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
gradio temporary image cache located at D:\unstable\shark_tmp/gradio. You may change this by setting the GRADIO_TEMP_DIR environment variable.
No temporary images files to clear.
Matplotlib is building the font cache; this may take a moment.
vulkan devices are available.
metal devices are not available.
cuda devices are not available.
local-sync devices are available.
local-task devices are available.
diffusers\models\cross_attention.py:30: FutureWarning: Importing from cross_attention is deprecated. Please import from diffusers.models.attention_processor instead.
shark_tank local cache is located at C:\Users\Daniil\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
Found device AMD Radeon (TM) R9 380 Series. Using target triple rdna2-unknown-windows.
Using tuned models for stabilityai/stable-diffusion-2-1-base(fp16) on device vulkan://00000000-0100-0000-0000-000000000000.
Downloading (…)cheduler_config.json: 100%|████████████████████████████████████████████████████| 346/346 [00:00<?, ?B/s]
huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Daniil\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
No vmfb found. Compiling and saving to D:\unstable\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb
Configuring for device:vulkan://00000000-0100-0000-0000-000000000000
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\unstable\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb.
Loading flatbuffer at D:\unstable\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb as a mmapped file
No vmfb found. Compiling and saving to D:\unstable\euler_step_1_512_512_vulkan_fp16.vmfb
Configuring for device:vulkan://00000000-0100-0000-0000-000000000000
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\unstable\euler_step_1_512_512_vulkan_fp16.vmfb.
Loading flatbuffer at D:\unstable\euler_step_1_512_512_vulkan_fp16.vmfb as a mmapped file
use_tuned? sharkify: True
_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base
Downloading (…)tokenizer/vocab.json: 100%|████████████████████████████████████████| 1.06M/1.06M [00:00<00:00, 8.05MB/s]
Downloading (…)tokenizer/merges.txt: 100%|██████████████████████████████████████████| 525k/525k [00:00<00:00, 1.45MB/s]
Downloading (…)cial_tokens_map.json: 100%|████████████████████████████████████████████████████| 460/460 [00:00<?, ?B/s]
Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████████| 807/807 [00:00<00:00, 807kB/s]
Downloading (…)_encoder/config.json: 100%|████████████████████████████████████████████████████| 613/613 [00:00<?, ?B/s]
Downloading model.safetensors: 100%|██████████████████████████████████████████████| 1.36G/1.36G [01:58<00:00, 11.5MB/s]
No vmfb found. Compiling and saving to D:\unstable\clip_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb
Configuring for device:vulkan://00000000-0100-0000-0000-000000000000
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\unstable\clip_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb.
Loading flatbuffer at D:\unstable\clip_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Downloading (…)ain/unet/config.json: 100%|████████████████████████████████████████████████████| 911/911 [00:00<?, ?B/s]
Downloading (…)ch_model.safetensors: 100%|████████████████████████████████████████| 3.46G/3.46G [05:00<00:00, 11.5MB/s]
Loading Winograd config file from  C:\Users\Daniil\.local/shark_tank/configs\unet_winograd_vulkan.json
100%|███████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 158B/s]
Loading lowering config file from  C:\Users\Daniil\.local/shark_tank/configs\unet_v2_1base_fp16_vulkan_rdna2_512x512.json
100%|█████████████████████████████████████████████████████████████████████████████| 19.2k/19.2k [00:00<00:00, 29.3kB/s]
Applying tuned configs on unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan
No vmfb found. Compiling and saving to D:\unstable\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb
Configuring for device:vulkan://00000000-0100-0000-0000-000000000000
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\unstable\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb.
Loading flatbuffer at D:\unstable\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\vma_allocator.cc:692: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.allocator.allocate; while calling import;
[ 1]   native hal.allocator.allocate:0 -
[ 0] bytecode module@1:28452 -
Retrying with a different base model configuration
Loading flatbuffer at D:\unstable\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\vma_allocator.cc:692: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.allocator.allocate; while calling import;
[ 1]   native hal.allocator.allocate:0 -
[ 0] bytecode module@1:28452 -
Retrying with a different base model configuration
Loading flatbuffer at D:\unstable\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\vma_allocator.cc:692: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.allocator.allocate; while calling import;
[ 1]   native hal.allocator.allocate:0 -
[ 0] bytecode module@1:28452 -
Retrying with a different base model configuration
Loading flatbuffer at D:\unstable\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\vma_allocator.cc:692: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.allocator.allocate; while calling import;
[ 1]   native hal.allocator.allocate:0 -
[ 0] bytecode module@1:28452 -
Retrying with a different base model configuration
Loading flatbuffer at D:\unstable\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\vma_allocator.cc:692: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.allocator.allocate; while calling import;
[ 1]   native hal.allocator.allocate:0 -
[ 0] bytecode module@1:28452 -
Retrying with a different base model configuration
Traceback (most recent call last):
  File "gradio\routes.py", line 437, in run_predict
  File "gradio\blocks.py", line 1346, in process_api
  File "gradio\blocks.py", line 1090, in call_function
  File "gradio\utils.py", line 341, in async_iteration
  File "gradio\utils.py", line 334, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 317, in run_sync_iterator_async
  File "ui\txt2img_ui.py", line 185, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 126, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 226, in produce_img_latents
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 105, in load_unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 673, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 668, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 62, in check_compilation
SystemExit: Could not compile Unet. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues
Found device AMD Radeon (TM) R9 380 Series. Using target triple rdna2-unknown-windows.
Tuned models are currently not supported for this setting.
No vmfb found. Compiling and saving to D:\unstable\euler_scale_model_input_1_384_384_vulkan_fp16.vmfb
Configuring for device:vulkan://00000000-0100-0000-0000-000000000000
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\unstable\euler_scale_model_input_1_384_384_vulkan_fp16.vmfb.
Loading flatbuffer at D:\unstable\euler_scale_model_input_1_384_384_vulkan_fp16.vmfb as a mmapped file
No vmfb found. Compiling and saving to D:\unstable\euler_step_1_384_384_vulkan_fp16.vmfb
Configuring for device:vulkan://00000000-0100-0000-0000-000000000000
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\unstable\euler_step_1_384_384_vulkan_fp16.vmfb.
Loading flatbuffer at D:\unstable\euler_step_1_384_384_vulkan_fp16.vmfb as a mmapped file
use_tuned? sharkify: False
_1_64_384_384_fp16_stable-diffusion-2-1-base
No vmfb found. Compiling and saving to D:\unstable\clip_1_64_384_384_fp16_stable-diffusion-2-1-base_vulkan.vmfb
Configuring for device:vulkan://00000000-0100-0000-0000-000000000000
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\unstable\clip_1_64_384_384_fp16_stable-diffusion-2-1-base_vulkan.vmfb.
Loading flatbuffer at D:\unstable\clip_1_64_384_384_fp16_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
No vmfb found. Compiling and saving to D:\unstable\unet_1_64_384_384_fp16_stable-diffusion-2-1-base_vulkan.vmfb
Configuring for device:vulkan://00000000-0100-0000-0000-000000000000
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\unstable\unet_1_64_384_384_fp16_stable-diffusion-2-1-base_vulkan.vmfb.
Loading flatbuffer at D:\unstable\unet_1_64_384_384_fp16_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\vma_allocator.cc:692: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.allocator.allocate; while calling import;
[ 1]   native hal.allocator.allocate:0 -
[ 0] bytecode module@1:29152 -
Retrying with a different base model configuration
Loading flatbuffer at D:\unstable\unet_1_64_384_384_fp16_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\vma_allocator.cc:692: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.allocator.allocate; while calling import;
[ 1]   native hal.allocator.allocate:0 -
[ 0] bytecode module@1:29152 -
Retrying with a different base model configuration
Loading flatbuffer at D:\unstable\unet_1_64_384_384_fp16_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\vma_allocator.cc:692: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.allocator.allocate; while calling import;
[ 1]   native hal.allocator.allocate:0 -
[ 0] bytecode module@1:29152 -
Retrying with a different base model configuration
Loading flatbuffer at D:\unstable\unet_1_64_384_384_fp16_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\vma_allocator.cc:692: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.allocator.allocate; while calling import;
[ 1]   native hal.allocator.allocate:0 -
[ 0] bytecode module@1:29152 -
Retrying with a different base model configuration
Loading flatbuffer at D:\unstable\unet_1_64_384_384_fp16_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\vma_allocator.cc:692: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.allocator.allocate; while calling import;
[ 1]   native hal.allocator.allocate:0 -
[ 0] bytecode module@1:29152 -
Retrying with a different base model configuration
Traceback (most recent call last):
  File "gradio\routes.py", line 437, in run_predict
  File "gradio\blocks.py", line 1346, in process_api
  File "gradio\blocks.py", line 1090, in call_function
  File "gradio\utils.py", line 341, in async_iteration
  File "gradio\utils.py", line 334, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 317, in run_sync_iterator_async
  File "ui\txt2img_ui.py", line 185, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 126, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 226, in produce_img_latents
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 105, in load_unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 673, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 668, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 62, in check_compilation
SystemExit: Could not compile Unet. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues

**Comment by NeedsMoar** [comment]
Your GPU only has 4GB of memory, so there's a good chance that you're out of memory...

**Comment by DanBrus** [comment]
@NeedsMoar can i find somewhere a recommend memory size for different sizes of pictures or different models?

**Comment by NeedsMoar** [comment]
I'd say 6GB depending on your display size(s) and how much vram is being eaten by other things.  In my case with a 2560x2880 LG display running at 10bpc 4:4:4 RGB, a 4k TV running at 10bpc 4:2:2, and Firefox open, 2.6GB of vram is being used.   On a 4GB card and a reasonably modern 4k display you've probably taken up too much memory to run it in low vram mode.  At best you might try lowering your display resolution to 1080p temporarily and closing all browers and open windows to see if it'll start going then.
