### ISSUE TITLE
SHARK can't be offline, if you change models, it shuts down in 120 seconds. It is also corresponding with google for some reason.

### ISSUE THREAD

**Issue by AmiiiiKo** [nod-ai/SHARK#1603]
1. There's traffic going to google with every image generation, are you able to enlightenment us as to what this is?
I have a range of IP's that have been blocked by the firewall, each and every one of them are google. I have fonts.google.com blocked in my browser, so it is not a request from there.

3. When I change model to Analog Diffusion SHARK sends data to google, well it attempts to and then fails 120 seconds later and crashes. It is completely installed and I have been using it.

This is the error I get:

> Traceback (most recent call last):
>   File "gradio\routes.py", line 437, in run_predict
>   File "gradio\blocks.py", line 1346, in process_api
>   File "gradio\blocks.py", line 1090, in call_function
>   File "gradio\utils.py", line 341, in async_iteration
>   File "gradio\utils.py", line 334, in __anext__
>   File "anyio\to_thread.py", line 33, in run_sync
>   File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
>   File "anyio\_backends\_asyncio.py", line 807, in run
>   File "gradio\utils.py", line 317, in run_sync_iterator_async
>   File "ui\txt2img_ui.py", line 185, in txt2img_inf
>   File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 126, in generate_images
>   File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 226, in produce_img_latents
>   File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 105, in load_unet
>   File "apps\stable_diffusion\src\models\model_wrappers.py", line 673, in unet
>   File "apps\stable_diffusion\src\models\model_wrappers.py", line 644, in unet
>   File "apps\stable_diffusion\src\models\model_wrappers.py", line 608, in compile_unet_variants
>   File "apps\stable_diffusion\src\models\model_wrappers.py", line 472, in get_unet
>   File "apps\stable_diffusion\src\utils\utils.py", line 156, in compile_through_fx
>   File "apps\stable_diffusion\src\utils\sd_annotation.py", line 238, in sd_model_annotation
>   File "apps\stable_diffusion\src\utils\sd_annotation.py", line 77, in load_winograd_configs
>   File "shark\shark_downloader.py", line 48, in download_public_file
>   File "google\api_core\page_iterator.py", line 208, in _items_iter
>   File "google\api_core\page_iterator.py", line 244, in _page_iter
>   File "google\api_core\page_iterator.py", line 373, in _next_page
>   File "google\api_core\page_iterator.py", line 432, in _get_next_page_response
>   File "google\cloud\storage\_http.py", line 72, in api_request
>   File "google\api_core\retry.py", line 349, in retry_wrapped_func
>   File "google\api_core\retry.py", line 207, in retry_target
> SystemExit: Deadline of 120.0s exceeded while calling target function, last exception: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /storage/v1/b/shark_tank/o?projection=noAcl&prefix=sd_tuned%2Fconfigs&prettyPrint=false (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xREDACTED>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))

I am not comfortable giving it access to the internet, I can use SHARK with other models, but not Analog Diffusion, which is fully installed and was operational.

**Comment by monorimet** [comment]
Hi, 
The attempt to read from `gs://shark_tank/sd_tuned_configs` here is to get a tuning configuration for the base UNet model.

To disable this feature, please run with the `--no-use_tuned` flag or [download the files manually](https://console.cloud.google.com/storage/browser/shark_tank/sd_tuned_configs)

**Comment by NeedsMoar** [comment]
There's an upstream gradio thing that the anything1111 UI hit where some version of it began calling out to a google analytics API to download the roboto webfont and broke offline for them, so that might be worth keeping an eye on too.

**Comment by monorimet** [comment]
Ah, thanks, that would explain the traffic to `fonts.google.com`. Perhaps if nothing else there is a workaround for the gradio requirements.

**Comment by NeedsMoar** [comment]
#https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11364
