### ISSUE TITLE
works with default models but when i dump the model into the model folder that i want to use and i am getting why is it trying to goto face hugger i have already downloaded the model 

### ISSUE THREAD

**Issue by uninstaller81** [nod-ai/SHARK#1662]
works with default models but when i dump the model into the model folder that i want to use and i am getting why is it trying to goto face hugger i have already downloaded the model 
Loading flatbuffer at C:\ai\New folder\euler_step_1_512_512_vulkan_fp16.vmfb as a mmapped file
use_tuned? sharkify: False
_1_64_512_512_fp16_realisticVisionV40_v40VAE
Checkpoint already loaded at :  C:/ai/New folder/models/diffusers/realisticVisionV40_v40VAE
Error no file named config.json found in directory C:/ai/New folder/models/diffusers/realisticVisionV40_v40VAE.
Retrying with a different base model configuration
Error no file named config.json found in directory C:/ai/New folder/models/diffusers/realisticVisionV40_v40VAE.
Retrying with a different base model configuration
Error no file named config.json found in directory C:/ai/New folder/models/diffusers/realisticVisionV40_v40VAE.
Retrying with a different base model configuration
Error no file named config.json found in directory C:/ai/New folder/models/diffusers/realisticVisionV40_v40VAE.
Retrying with a different base model configuration
Error no file named config.json found in directory C:/ai/New folder/models/diffusers/realisticVisionV40_v40VAE.
Retrying with a different base model configuration
Traceback (most recent call last):
  File "gradio\routes.py", line 439, in run_predict
  File "gradio\blocks.py", line 1384, in process_api
  File "gradio\blocks.py", line 1103, in call_function
  File "gradio\utils.py", line 343, in async_iteration
  File "gradio\utils.py", line 336, in _anext_
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 319, in run_sync_iterator_async
  File "gradio\utils.py", line 688, in gen_wrapper
  File "ui\txt2img_ui.py", line 155, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 389, in from_pretrained
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 51, in _init_
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 82, in _init_
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 114, in load_unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 826, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 821, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 63, in check_compilation
SystemExit: Could not compile Unet. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues
Found device AMD Radeon RX 6700 XT. Using target triple rdna2-unknown-windows.
Tuned models are currently not supported for this setting.
Traceback (most recent call last):
  File "huggingface_hub\utils\_errors.py", line 261, in hf_raise_for_status
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/4201/resolve/main/scheduler/scheduler_config.json

The above exception was the direct cause of the following exception:

**Comment by NeedsMoar** [comment]
I didn't have this problem with that model (downloaded as pruned fp16 safetensors from civitAI.  It refused to tune without changing the VAE, but I'm not convinced this isn't some issue with Shark itself (i.e. the matrix mismatch reported by the first run causes it to fail to tune, but the second time you access the model in a later session it pulls the .vmfb files it generated the first time and runs those) .

A 401 error indicates that you're not logged in to huggingface, but that wouldn't have mattered since there's no repo at that address and I should have received a file not found error if mine was trying to download from there too, I'd assume.  I'd suggest trying a .safetensors version if you had just installed a model tree from GIT.
