### ISSUE TITLE
Stencils no longer work

### ISSUE THREAD

**Issue by Arcadia245** [nod-ai/SHARK#1774]
When trying to use canny, openpose or scribble I get this error:

Traceback (most recent call last):
  File "gradio\routes.py", line 442, in run_predict
  File "gradio\blocks.py", line 1392, in process_api
  File "gradio\blocks.py", line 1111, in call_function
  File "gradio\utils.py", line 346, in async_iteration
  File "gradio\utils.py", line 339, in anext
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio_backends_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio_backends_asyncio.py", line 807, in run
  File "gradio\utils.py", line 322, in run_sync_iterator_async
  File "gradio\utils.py", line 691, in gen_wrapper
  File "ui\img2img_ui.py", line 241, in img2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_stencil.py", line 267, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_stencil.py", line 138, in produce_stencil_latents
  File "shark\shark_inference.py", line 142, in call
    return self.shark_runner.run(function_name, inputs, send_to_host)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "shark\shark_runner.py", line 101, in run
    return get_results(
           ^^^^^^^^^^^^
  File "shark\iree_utils\compile_utils.py", line 504, in get_results
    result = compiled_vm[function_name](*device_inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "iree\runtime\function.py", line 137, in call
  File "iree\runtime\function.py", line 162, in _invoke
ValueError: Error invoking function: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\modules\hal\utils\buffer_diagnostics.c:225: INVALID_ARGUMENT; input 2 shape dimension 1 mismatch; expected 64 but have 512; expected shape 2x64x768, actual shape 2x512x768; while invoking native function hal.buffer_view.assert; while calling import;
[ 1]   native hal.buffer_view.assert:0 -
[ 0] bytecode module@0:9168 -

**Comment by Arcadia245** [comment]
I was finally able to test it with shark 901, it still does not work. There is a different error now. Here it is:

Traceback (most recent call last):
  File "gradio\routes.py", line 488, in run_predict
  File "gradio\blocks.py", line 1431, in process_api
  File "gradio\blocks.py", line 1123, in call_function
  File "gradio\utils.py", line 349, in async_iteration
  File "gradio\utils.py", line 342, in anext
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio_backends_asyncio.py", line 2101, in run_sync_in_worker_thread
  File "anyio_backends_asyncio.py", line 828, in run
  File "gradio\utils.py", line 325, in run_sync_iterator_async
  File "gradio\utils.py", line 694, in gen_wrapper
  File "ui\img2img_ui.py", line 241, in img2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_stencil.py", line 295, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_stencil.py", line 152, in produce_stencil_latents
AttributeError: 'Tensor' object has no attribute 'shapes'
