### ISSUE TITLE
App startup error when running with ROCm/HIP 5.5 installed on Windows

### ISSUE THREAD

**Issue by one-lithe-rune** [nod-ai/SHARK#1789]
Getting the following error at 16160d9a7d38b75fff725fec86039074718c5d8a now I have ROCm HIP SDK installed on Windows:

```
(shark.venv) PS C:\develop\SHARK> shark-run
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
shark_tank local cache is located at C:\Users\skapusniak\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
gradio temporary image cache located at C:\develop\SHARK\shark_tmp/gradio. You may change this by setting the GRADIO_TEMP_DIR environment variable.
No temporary images files to clear.
vulkan devices are available.
metal devices are not available.
cuda devices are not available.
local-sync devices are available.
local-task devices are available.
No ROCm runtime is found, using ROCM_HOME='C:\Program Files\AMD\ROCm\5.5'
Traceback (most recent call last):
  File "C:\develop\SHARK\apps\stable_diffusion\web\index.py", line 94, in <module>
    from apps.stable_diffusion.web.ui.utils import create_custom_models_folders
  File "C:\develop\SHARK\apps\stable_diffusion\web\ui\__init__.py", line 81, in <module>
    from apps.stable_diffusion.web.ui.generate_config import model_config_web
  File "C:\develop\SHARK\apps\stable_diffusion\web\ui\generate_config.py", line 4, in <module>
    from apps.language_models.src.model_wrappers.vicuna_model import CombinedModel
  File "C:\develop\SHARK\apps\language_models\src\model_wrappers\vicuna_model.py", line 4, in <module>
    from brevitas_examples.llm.llm_quant.quantize import quantize_model
  File "C:\develop\shark\shark.venv\Lib\site-packages\brevitas_examples\llm\llm_quant\quantize.py", line 8, in <module>
    from brevitas import nn as qnn
  File "C:\develop\shark\shark.venv\Lib\site-packages\brevitas\__init__.py", line 14, in <module>
    from torch.utils import cpp_extension
  File "C:\develop\shark\shark.venv\Lib\site-packages\torch\utils\cpp_extension.py", line 203, in <module>
    HIP_HOME = _join_rocm_home('hip') if ROCM_HOME else None
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\torch\utils\cpp_extension.py", line 156, in _join_rocm_home
    raise OSError('Building PyTorch extensions using '
OSError: Building PyTorch extensions using ROCm and Windows is not supported.

**Comment by njsharpe** [comment]
ROCm versions of PyTorch are not yet available on Windows, despite HIP being made available for v5.5

See:
[https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2272](MIOpen Pipeline PR)
[https://github.com/pytorch/pytorch/issues/106529](PyTorch ROCm+Windows Implementation Issue)

**Comment by InCrIpTiOn** [comment]
@monorimet Can I ask how this is possible when libraries like MIOpen and PyTorch are updated for hip on windows? If you do have a working build, it would be useful to help get their releases out

**Comment by one-lithe-rune** [comment]
At https://github.com/nod-ai/SHARK/commit/671881cf87627e7aae880a2a1d1043fa52bdbe58 Shark Studio now starts fine. However, trying to use a rocm device for txt2img gives me errors, I'll close this issue and make a new one for that.
