### ISSUE TITLE
Torch IR Pipeline Failure on Scaled Dot Product MHA

### ISSUE THREAD

**Issue by njsharpe** [nod-ai/SHARK#1813]
Probably a result of some experimental stuff in SRT, but posting the issue here as unsure. Context is that, a lot of LoRAs I use had worked previously before I force rebuilt my venv. Now, for many LoRAs, I encounter the following stacktrace:

```
Traceback (most recent call last):
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\web\ui\txt2img_ui.py", line 195, in txt2img_inf
    out_imgs = global_obj.get_sd_obj().generate_images(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 134, in generate_images
    latents = self.produce_img_latents(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 237, in produce_img_latents
    self.load_unet_512()
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 132, in load_unet_512
    self.unet_512 = self.sd_model.unet(use_large=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\src\models\model_wrappers.py", line 855, in unet
    sys.exit(e)
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\src\models\model_wrappers.py", line 818, in unet
    compiled_unet, unet_mlir = self.compile_unet_variants(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\src\models\model_wrappers.py", line 778, in compile_unet_variants
    return self.get_unet(use_large=use_large)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\src\models\model_wrappers.py", line 619, in get_unet
    shark_unet, unet_mlir = compile_through_fx(
                            ^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\src\utils\utils.py", line 150, in compile_through_fx
    ) = import_with_fx(
        ^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark\shark_importer.py", line 683, in import_with_fx
    mlir_module, func_name = mlir_importer.import_mlir()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark\shark_importer.py", line 133, in import_mlir
    self._torch_mlir(is_dynamic, tracing_required, mlir_type),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark\shark_importer.py", line 87, in _torch_mlir
    return get_torch_mlir_module(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark\torch_mlir_utils.py", line 77, in get_torch_mlir_module
    mlir_module = torch_mlir.compile(
                  ^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\torch_mlir\__init__.py", line 463, in compile
    run_pipeline_with_repro_report(
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\torch_mlir\compiler_utils.py", line 69, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
SystemExit: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:


python exception: Failure while executing pass pipeline:
error: "aten::_scaled_dot_product_flash_attention"("<eval_with_key>.34 from D:\\Stable\\stable-diffusion-shark\\shark.venv\\Lib\\site-packages\\torch\\fx\\experimental\\proxy_tensor.py:489 in wrapped":176:42): unsupported by backend contract: Unimplemented operator 'aten._scaled_dot_product_flash_attention'
note: "aten::_scaled_dot_product_flash_attention"("<eval_with_key>.34 from D:\\Stable\\stable-diffusion-shark\\shark.venv\\Lib\\site-packages\\torch\\fx\\experimental\\proxy_tensor.py:489 in wrapped":176:42): see current operation: %959:9 = "torch.operator"(%954, %956, %958, %0, %2, %2, %3) {name = "aten._scaled_dot_product_flash_attention"} : (!torch.tensor<[2,8,4096,40],unk>, !torch.tensor<[2,8,4096,40],unk>, !torch.tensor<[2,8,4096,40],unk>, !torch.float, !torch.bool, !torch.bool, !torch.none) -> (!torch.tensor, !torch.tensor, !torch.tensor, !torch.tensor, !torch.int, !torch.int, !torch.tensor, !torch.tensor, !torch.tensor)

For Torch-MLIR developers, the error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='builtin.module(torchscript-module-to-torch-backend-pipeline{backend-legal-ops=aten.flatten.using_ints extra-library=})' .\_lambda.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
```

Current versions for related packages:
|Package|Version|
| --- | --- |
|iree-compiler|20230901.508|
|iree-runtime|20230901.508|
|torch|2.1.0.dev20230831+cpu|
|torch-mlir|20230901.948|
|torchvision|0.16.0.dev20230901+cpu|

EDIT: To note, the selected device is `vulkan://0`. No additional packages have been installed and I tried a `--clear_all` run into generate before reporting the issue.

**Comment by njsharpe** [comment]
I have some updated results from additional testing (various combinations of LoRA + Model + VAE) to confirm that this issue does not stem from LoRAs only. Completely removing all of the files in `/diffusers/` for my VAEs and Models will cause another variant of this message to appear. I could not get any models working, including the built-in models like anything-v3.0.

```
Loading diffusers' pipeline from original stable diffusion checkpoint
Processing standalone Vae checkpoint
mat1 and mat2 shapes cannot be multiplied (128x1024 and 768x320)
Retrying with a different base model configuration
Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:


python exception: Failure while executing pass pipeline:
error: "aten::_scaled_dot_product_flash_attention"("<eval_with_key>.9 from D:\\Stable\\stable-diffusion-shark\\shark.venv\\Lib\\site-packages\\torch\\fx\\experimental\\proxy_tensor.py:489 in wrapped":176:42): unsupported by backend contract: Unimplemented operator 'aten._scaled_dot_product_flash_attention'
note: "aten::_scaled_dot_product_flash_attention"("<eval_with_key>.9 from D:\\Stable\\stable-diffusion-shark\\shark.venv\\Lib\\site-packages\\torch\\fx\\experimental\\proxy_tensor.py:489 in wrapped":176:42): see current operation: %959:9 = "torch.operator"(%954, %956, %958, %0, %2, %2, %3) {name = "aten._scaled_dot_product_flash_attention"} : (!torch.tensor<[2,8,4096,40],unk>, !torch.tensor<[2,8,4096,40],unk>, !torch.tensor<[2,8,4096,40],unk>, !torch.float, !torch.bool, !torch.bool, !torch.none) -> (!torch.tensor, !torch.tensor, !torch.tensor, !torch.tensor, !torch.int, !torch.int, !torch.tensor, !torch.tensor, !torch.tensor)

For Torch-MLIR developers, the error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='builtin.module(torchscript-module-to-torch-backend-pipeline{backend-legal-ops=aten.flatten.using_ints extra-library=})' .\_lambda.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.

Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[4, 7, 512, 512] to have 4 channels, but got 7 channels instead
Retrying with a different base model configuration
Traceback (most recent call last):
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\shark.venv\Lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\web\ui\txt2img_ui.py", line 163, in txt2img_inf
    Text2ImagePipeline.from_pretrained(
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 389, in from_pretrained
    return cls(scheduler, sd_model, import_mlir, use_lora, ondemand)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 51, in __init__
    super().__init__(scheduler, sd_model, import_mlir, use_lora, ondemand)
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 82, in __init__
    self.load_unet()
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 114, in load_unet
    self.unet = self.sd_model.unet()
                ^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\src\models\model_wrappers.py", line 855, in unet
    sys.exit(e)
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\src\models\model_wrappers.py", line 850, in unet
    check_compilation(compiled_unet, "Unet")
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\src\models\model_wrappers.py", line 63, in check_compilation
    raise Exception(
SystemExit: Could not compile Unet. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues
```

No packages have been updated since the previous post.
