### ISSUE TITLE
Stencils no longer work 

### ISSUE THREAD

**Issue by Arcadia245** [nod-ai/SHARK#1818]
Since hires fix was added to shark, stencils stop working again. Here is the error I get:

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "gradio\routes.py", line 523, in run_predict
  File "gradio\blocks.py", line 1437, in process_api
  File "gradio\blocks.py", line 1123, in call_function
  File "gradio\utils.py", line 508, in async_iteration
  File "gradio\utils.py", line 501, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 484, in run_sync_iterator_async
  File "gradio\utils.py", line 853, in gen_wrapper
  File "ui\img2img_ui.py", line 243, in img2img_inf
TypeError: StencilPipeline.generate_images() got an unexpected keyword argument 'resample_type'

**Comment by Arcadia245** [comment]
I want to make mention, Stencils were fixed in build 907, but bugged again in build 909 when Hires fix was introduced.

**Comment by monorimet** [comment]
Thanks. I've added a fix to this PR: https://github.com/nod-ai/SHARK/pull/1828

**Comment by Arcadia245** [comment]
> Thanks. I've added a fix to this PR: #1828

I can confirm that this issue has been fixed. Closing the thread!
