### ISSUE TITLE
SD/rocm: Error invoking IREE compiler/LLVM ERROR: Cannot select: 0x26a48d0b0b8

### ISSUE THREAD

**Issue by one-lithe-rune** [nod-ai/SHARK#1852]
At 9459454, webui -- Adrenalin 23.9.3, RX 7900 XTX, SD 2.1 base, txt2img, rocm 5.5.1 windows

```
(shark.venv) PS C:\develop\SHARK> shark-run-64
9459454 (HEAD -> main, origin/main, origin/HEAD) remove use of vulkaninfo
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
shark_tank local cache is located at C:\Users\skapusniak\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
gradio temporary image cache located at C:\develop\SHARK\shark_tmp/gradio. You may change this by setting the GRADIO_TEMP_DIR environment variable.
No temporary images files to clear.
vulkan devices are available.
metal devices are not available.
cuda devices are not available.
rocm devices are available.
local-sync devices are available.
local-task devices are available.
C:\develop\SHARK\shark.venv\Lib\site-packages\gradio\components\dropdown.py:238: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include:  or set allow_custom_value=True.
  warnings.warn(
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
Tuned models are currently not supported for this setting.
Checking for updates from gs://shark_tank/nightly
Model artifacts for euler_scale_model_input_fp16 found at C:\Users\skapusniak\.local/shark_tank/...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 4.96kB/s]
Local and upstream hashes match. Using cached model artifacts.
Verifying that model artifacts were downloaded successfully to C:\Users\skapusniak\.local/shark_tank/euler_scale_model_input_fp16_torch\euler_scale_model_input_fp16_torch.mlir...
loading existing vmfb from: C:\develop\SHARK\euler_scale_model_input_fp16.vmfb
Loading module C:\develop\SHARK\euler_scale_model_input_fp16.vmfb...
Checking for updates from gs://shark_tank/nightly
Model artifacts for euler_step_fp16 found at C:\Users\skapusniak\.local/shark_tank/...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 4.51kB/s]
Local and upstream hashes match. Using cached model artifacts.
Verifying that model artifacts were downloaded successfully to C:\Users\skapusniak\.local/shark_tank/euler_step_fp16_torch\euler_step_fp16_torch.mlir...
loading existing vmfb from: C:\develop\SHARK\euler_step_fp16.vmfb
Loading module C:\develop\SHARK\euler_step_fp16.vmfb...
use_tuned? sharkify: False
_1_64_512_512_fp16_stable-diffusion-2-1-base
Found a ROCm installation at C:\Program Files\AMD\ROCm\5.5\.
Found rocm arch gfx1100...
['--iree-rocm-target-chip=gfx1100', '--iree-rocm-link-bc=true', '--iree-rocm-bc-dir=C:\\Program Files\\AMD\\ROCm\\5.5\\amdgcn\\bitcode']
Checking for updates from gs://shark_tank/nightly
Model artifacts for clip_1_64_512_512_fp16_stable-diffusion-2-1-base_vulkan found at C:\Users\skapusniak\.local/shark_tank/...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 4.67kB/s]
Local and upstream hashes match. Using cached model artifacts.
Verifying that model artifacts were downloaded successfully to C:\Users\skapusniak\.local/shark_tank/clip_1_64_512_512_fp16_stable-diffusion-2-1-base_vulkan\clip_1_64_512_512_fp16_stable-diffusion-2-1-base_vulkan_torch.mlir...
No vmfb found. Compiling and saving to C:\develop\SHARK\clip_1_64_512_512_fp16_stable-diffusion-2-1-base_vulkan.vmfb
Configuring for device:rocm://0
Specific device selection only supported for vulkan now.Proceeding with rocm://0 as device.
Error invoking IREE compiler tool iree-compile.exe
Diagnostics:
<eval_with_key>.32:67:15: error: unregistered operation 'arith.maxf' found in dialect ('arith') that does not allow unknown operations
<eval_with_key>.32:67:15: note: in bytecode version 1 produced by: MLIR17.0.0git


Invoked with:
 iree-compile.exe C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\tools\..\_mlir_libs\iree-compile.exe - --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=rocm --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-rocm-target-chip=gfx1100 --iree-rocm-link-bc=true --iree-rocm-bc-dir=C:\Program Files\AMD\ROCm\5.5\amdgcn\bitcode --iree-stream-resource-max-allocation-size=4294967295 --iree-vm-bytecode-module-strip-source-map=true --iree-util-zero-fill-elided-attrs --iree-opt-strip-assertions=true --verify=false --iree-rocm-target-chip=gfx1100 --iree-rocm-link-bc=true --iree-rocm-bc-dir=C:\Program Files\AMD\ROCm\5.5\amdgcn\bitcode --iree-preprocessing-pass-pipeline=builtin.module(func.func(iree-preprocessing-pad-linalg-ops{pad-size=16}))

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.

download pipeline failed, falling back to import_mlir
['--iree-rocm-target-chip=gfx1100', '--iree-rocm-link-bc=true', '--iree-rocm-bc-dir=C:\\Program Files\\AMD\\ROCm\\5.5\\amdgcn\\bitcode']
No vmfb found. Compiling and saving to C:\develop\SHARK\clip_1_64_512_512_fp16_stable-diffusion-2-1-base_rocm.vmfb
Configuring for device:rocm://0
Specific device selection only supported for vulkan now.Proceeding with rocm://0 as device.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\skapusniak\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\skapusniak\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\skapusniak\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\skapusniak\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\skapusniak\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\skapusniak\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\skapusniak\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\gradio\queueing.py", line 431, in process_events
    response = await self.call_prediction(awake_events, batch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\gradio\blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\gradio\utils.py", line 503, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\gradio\utils.py", line 496, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\gradio\utils.py", line 479, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\gradio\utils.py", line 629, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\develop\SHARK\apps\stable_diffusion\web\ui\txt2img_ui.py", line 195, in txt2img_inf
    out_imgs = global_obj.get_sd_obj().generate_images(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 123, in generate_images
    text_embeddings = self.encode_prompts_weight(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 432, in encode_prompts_weight
    self.load_clip()
  File "C:\develop\SHARK\apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 103, in load_clip
    self.text_encoder = self.sd_model.clip()
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\models\model_wrappers.py", line 806, in clip
    sys.exit(e)
  File "C:\develop\SHARK\apps\stable_diffusion\src\models\model_wrappers.py", line 799, in clip
    compiled_clip, clip_mlir = self.get_clip()
                               ^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\models\model_wrappers.py", line 719, in get_clip
    shark_clip, clip_mlir = compile_through_fx(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\utils\utils.py", line 178, in compile_through_fx
    _compile_module(shark_module, extended_model_name, extra_args),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\utils\utils.py", line 80, in _compile_module
    path = shark_module.save_module(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark\shark_inference.py", line 198, in save_module
    return export_iree_module_to_vmfb(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark\iree_utils\compile_utils.py", line 492, in export_iree_module_to_vmfb
    flatbuffer_blob = compile_module_to_flatbuffer(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark\iree_utils\compile_utils.py", line 318, in compile_module_to_flatbuffer
    flatbuffer_blob = ireec.compile_str(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\tools\core.py", line 300, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\tools\binaries.py", line 199, in invoke_immediate
    raise CompilerToolError(process)
SystemExit: Error invoking IREE compiler tool iree-compile.exe
Diagnostics:
LLVM ERROR: Cannot select: 0x26a48d0b0b8: f32 = fmaximum # D:1 0x26a48d0dd58, 0x26a48d0ddc8
  0x26a48d0dd58: f32 = extract_vector_elt # D:1 0x26a48d0b5f8, Constant:i32<0>
    0x26a48d0b5f8: v2f32 = bitcast # D:1 0x26a48d138c8
      0x26a48d138c8: v2i32,ch = load<(load (s64) from %ir.24, align 4)> # D:1 0x26a93a90168, 0x26a48d0e538, undef:i64
        0x26a48d0e538: i64 = add # D:1 0x26a48d0e4c8, Constant:i64<1572864>
          0x26a48d0e4c8: i64 = add # D:1 0x26a48d0afd8, 0x26a48d13d98
            0x26a48d0afd8: i64 = bitcast 0x26a48d0ac58
              0x26a48d0ac58: v2i32,ch = load<(dereferenceable invariant load (s64), align 16, addrspace 4)> 0x26a93a90168, 0x26a48d0ab78, undef:i64
                0x26a48d0ab78: i64,ch = CopyFromReg 0x26a93a90168, Register:i64 %1
                  0x26a48d0abe8: i64 = Register %1
                0x26a48d0aa98: i64 = undef
            0x26a48d13d98: i64 = bitcast # D:1 0x26a48d13d28
              0x26a48d13d28: v2i32 = BUILD_VECTOR # D:1 0x26a48d13cb8, 0x26a48d13c48
                0x26a48d13cb8: i32 = or # D:1 0x26a48d0f648, 0x26a48d0b6d8
                  0x26a48d0f648: i32 = extract_vector_elt 0x26a48d0b198, Constant:i32<0>


                  0x26a48d0b6d8: i32 = shl # D:1 0x26a48d139a8, Constant:i32<3>


                0x26a48d13c48: i32 = extract_vector_elt 0x26a48d0b198, Constant:i32<1>
                  0x26a48d0b198: v2i32 = bitcast 0x26a48d0f5d8

                  0x26a48d0e5a8: i32 = Constant<1>
          0x26a48d0b048: i64 = Constant<1572864>
        0x26a48d0aa98: i64 = undef
    0x26a48d0e228: i32 = Constant<0>
  0x26a48d0ddc8: f32 = extract_vector_elt # D:1 0x26a48d0b5f8, Constant:i32<1>
    0x26a48d0b5f8: v2f32 = bitcast # D:1 0x26a48d138c8
      0x26a48d138c8: v2i32,ch = load<(load (s64) from %ir.24, align 4)> # D:1 0x26a93a90168, 0x26a48d0e538, undef:i64
        0x26a48d0e538: i64 = add # D:1 0x26a48d0e4c8, Constant:i64<1572864>
          0x26a48d0e4c8: i64 = add # D:1 0x26a48d0afd8, 0x26a48d13d98
            0x26a48d0afd8: i64 = bitcast 0x26a48d0ac58
              0x26a48d0ac58: v2i32,ch = load<(dereferenceable invariant load (s64), align 16, addrspace 4)> 0x26a93a90168, 0x26a48d0ab78, undef:i64
                0x26a48d0ab78: i64,ch = CopyFromReg 0x26a93a90168, Register:i64 %1
                  0x26a48d0abe8: i64 = Register %1
                0x26a48d0aa98: i64 = undef
            0x26a48d13d98: i64 = bitcast # D:1 0x26a48d13d28
              0x26a48d13d28: v2i32 = BUILD_VECTOR # D:1 0x26a48d13cb8, 0x26a48d13c48
                0x26a48d13cb8: i32 = or # D:1 0x26a48d0f648, 0x26a48d0b6d8
                  0x26a48d0f648: i32 = extract_vector_elt 0x26a48d0b198, Constant:i32<0>


                  0x26a48d0b6d8: i32 = shl # D:1 0x26a48d139a8, Constant:i32<3>


                0x26a48d13c48: i32 = extract_vector_elt 0x26a48d0b198, Constant:i32<1>
                  0x26a48d0b198: v2i32 = bitcast 0x26a48d0f5d8

                  0x26a48d0e5a8: i32 = Constant<1>
          0x26a48d0b048: i64 = Constant<1572864>
        0x26a48d0aa98: i64 = undef
    0x26a48d0e5a8: i32 = Constant<1>
In function: forward_dispatch_11_softmax_32x64x64xf32
Please report issues to https://github.com/openxla/iree/issues and include the crash backtrace.
Stack dump:
0.      Running pass 'CallGraph Pass Manager' on module 'forward_dispatch_11'.
1.      Running pass 'AMDGPU DAG->DAG Pattern Instruction Selection' on function '@forward_dispatch_11_softmax_32x64x64xf32'
Exception Code: 0x80000003
0x00007FF88DDFE7C5, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0xDE7C5 byte(s), ireeCompilerRunLldMain() + 0x22535 byte(s)
0x00007FF925C01881, C:\WINDOWS\System32\ucrtbase.dll(0x00007FF925B90000) + 0x71881 byte(s), raise() + 0x1E1 byte(s)
0x00007FF925C02851, C:\WINDOWS\System32\ucrtbase.dll(0x00007FF925B90000) + 0x72851 byte(s), abort() + 0x31 byte(s)
0x00007FF88DDE3EF4, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0xC3EF4 byte(s), ireeCompilerRunLldMain() + 0x7C64 byte(s)
0x00007FF89122844A, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x350844A byte(s), ireeCompilerRunLldMain() + 0x344C1BA byte(s)
0x00007FF891231192, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x3511192 byte(s), ireeCompilerRunLldMain() + 0x3454F02 byte(s)
0x00007FF890EB9029, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x3199029 byte(s), ireeCompilerRunLldMain() + 0x30DCD99 byte(s)
0x00007FF89122989F, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x350989F byte(s), ireeCompilerRunLldMain() + 0x344D60F byte(s)
0x00007FF891228F14, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x3508F14 byte(s), ireeCompilerRunLldMain() + 0x344CC84 byte(s)
0x00007FF89122DC5B, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x350DC5B byte(s), ireeCompilerRunLldMain() + 0x34519CB byte(s)
0x00007FF891235361, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x3515361 byte(s), ireeCompilerRunLldMain() + 0x34590D1 byte(s)
0x00007FF8916F963F, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x39D963F byte(s), ireeCompilerRunLldMain() + 0x391D3AF byte(s)
0x00007FF8924F4163, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x47D4163 byte(s), ireeCompilerRunLldMain() + 0x4717ED3 byte(s)
0x00007FF8921CDBE6, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x44ADBE6 byte(s), ireeCompilerRunLldMain() + 0x43F1956 byte(s)
0x00007FF8921CD878, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x44AD878 byte(s), ireeCompilerRunLldMain() + 0x43F15E8 byte(s)
0x00007FF8921CE2D7, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x44AE2D7 byte(s), ireeCompilerRunLldMain() + 0x43F2047 byte(s)
0x00007FF8924F45B4, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x47D45B4 byte(s), ireeCompilerRunLldMain() + 0x4718324 byte(s)
0x00007FF8924F3E60, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x47D3E60 byte(s), ireeCompilerRunLldMain() + 0x4717BD0 byte(s)
0x00007FF88F100290, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x13E0290 byte(s), ireeCompilerRunLldMain() + 0x1324000 byte(s)
0x00007FF88F0FF53D, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x13DF53D byte(s), ireeCompilerRunLldMain() + 0x13232AD byte(s)
0x00007FF88EBF2B2E, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0xED2B2E byte(s), ireeCompilerRunLldMain() + 0xE1689E byte(s)
0x00007FF88DF8274A, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x26274A byte(s), ireeCompilerRunLldMain() + 0x1A64BA byte(s)
0x00007FF88DF87FB3, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x267FB3 byte(s), ireeCompilerRunLldMain() + 0x1ABD23 byte(s)
0x00007FF88DF897F1, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x2697F1 byte(s), ireeCompilerRunLldMain() + 0x1AD561 byte(s)
0x00007FF88DF843FA, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x2643FA byte(s), ireeCompilerRunLldMain() + 0x1A816A byte(s)
0x00007FF88DF826D7, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x2626D7 byte(s), ireeCompilerRunLldMain() + 0x1A6447 byte(s)
0x00007FF88EBF2216, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0xED2216 byte(s), ireeCompilerRunLldMain() + 0xE15F86 byte(s)
0x00007FF88DF8274A, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x26274A byte(s), ireeCompilerRunLldMain() + 0x1A64BA byte(s)
0x00007FF88DF87FB3, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x267FB3 byte(s), ireeCompilerRunLldMain() + 0x1ABD23 byte(s)
0x00007FF88DF897F1, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x2697F1 byte(s), ireeCompilerRunLldMain() + 0x1AD561 byte(s)
0x00007FF88DF84608, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x264608 byte(s), ireeCompilerRunLldMain() + 0x1A8378 byte(s)
0x00007FF88DF05C1C, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0x1E5C1C byte(s), ireeCompilerRunLldMain() + 0x12998C byte(s)
0x00007FF88DDE507F, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0xC507F byte(s), ireeCompilerRunLldMain() + 0x8DEF byte(s)
0x00007FF88DDE40D8, C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF88DD20000) + 0xC40D8 byte(s), ireeCompilerRunLldMain() + 0x7E48 byte(s)
0x00007FF925BB1BB2, C:\WINDOWS\System32\ucrtbase.dll(0x00007FF925B90000) + 0x21BB2 byte(s), _configthreadlocale() + 0x92 byte(s)
0x00007FF926E07344, C:\WINDOWS\System32\KERNEL32.DLL(0x00007FF926DF0000) + 0x17344 byte(s), BaseThreadInitThunk() + 0x14 byte(s)
0x00007FF9280A26B1, C:\WINDOWS\SYSTEM32\ntdll.dll(0x00007FF928050000) + 0x526B1 byte(s), RtlUserThreadStart() + 0x21 byte(s)


Invoked with:
 iree-compile.exe C:\develop\SHARK\shark.venv\Lib\site-packages\iree\compiler\tools\..\_mlir_libs\iree-compile.exe - --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=rocm --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-rocm-target-chip=gfx1100 --iree-rocm-link-bc=true --iree-rocm-bc-dir=C:\Program Files\AMD\ROCm\5.5\amdgcn\bitcode --iree-stream-resource-max-allocation-size=4294967295 --iree-vm-bytecode-module-strip-source-map=true --iree-util-zero-fill-elided-attrs --iree-opt-strip-assertions=true --verify=false --iree-rocm-target-chip=gfx1100 --iree-rocm-link-bc=true --iree-rocm-bc-dir=C:\Program Files\AMD\ROCm\5.5\amdgcn\bitcode --iree-preprocessing-pass-pipeline=builtin.module(func.func(iree-preprocessing-pad-linalg-ops{pad-size=16}))

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.
```

**Comment by PhaneeshB** [comment]
Tracking this on IREE 
https://github.com/openxla/iree/issues/15064

**Comment by nirvedhmeshram** [comment]
should work once the fix is picked up by SRT https://github.com/openxla/iree/pull/15069

**Comment by one-lithe-rune** [comment]
Now fixed for me.
