### ISSUE TITLE
SHARK 20231002.973 Errors

### ISSUE THREAD

**Issue by LoGiCa7** [nod-ai/SHARK#1870]
After generating the VMFB Shark just errors out. I'm using a 6600xt with the latest AMD drivers (23.9.3 )

Tried with several models with the same result.

<img width="1541" alt="shark" src="https://github.com/nod-ai/SHARK/assets/47193468/893475e8-90e6-4004-bea6-cc9174669e41">
<img width="1543" alt="shark2" src="https://github.com/nod-ai/SHARK/assets/47193468/d0f839ca-8307-426b-abf5-c13f4ad35efa">

**Comment by LoGiCa7** [comment]
I've tested this further and found that I don't get any errors when leaving the dimensions on 512x512. I have used height 768 x 512 width on the previous stable build without issue, but on the new stable build it errors out.

**Comment by LoGiCa7** [comment]
Tried build 819 and getting the error: SystemExit: mat1 and mat2 shapes cannot be multiplied (128x1024 and 768x320)

**Comment by monorimet** [comment]
This is a crash on VAE execution. Haven't seen it before -- it looks like the first screenshot shows it completing VAE inference which should be the last step besides maybe a PIL.Image convert to have the image show up in the UI, so I'm surprised it's crashed. The second screenshot looks like a VAE load error.
Can you check to see if the `Low VRAM` checkbox makes a difference? on a 6600xt you might just be running out of memory when loading the last part of the SD pipeline. It could be that we've had some general vulkan optimizations upstream that affect VRAM consumption on some part of the SD pipeline, but it's hard to tell from here.

**Comment by LoGiCa7** [comment]
Checking the Low VRAM box didn't help:

E:\SHARK>nodai_shark_studio_20231005_978.exe --clear_all --local_tank_cache=e:\sharktank
Using e:\sharktank as local shark_tank cache directory.
CLEARING ALL, EXPECT SEVERAL MINUTES TO RECOMPILE
gradio temporary image cache located at E:\SHARK\shark_tmp/gradio. You may change this by setting the GRADIO_TEMP_DIR environment variable.
No temporary images files to clear.
vulkan devices are available.
metal devices are not available.
cuda devices are not available.
rocm devices are available.
shark_tank local cache is located at C:\Users\Studio\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
local-sync devices are available.
shark_tank local cache is located at C:\Users\Studio\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
local-task devices are available.
shark_tank local cache is located at C:\Users\Studio\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
gradio\components\dropdown.py:238: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include:  or set allow_custom_value=True.
Running on local URL:  http://0.0.0.0:8080
shark_tank local cache is located at C:\Users\Studio\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag

To create a public link, set `share=True` in `launch()`.
Found device AMD Radeon RX 6600 XT. Using target triple rdna2-unknown-windows.
Tuned models are currently not supported for this setting.
No vmfb found. Compiling and saving to E:\SHARK\euler_scale_model_input_1_768_512_vulkan_fp16.vmfb
Configuring for device:vulkan://00000000-2f00-0000-0000-000000000000
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in E:\SHARK\euler_scale_model_input_1_768_512_vulkan_fp16.vmfb.
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Program Files (x86)\Epic Games\Launcher\Portal\Extras\Overlay\EOSOverlayVkLayer-Win32.json
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Program Files (x86)\Epic Games\Launcher\Portal\Extras\Overlay\EOSOverlayVkLayer-Win64.json
WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
Loading module E:\SHARK\euler_scale_model_input_1_768_512_vulkan_fp16.vmfb...
        Compiling Vulkan shaders. This may take a few minutes.
No vmfb found. Compiling and saving to E:\SHARK\euler_step_1_768_512_vulkan_fp16.vmfb
Configuring for device:vulkan://00000000-2f00-0000-0000-000000000000
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in E:\SHARK\euler_step_1_768_512_vulkan_fp16.vmfb.
Loading module E:\SHARK\euler_step_1_768_512_vulkan_fp16.vmfb...
        Compiling Vulkan shaders. This may take a few minutes.
use_tuned? sharkify: False
_1_64_768_512_fp16_realisticVisionV51_v51VAE
Diffusers' checkpoint will be identified here :  E:/SHARK/models/diffusers/realisticVisionV51_v51VAE
Loading diffusers' pipeline from original stable diffusion checkpoint
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["bos_token_id"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["eos_token_id"]` will be overriden.
transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
Loading complete
No vmfb found. Compiling and saving to E:\SHARK\clip_1_64_768_512_fp16_realisticVisionV51_v51VAE_vulkan.vmfb
Configuring for device:vulkan://00000000-2f00-0000-0000-000000000000
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in E:\SHARK\clip_1_64_768_512_fp16_realisticVisionV51_v51VAE_vulkan.vmfb.
Loading module E:\SHARK\clip_1_64_768_512_fp16_realisticVisionV51_v51VAE_vulkan.vmfb...
        Compiling Vulkan shaders. This may take a few minutes.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 640, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 607, in run_forever
  File "asyncio\base_events.py", line 1922, in _run_once
  File "asyncio\events.py", line 80, in _run
  File "gradio\queueing.py", line 431, in process_events
  File "gradio\queueing.py", line 388, in call_prediction
  File "gradio\route_utils.py", line 219, in call_process_api
  File "gradio\blocks.py", line 1437, in process_api
  File "gradio\blocks.py", line 1123, in call_function
  File "gradio\utils.py", line 503, in async_iteration
  File "gradio\utils.py", line 496, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 479, in run_sync_iterator_async
  File "gradio\utils.py", line 629, in gen_wrapper
  File "ui\txt2img_ui.py", line 195, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 134, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 235, in produce_img_latents
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 114, in load_unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 855, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 818, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 778, in compile_unet_variants
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 619, in get_unet
  File "apps\stable_diffusion\src\utils\utils.py", line 150, in compile_through_fx
  File "shark\shark_importer.py", line 688, in import_with_fx
    fx_g = make_fx(
           ^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 841, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_dispatch), tracer=fx_tracer, concrete_args=tuple(phs))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\_dynamo\eval_frame.py", line 401, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 461, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\_symbolic_trace.py", line 817, in trace
    (self.create_arg(fn(*args)),),
                     ^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 497, in wrapped
    out = f(*tensors)
          ^^^^^^^^^^^
  File "<string>", line 1, in <lambda>
  File "torch\fx\_symbolic_trace.py", line 795, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 418, in call_module
    return forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\_symbolic_trace.py", line 788, in forward
    return _orig_module_call(mod, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 584, in forward
  File "diffusers\models\unet_2d_condition.py", line 958, in forward
  File "torch\fx\_symbolic_trace.py", line 795, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 418, in call_module
    return forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\_symbolic_trace.py", line 788, in forward
    return _orig_module_call(mod, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "diffusers\models\unet_2d_blocks.py", line 1086, in forward
  File "torch\fx\_symbolic_trace.py", line 795, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 418, in call_module
    return forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\_symbolic_trace.py", line 788, in forward
    return _orig_module_call(mod, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "diffusers\models\transformer_2d.py", line 315, in forward
  File "torch\fx\_symbolic_trace.py", line 795, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 418, in call_module
    return forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\_symbolic_trace.py", line 788, in forward
    return _orig_module_call(mod, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "diffusers\models\attention.py", line 218, in forward
  File "torch\fx\_symbolic_trace.py", line 795, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 418, in call_module
    return forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\_symbolic_trace.py", line 788, in forward
    return _orig_module_call(mod, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "diffusers\models\attention_processor.py", line 417, in forward
  File "diffusers\models\attention_processor.py", line 1023, in __call__
  File "torch\fx\_symbolic_trace.py", line 795, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 418, in call_module
    return forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\_symbolic_trace.py", line 788, in forward
    return _orig_module_call(mod, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "diffusers\models\lora.py", line 224, in forward
  File "torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\utils\_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 574, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 609, in inner_torch_dispatch
    return proxy_call(self, func, self.pre_dispatch, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 354, in proxy_call
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "torch\_ops.py", line 499, in __call__
    return self._op(*args, **kwargs or {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemExit: mat1 and mat2 shapes cannot be multiplied (128x1024 and 768x320)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uvicorn\protocols\websockets\websockets_impl.py", line 247, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 84, in __call__
  File "fastapi\applications.py", line 292, in __call__
  File "starlette\applications.py", line 122, in __call__
  File "starlette\middleware\errors.py", line 149, in __call__
  File "starlette\middleware\cors.py", line 75, in __call__
  File "starlette\middleware\exceptions.py", line 68, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 17, in __call__
  File "starlette\routing.py", line 718, in __call__
  File "starlette\routing.py", line 341, in handle
  File "starlette\routing.py", line 82, in app
  File "fastapi\routing.py", line 324, in app
  File "gradio\routes.py", line 578, in join_queue
  File "asyncio\tasks.py", line 639, in sleep
asyncio.exceptions.CancelledError
ERROR:    Traceback (most recent call last):
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 640, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 607, in run_forever
  File "asyncio\base_events.py", line 1922, in _run_once
  File "asyncio\events.py", line 80, in _run
  File "gradio\queueing.py", line 431, in process_events
  File "gradio\queueing.py", line 388, in call_prediction
  File "gradio\route_utils.py", line 219, in call_process_api
  File "gradio\blocks.py", line 1437, in process_api
  File "gradio\blocks.py", line 1123, in call_function
  File "gradio\utils.py", line 503, in async_iteration
  File "gradio\utils.py", line 496, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 479, in run_sync_iterator_async
  File "gradio\utils.py", line 629, in gen_wrapper
  File "ui\txt2img_ui.py", line 195, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 134, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 235, in produce_img_latents
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 114, in load_unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 855, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 818, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 778, in compile_unet_variants
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 619, in get_unet
  File "apps\stable_diffusion\src\utils\utils.py", line 150, in compile_through_fx
  File "shark\shark_importer.py", line 688, in import_with_fx
    fx_g = make_fx(
           ^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 841, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_dispatch), tracer=fx_tracer, concrete_args=tuple(phs))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\_dynamo\eval_frame.py", line 401, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 461, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\_symbolic_trace.py", line 817, in trace
    (self.create_arg(fn(*args)),),
                     ^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 497, in wrapped
    out = f(*tensors)
          ^^^^^^^^^^^
  File "<string>", line 1, in <lambda>
  File "torch\fx\_symbolic_trace.py", line 795, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 418, in call_module
    return forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\_symbolic_trace.py", line 788, in forward
    return _orig_module_call(mod, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 584, in forward
  File "diffusers\models\unet_2d_condition.py", line 958, in forward
  File "torch\fx\_symbolic_trace.py", line 795, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 418, in call_module
    return forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\_symbolic_trace.py", line 788, in forward
    return _orig_module_call(mod, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "diffusers\models\unet_2d_blocks.py", line 1086, in forward
  File "torch\fx\_symbolic_trace.py", line 795, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 418, in call_module
    return forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\_symbolic_trace.py", line 788, in forward
    return _orig_module_call(mod, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "diffusers\models\transformer_2d.py", line 315, in forward
  File "torch\fx\_symbolic_trace.py", line 795, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 418, in call_module
    return forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\_symbolic_trace.py", line 788, in forward
    return _orig_module_call(mod, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "diffusers\models\attention.py", line 218, in forward
  File "torch\fx\_symbolic_trace.py", line 795, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 418, in call_module
    return forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\_symbolic_trace.py", line 788, in forward
    return _orig_module_call(mod, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "diffusers\models\attention_processor.py", line 417, in forward
  File "diffusers\models\attention_processor.py", line 1023, in __call__
  File "torch\fx\_symbolic_trace.py", line 795, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 418, in call_module
    return forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\_symbolic_trace.py", line 788, in forward
    return _orig_module_call(mod, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "diffusers\models\lora.py", line 224, in forward
  File "torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\utils\_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 574, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 609, in inner_torch_dispatch
    return proxy_call(self, func, self.pre_dispatch, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torch\fx\experimental\proxy_tensor.py", line 354, in proxy_call
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "torch\_ops.py", line 499, in __call__
    return self._op(*args, **kwargs or {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemExit: mat1 and mat2 shapes cannot be multiplied (128x1024 and 768x320)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "starlette\routing.py", line 686, in lifespan
  File "uvicorn\lifespan\on.py", line 137, in receive
  File "asyncio\queues.py", line 158, in get
asyncio.exceptions.CancelledError
