### ISSUE TITLE
Error with nod.ai SHARK 20231005.978

### ISSUE THREAD

**Issue by Joly0** [nod-ai/SHARK#1875]
Hey, i am trying to get SHARK working. I started the programm using the exe and didnt change anything except the model to juggernautXL i downloaded from civitai, but as soon as i try to generate anything with it (as i said, i left anythign else on stock, even the default prompts), i get this error:
```
Loading diffusers' pipeline from original stable diffusion checkpoint
Traceback (most recent call last):
  File "gradio\queueing.py", line 388, in call_prediction
  File "gradio\route_utils.py", line 219, in call_process_api
  File "gradio\blocks.py", line 1437, in process_api
  File "gradio\blocks.py", line 1123, in call_function
  File "gradio\utils.py", line 503, in async_iteration
  File "gradio\utils.py", line 496, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 479, in run_sync_iterator_async
  File "gradio\utils.py", line 629, in gen_wrapper
  File "ui\txt2img_ui.py", line 163, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 359, in from_pretrained
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 164, in __init__
  File "apps\stable_diffusion\src\utils\utils.py", line 596, in preprocessCKPT
  File "diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1627, in download_from_original_stable_diffusion_ckpt
TypeError: StableDiffusionPipeline.__init__() got an unexpected keyword argument 'text_encoder_2'
```

I even tried to let SHARK download that model from civitai and entered the download url and set models to none, but even then, the error is exactly the same. I t starts doing things, downloading the model, and then comes the error

**Comment by ase1590** [comment]
Quick google seems to point towards this being related to the StableDiffusion XL pipeline, which I don't think shark has *yet*.

**Comment by Joly0** [comment]
Hey @monorimet i have seen the pr you mentioned is merged, does that mean sdxl is now available in shark or will be very soon? :)

**Comment by Joly0** [comment]
Hey @monorimet  @Abhishek-Varma What is the current state of this? :)

**Comment by monorimet** [comment]
It's on the way https://github.com/nod-ai/SHARK/pull/1941

custom SDXL models is still up to a week or two out... it's quite a chunky model and the UX needs quite a bit of polish. We'll add it incrementally.

**Comment by Joly0** [comment]
Nice, great to hear there is progess and active development behind it. I think alot of people are waiting for sdxl support :D

**Comment by Kikillervortlex** [comment]
I just saw that SDXL support has been merged in the main. Do you know when the stable release will include this change?
