### ISSUE TITLE
(LLaMa2_7b_int4) Correctness issues on Vulkan + W7900

### ISSUE THREAD

**Issue by monorimet** [nod-ai/SHARK#1890]
There seems to be some garbage results being generated when running LLaMa2_7b_int4 on vulkan backend.

Latest versions have this issue (including stable ver.984)

![image](https://github.com/nod-ai/SHARK/assets/87458719/a1344fb1-194a-4a59-992a-d2b175f56137)

Bonus: hitting "stop" and generating from a new prompt causes... resource exhaustion? Is there some latency associated with the loading/unloading/reusing the vmfb? This is probably a python-side API usage + UI design issue

```
Traceback (most recent call last):
  File "gradio\queueing.py", line 388, in call_prediction
  File "gradio\route_utils.py", line 219, in call_process_api
  File "gradio\blocks.py", line 1437, in process_api
  File "gradio\blocks.py", line 1123, in call_function
  File "gradio\utils.py", line 503, in async_iteration
  File "gradio\utils.py", line 496, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 479, in run_sync_iterator_async
  File "gradio\utils.py", line 629, in gen_wrapper
  File "ui\stablelm_ui.py", line 252, in chat
  File "gradio\helpers.py", line 528, in __next__
  File "apps\language_models\scripts\vicuna.py", line 1790, in generate
  File "apps\language_models\scripts\vicuna.py", line 425, in generate_new_token
  File "shark\shark_inference.py", line 150, in __call__
    return self.shark_runner.run(function_name, inputs, send_to_host)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "shark\shark_runner.py", line 110, in run
    return get_results(
           ^^^^^^^^^^^^
  File "shark\iree_utils\compile_utils.py", line 557, in get_results
    result = compiled_vm[function_name](*device_inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "iree\runtime\function.py", line 137, in __call__
  File "iree\runtime\function.py", line 162, in _invoke
RuntimeError: Error invoking function: C:\actions-runner\w\SRT\SRT\c\runtime\src\iree\hal\drivers\vulkan\native_semaphore.cc:134: RESOURCE_EXHAUSTED; overflowed timeline semaphore max value; while invoking native function hal.fence.await; while calling import;
[ 1]   native hal.fence.await:0 -
[ 0] bytecode module@0:84260 -

```

**Comment by monorimet** [comment]
Update: this may be a dev machine-specific issue with multiple driver installs... going off of basically rumors. If anyone has success on vulkan recently (windows, linux, exe or pyvenv) please chime in.

**Comment by njsharpe** [comment]
Using 7963abb with a git pull and venv, I was able to ask the same question and get a response using vulkan. Additionally, stopping in the middle of generating a new prompt does not cause an error or crash, as you described.

![image](https://github.com/nod-ai/SHARK/assets/24849994/f4ae4770-3d08-465e-9b27-495d4d07720d)

**Comment by monorimet** [comment]
Closed as results point towards system driver installation issues.
