### ISSUE TITLE
Could not compile Unet. 

### ISSUE THREAD

**Issue by Acrivec** [nod-ai/SHARK#1894]
Console asked to report it on here, so here it goes:

```cmd
shark_tank local cache is located at C:\Users\Acrivec\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
gradio temporary image cache located at G:\Downloads\shark_tmp/gradio. You may change this by setting the GRADIO_TEMP_DIR environment variable.
No temporary images files to clear.
Matplotlib is building the font cache; this may take a moment.
vulkan devices are available.
metal devices are not available.
cuda devices are not available.
rocm devices are available.
shark_tank local cache is located at C:\Users\Acrivec\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
local-sync devices are available.
shark_tank local cache is located at C:\Users\Acrivec\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
local-task devices are available.
shark_tank local cache is located at C:\Users\Acrivec\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Running on local URL:  http://0.0.0.0:8080
shark_tank local cache is located at C:\Users\Acrivec\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag

To create a public link, set `share=True` in `launch()`.
Found device AMD Radeon RX 7900 XTX. Using target triple rdna3-7900-windows.
Using tuned models for stabilityai/stable-diffusion-2-1-base(fp16) on device vulkan://00000000-0300-0000-0000-000000000000.
failed to download model, falling back and using import_mlir
saving euler_scale_model_input_1_512_512_vulkan_fp16_torch_linalg.mlir to C:\Users\Acrivec\AppData\Local\Temp
loading existing vmfb from: G:\Downloads\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_VERBOSE does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer name GalaxyOverlayVkLayer_DEBUG does not conform to naming standard (Policy #LLP_LAYER_3)
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_OBS_HOOK uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
Loading module G:\Downloads\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb...
        Compiling Vulkan shaders. This may take a few minutes.
saving euler_step_1_512_512_vulkan_fp16_torch_linalg.mlir to C:\Users\Acrivec\AppData\Local\Temp
loading existing vmfb from: G:\Downloads\euler_step_1_512_512_vulkan_fp16.vmfb
Loading module G:\Downloads\euler_step_1_512_512_vulkan_fp16.vmfb...
        Compiling Vulkan shaders. This may take a few minutes.
use_tuned? sharkify: True
_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base
Loading module G:\Downloads\clip_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb...
        Compiling Vulkan shaders. This may take a few minutes.
torch\fx\node.py:263: UserWarning: Trying to prepend a node to itself. This behavior has no effect on the graph.
  warnings.warn("Trying to prepend a node to itself. This behavior has no effect on the graph.")
Loading Winograd config file from  C:\Users\Acrivec\.local/shark_tank/configs\unet_winograd_vulkan.json
100%|█████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 8.92kB/s]
Loading lowering config file from  C:\Users\Acrivec\.local/shark_tank/configs\unet_v2_1base_64_fp16_vulkan_rdna3_512x512.json
100%|█████████████████████████████████████████████████████████████████████████████| 21.1k/21.1k [00:00<00:00, 1.20MB/s]
100%|█████████████████████████████████████████████████████████████████████████████| 21.1k/21.1k [00:00<00:00, 1.35MB/s]
Applying tuned configs on unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan

Retrying with a different base model configuration
mat1 and mat2 shapes cannot be multiplied (128x768 and 1024x320)
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[4, 7, 512, 512] to have 4 channels, but got 7 channels instead
Retrying with a different base model configuration
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 640, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 607, in run_forever
  File "asyncio\base_events.py", line 1922, in _run_once
  File "asyncio\events.py", line 80, in _run
  File "gradio\queueing.py", line 431, in process_events
  File "gradio\queueing.py", line 388, in call_prediction
  File "gradio\route_utils.py", line 219, in call_process_api
  File "gradio\blocks.py", line 1437, in process_api
  File "gradio\blocks.py", line 1123, in call_function
  File "gradio\utils.py", line 503, in async_iteration
  File "gradio\utils.py", line 496, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 479, in run_sync_iterator_async
  File "gradio\utils.py", line 629, in gen_wrapper
  File "ui\txt2img_ui.py", line 195, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 134, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 235, in produce_img_latents
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 114, in load_unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 858, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 853, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 63, in check_compilation
SystemExit: Could not compile Unet. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uvicorn\protocols\websockets\websockets_impl.py", line 247, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 84, in __call__
  File "fastapi\applications.py", line 292, in __call__
  File "starlette\applications.py", line 122, in __call__
  File "starlette\middleware\errors.py", line 149, in __call__
  File "starlette\middleware\cors.py", line 75, in __call__
  File "starlette\middleware\exceptions.py", line 68, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 17, in __call__
  File "starlette\routing.py", line 718, in __call__
  File "starlette\routing.py", line 341, in handle
  File "starlette\routing.py", line 82, in app
  File "fastapi\routing.py", line 324, in app
  File "gradio\routes.py", line 578, in join_queue
  File "asyncio\tasks.py", line 639, in sleep
asyncio.exceptions.CancelledError
ERROR:    Traceback (most recent call last):
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 640, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 607, in run_forever
  File "asyncio\base_events.py", line 1922, in _run_once
  File "asyncio\events.py", line 80, in _run
  File "gradio\queueing.py", line 431, in process_events
  File "gradio\queueing.py", line 388, in call_prediction
  File "gradio\route_utils.py", line 219, in call_process_api
  File "gradio\blocks.py", line 1437, in process_api
  File "gradio\blocks.py", line 1123, in call_function
  File "gradio\utils.py", line 503, in async_iteration
  File "gradio\utils.py", line 496, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 479, in run_sync_iterator_async
  File "gradio\utils.py", line 629, in gen_wrapper
  File "ui\txt2img_ui.py", line 195, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 134, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 235, in produce_img_latents
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 114, in load_unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 858, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 853, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 63, in check_compilation
SystemExit: Could not compile Unet. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "starlette\routing.py", line 686, in lifespan
  File "uvicorn\lifespan\on.py", line 137, in receive
  File "asyncio\queues.py", line 158, in get
asyncio.exceptions.CancelledError
```

**Comment by Acrivec** [comment]
It works on last dev release after running --clear-all

**Comment by Acrivec** [comment]
Closing as dev build fixed it.
