### ISSUE TITLE
rocm driver error 'hipErrorSharedObjectInitFailed' (303): shared object initialization failed

### ISSUE THREAD

**Issue by incognico** [nod-ai/SHARK#1938]
Win 11, rocm 5.5. First to get it running at all I had to add `C:\Program Files\AMD\ROCm\5.5\bin` to `PATH` because it said it could not find `hipminfo`, however the file is there but called `hipInfo.exe`. Vulkan backend works.

Using txt2img I get the following error: 

```
shark_tank local cache is located at C:\Users\nwohl\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Tuned models are currently not supported for this setting.
saving euler_scale_model_input_1_512_512_rocm_fp16_torch_linalg.mlir to C:\Users\nwohl\AppData\Local\Temp
loading existing vmfb from: C:\Users\nwohl\Downloads\euler_scale_model_input_1_512_512_rocm_fp16.vmfb
Loading module C:\Users\nwohl\Downloads\euler_scale_model_input_1_512_512_rocm_fp16.vmfb...
Traceback (most recent call last):
  File "gradio\queueing.py", line 388, in call_prediction
  File "gradio\route_utils.py", line 219, in call_process_api
  File "gradio\blocks.py", line 1437, in process_api
  File "gradio\blocks.py", line 1123, in call_function
  File "gradio\utils.py", line 503, in async_iteration
  File "gradio\utils.py", line 496, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 479, in run_sync_iterator_async
  File "gradio\utils.py", line 629, in gen_wrapper
  File "ui\txt2img_ui.py", line 160, in txt2img_inf
  File "apps\stable_diffusion\src\schedulers\sd_schedulers.py", line 103, in get_schedulers
  File "apps\stable_diffusion\src\schedulers\shark_eulerdiscrete.py", line 111, in compile
  File "apps\stable_diffusion\src\schedulers\shark_eulerdiscrete.py", line 93, in _import
  File "apps\stable_diffusion\src\utils\utils.py", line 186, in compile_through_fx
  File "apps\stable_diffusion\src\utils\utils.py", line 70, in _compile_module
  File "shark\shark_inference.py", line 224, in load_module
    params = load_flatbuffer(
             ^^^^^^^^^^^^^^^^
  File "shark\iree_utils\compile_utils.py", line 475, in load_flatbuffer
    vmfb, config, temp_file_to_unlink = load_vmfb_using_mmap(
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "shark\iree_utils\compile_utils.py", line 411, in load_vmfb_using_mmap
    ctx.add_vm_module(mmaped_vmfb)
  File "iree\runtime\system_api.py", line 271, in add_vm_module
  File "iree\runtime\system_api.py", line 268, in add_vm_modules
RuntimeError: Error registering modules: C:\actions-runner\w\SRT\SRT\c\experimental\rocm\status_util.c:31: INTERNAL; rocm driver error 'hipErrorSharedObjectInitFailed' (303): shared object initialization failed; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode module@1:250 -
```

hipInfo:
```
--------------------------------------------------------------------------------
device#                           0
Name:                             Radeon RX Vega M GH Graphics
pciBusID:                         1
pciDeviceID:                      0
pciDomainID:                      0
multiProcessorCount:              24
maxThreadsPerMultiProcessor:      2048
isMultiGpuBoard:                  0
clockRate:                        1190 Mhz
memoryClockRate:                  800 Mhz
memoryBusWidth:                   0
totalGlobalMem:                   4.00 GB
totalConstMem:                    2147483647
sharedMemPerBlock:                64.00 KB
canMapHostMemory:                 1
regsPerBlock:                     0
warpSize:                         64
l2CacheSize:                      1048576
computeMode:                      0
maxThreadsPerBlock:               1024
maxThreadsDim.x:                  1024
maxThreadsDim.y:                  1024
maxThreadsDim.z:                  1024
maxGridSize.x:                    2147483647
maxGridSize.y:                    2147483647
maxGridSize.z:                    2147483647
major:                            8
minor:                            0
concurrentKernels:                1
cooperativeLaunch:                0
cooperativeMultiDeviceLaunch:     0
isIntegrated:                     0
maxTexture1D:                     16384
maxTexture2D.width:               16384
maxTexture2D.height:              16384
maxTexture3D.width:               2048
maxTexture3D.height:              2048
maxTexture3D.depth:               2048
isLargeBar:                       0
asicRevision:                     0
maxSharedMemoryPerMultiProcessor: 64.00 KB
clockInstructionRate:             1000.00 Mhz
arch.hasGlobalInt32Atomics:       1
arch.hasGlobalFloatAtomicExch:    1
arch.hasSharedInt32Atomics:       1
arch.hasSharedFloatAtomicExch:    1
arch.hasFloatAtomicAdd:           1
arch.hasGlobalInt64Atomics:       1
arch.hasSharedInt64Atomics:       1
arch.hasDoubles:                  1
arch.hasWarpVote:                 1
arch.hasWarpBallot:               1
arch.hasWarpShuffle:              1
arch.hasFunnelShift:              0
arch.hasThreadFenceSystem:        1
arch.hasSyncThreadsExt:           0
arch.hasSurfaceFuncs:             0
arch.has3dGrid:                   1
arch.hasDynamicParallelism:       0
gcnArchName:                      gfx803
peers:
non-peers:                        device#0

memInfo.total:                    4.00 GB
memInfo.free:                     3.88 GB (97%)
```

**Comment by dmjohn0x** [comment]
Im having the same problem using ROCm on my 7900XT. This is my log: 

`To create a public link, set `share=True` in `launch()`.
Tuned models are currently not supported for this setting.
failed to download model, falling back and using import_mlir
saving euler_scale_model_input_1_512_512_rocm_fp16_torch_linalg.mlir to C:\Users\Admin\AppData\Local\Temp
loading existing vmfb from: L:\LLM\euler_scale_model_input_1_512_512_rocm_fp16.vmfb
Loading module L:\LLM\euler_scale_model_input_1_512_512_rocm_fp16.vmfb...
Traceback (most recent call last):
  File "apps\stable_diffusion\src\schedulers\shark_eulerdiscrete.py", line 112, in compile
  File "apps\stable_diffusion\src\utils\utils.py", line 102, in get_shark_model
  File "shark\shark_downloader.py", line 207, in download_model
    shark_args.shark_prefix = get_sharktank_prefix()
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "shark\shark_downloader.py", line 175, in get_sharktank_prefix
    desired_prefix = get_git_revision_short_hash()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "shark\shark_downloader.py", line 160, in get_git_revision_short_hash
    with open(src, "r") as f:
         ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\_MEI268922\\shark\\..\\tank_version.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gradio\queueing.py", line 388, in call_prediction
  File "gradio\route_utils.py", line 219, in call_process_api
  File "gradio\blocks.py", line 1437, in process_api
  File "gradio\blocks.py", line 1123, in call_function
  File "gradio\utils.py", line 503, in async_iteration
  File "gradio\utils.py", line 496, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 479, in run_sync_iterator_async
  File "gradio\utils.py", line 629, in gen_wrapper
  File "ui\txt2img_ui.py", line 160, in txt2img_inf
  File "apps\stable_diffusion\src\schedulers\sd_schedulers.py", line 103, in get_schedulers
  File "apps\stable_diffusion\src\schedulers\shark_eulerdiscrete.py", line 127, in compile
  File "apps\stable_diffusion\src\schedulers\shark_eulerdiscrete.py", line 90, in _import
  File "apps\stable_diffusion\src\utils\utils.py", line 186, in compile_through_fx
  File "apps\stable_diffusion\src\utils\utils.py", line 70, in _compile_module
  File "shark\shark_inference.py", line 232, in load_module
    params = load_flatbuffer(
             ^^^^^^^^^^^^^^^^
  File "shark\iree_utils\compile_utils.py", line 505, in load_flatbuffer
    vmfb, config, temp_file_to_unlink = load_vmfb_using_mmap(
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "shark\iree_utils\compile_utils.py", line 436, in load_vmfb_using_mmap
    ctx.add_vm_module(mmaped_vmfb)
  File "iree\runtime\system_api.py", line 271, in add_vm_module
  File "iree\runtime\system_api.py", line 268, in add_vm_modules
RuntimeError: Error registering modules: C:\actions-runner\w\SRT\SRT\c\experimental\rocm\status_util.c:31: INTERNAL; rocm driver error 'hipErrorSharedObjectInitFailed' (303): shared object initialization failed; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode module@1:280 -`

**Comment by PhaneeshB** [comment]
Hi folks! Thanks for reporting this issue, it helps us cover a variety of use cases for our end users. 
#1950 should fix the issue, if y'all still face this feel free to reopen, closing for now.
