### ISSUE TITLE
I can't start the program (Port problem, please help)

### ISSUE THREAD

**Issue by P1agueDoc** [nod-ai/SHARK#1945]
Traceback (most recent call last):
  File "D:\AI\NodaAIshark\apps\stable_diffusion\web\index.py", line 438, in <module>
    sd_web.launch(
  File "C:\Users\D0cpl\miniconda3\Lib\site-packages\gradio\blocks.py", line 1907, in launch
    ) = networking.start_server(
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D0cpl\miniconda3\Lib\site-packages\gradio\networking.py", line 207, in start_server
    raise OSError(
OSError: Cannot find empty port in range: 8080-8080. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.
I tried changing stuff in server_port but nothing works, maybe im just doing something wrong.

**Comment by Acrivec** [comment]
Try to close the app that's using 8080 on your computer maybe.
with `python index.py --server_port 8090` you get any other errors?

**Comment by P1agueDoc** [comment]
Thank you. Everything works fine now
