### ISSUE TITLE
Queue error

### ISSUE THREAD

**Issue by Acrivec** [nod-ai/SHARK#1947]
I've queued 10 generations, this is after it started doing second one.
Hires fix was checked. I've noticed that when it's checked - shark is shuffling models constantly in/out of memory, which takes quite some time.
 <details>
 <summary> 

```
Code block collapsed, click to show
```

</summary>

```
        Compiling Vulkan shaders. This may take a few minutes.
50it [00:02, 17.72it/s]
Loading module G:\Downloads\Shark\SHARK\apps\stable_diffusion\web\vae_1_64_512_512_fp16_stable-diffusion-2-1-base_vulkan.vmfb...
        Compiling Vulkan shaders. This may take a few minutes.
Found device AMD Radeon RX 7900 XTX. Using target triple rdna3-7900-windows.
Tuned models are currently not supported for this setting.
saving euler_scale_model_input_1_512_512_vulkan_fp16_torch_linalg.mlir to C:\Users\Acrivec\AppData\Local\Temp
loading existing vmfb from: G:\Downloads\Shark\SHARK\apps\stable_diffusion\web\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb
Loading module G:\Downloads\Shark\SHARK\apps\stable_diffusion\web\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb...
        Compiling Vulkan shaders. This may take a few minutes.
saving euler_step_1_512_512_vulkan_fp16_torch_linalg.mlir to C:\Users\Acrivec\AppData\Local\Temp
loading existing vmfb from: G:\Downloads\Shark\SHARK\apps\stable_diffusion\web\euler_step_1_512_512_vulkan_fp16.vmfb
Loading module G:\Downloads\Shark\SHARK\apps\stable_diffusion\web\euler_step_1_512_512_vulkan_fp16.vmfb...
        Compiling Vulkan shaders. This may take a few minutes.
use_tuned? sharkify: False
_1_64_768_768_fp16_stable-diffusion-2-1-base
Loading module G:\Downloads\Shark\SHARK\apps\stable_diffusion\web\clip_1_64_768_768_fp16_stable-diffusion-2-1-base_vulkan.vmfb...
        Compiling Vulkan shaders. This may take a few minutes.
Loading module G:\Downloads\Shark\SHARK\apps\stable_diffusion\web\vae_encode_1_64_768_768_fp16_stable-diffusion-2-1-base_vulkan.vmfb...
        Compiling Vulkan shaders. This may take a few minutes.
Loading module G:\Downloads\Shark\SHARK\apps\stable_diffusion\web\unet_1_64_768_768_fp16_stable-diffusion-2-1-base_vulkan.vmfb...
        Compiling Vulkan shaders. This may take a few minutes.
50it [00:07,  6.31it/s]
Loading module G:\Downloads\Shark\SHARK\apps\stable_diffusion\web\vae_1_64_768_768_fp16_stable-diffusion-2-1-base_vulkan.vmfb...
        Compiling Vulkan shaders. This may take a few minutes.
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.24it/s]
Traceback (most recent call last):
  File "G:\Downloads\Shark\SHARK\shark.venv\Lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Downloads\Shark\SHARK\shark.venv\Lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Downloads\Shark\SHARK\shark.venv\Lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Downloads\Shark\SHARK\shark.venv\Lib\site-packages\gradio\blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Downloads\Shark\SHARK\shark.venv\Lib\site-packages\gradio\utils.py", line 503, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Downloads\Shark\SHARK\shark.venv\Lib\site-packages\gradio\utils.py", line 496, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Downloads\Shark\SHARK\shark.venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Downloads\Shark\SHARK\shark.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "G:\Downloads\Shark\SHARK\shark.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Downloads\Shark\SHARK\shark.venv\Lib\site-packages\gradio\utils.py", line 479, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "G:\Downloads\Shark\SHARK\shark.venv\Lib\site-packages\gradio\utils.py", line 629, in gen_wrapper
    yield from f(*args, **kwargs)
  File "G:\Downloads\Shark\SHARK\apps\stable_diffusion\web\ui\txt2img_ui.py", line 192, in txt2img_inf
    out_imgs = global_obj.get_sd_obj().generate_images(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Image2ImagePipeline.generate_images() missing 4 required positional arguments: 'cpu_scheduling', 'max_embeddings_multiples', 'use_stencil', and 'resample_type'

```

</details>

**Comment by monorimet** [comment]
@gpetters94 could this be related to the issue you're having with multicontrolnet? This sounds a lot like how you described the behavior.

**Comment by gpetters94** [comment]
I don't think this is the same issue I was having, but I'll take a look.
