### ISSUE TITLE
chatbot fails with error WindowsPath found

### ISSUE THREAD

**Issue by sp1d3rx** [nod-ai/SHARK#1969]
Looking into gs://shark_tank/llama2_7b/unsharded/vmfb/llama2_7b_int4_vulkan_rdna3_7900.vmfb
[DEBUG] vmfb not found (search path: llama2_7b_int4_vulkan_rdna3_7900.vmfb)
Looking into gs://shark_tank/llama2_7b/unsharded/mlir/llama2_7b_int4.mlirbc
[DEBUG] mlir found at F:\Download\Web\llama2_7b_int4.mlir
vulkan
Configuring for device:vulkan
Using target triple -iree-vulkan-target-triple=rdna3-7900-windows from command line args
Traceback (most recent call last):
  File "gradio\queueing.py", line 388, in call_prediction
  File "gradio\route_utils.py", line 219, in call_process_api
  File "gradio\blocks.py", line 1437, in process_api
  File "gradio\blocks.py", line 1123, in call_function
  File "gradio\utils.py", line 503, in async_iteration
  File "gradio\utils.py", line 496, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 479, in run_sync_iterator_async
  File "gradio\utils.py", line 629, in gen_wrapper
  File "ui\stablelm_ui.py", line 228, in chat
  File "apps\language_models\scripts\vicuna.py", line 1302, in __init__
  File "apps\language_models\scripts\vicuna.py", line 1757, in compile
  File "shark\shark_inference.py", line 206, in save_module
    return export_iree_module_to_vmfb(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "shark\iree_utils\compile_utils.py", line 504, in export_iree_module_to_vmfb
    flatbuffer_blob = compile_module_to_flatbuffer(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "shark\iree_utils\compile_utils.py", line 324, in compile_module_to_flatbuffer
    flatbuffer_blob = ireec.compile_file(
                      ^^^^^^^^^^^^^^^^^^^
  File "iree\compiler\tools\core.py", line 256, in compile_file
  File "iree\compiler\tools\binaries.py", line 200, in invoke_immediate
  File "iree\compiler\tools\binaries.py", line 81, in __init__
TypeError: sequence item 1: expected str instance, WindowsPath found

**Comment by sp1d3rx** [comment]
nodai_shark_studio_20231009_984.exe

**Comment by monorimet** [comment]
This is fixed by https://github.com/nod-ai/SHARK/pull/1901, though I thought that stable release didn't have this issue. Sorry about that.

Chatbot should be quite stable and performant on our latest pre-release: https://github.com/nod-ai/SHARK/releases/download/20231110.1021/nodai_shark_studio_20231110_1021.exe

**Comment by monorimet** [comment]
(you can reuse the llama2 .mlir so you dont have to re-download it, just drop it in the same folder as the new .exe)

**Comment by monorimet** [comment]
Closing this issue for now. We can reopen it if you see this issue on versions after #1901 .
