### ISSUE TITLE
(Studio) RuntimeError: operator torchvision::nms does not exist @ 803a33d4 (current head)

### ISSUE THREAD

**Issue by one-lithe-rune** [nod-ai/SHARK#1987]
On Windows at studio startup. Still occurs after `.\setup_venv.ps1 --force`. Doesn't occur at the previous commit of 4125a26

Maybe something missing from/wrong in `requirements.txt`?

```
(shark.venv) PS C:\develop\SHARK> shark-run
80a33d4 (HEAD -> main, origin/main, origin/HEAD) Save intermediate values of controlnet (#1981)
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
shark_tank local cache is located at C:\Users\skapusniak\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Traceback (most recent call last):
  File "C:\develop\SHARK\apps\stable_diffusion\web\index.py", line 5, in <module>
    import apps.stable_diffusion.web.utils.app as app
  File "C:\develop\SHARK\apps\stable_diffusion\web\utils\app.py", line 10, in <module>
    from apps.stable_diffusion.src import args
  File "C:\develop\SHARK\apps\stable_diffusion\src\__init__.py", line 1, in <module>
    from apps.stable_diffusion.src.utils import (
  File "C:\develop\SHARK\apps\stable_diffusion\src\utils\__init__.py", line 14, in <module>
    from apps.stable_diffusion.src.utils.stencils.stencil_utils import (
  File "C:\develop\SHARK\apps\stable_diffusion\src\utils\stencils\stencil_utils.py", line 6, in <module>
    import torchvision
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\torchvision\_meta_registrations.py", line 163, in <module>
    @torch._custom_ops.impl_abstract("torchvision::nms")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\torch\library.py", line 417, in inner
    handle = entry.abstract_impl.register(func, source)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark.venv\Lib\site-packages\torch\_library\abstract_impl.py", line 30, in register
    if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: operator torchvision::nms does not exist
```

**Comment by njsharpe** [comment]
Just got this. Reverted to older version of SHARK (in my case, I reverted to my previously used version [1026](https://github.com/nod-ai/SHARK/releases/tag/20231115.1026).

**Comment by one-lithe-rune** [comment]
Fixed for me
