### ISSUE TITLE
"Could not compile Unet.  Please create an issue with the detailed log...."

### ISSUE THREAD

**Issue by jgiddens** [nod-ai/SHARK#2107]
Hi there.  Just installed NODAI Shark today.. i am on Windows 11 with a RX7900xtx.

I can start the EXE from the powershell prompt and you see the terminal output below.  The interface opens and/or i can lose https://localhost:8080 just fine.  I dont change anything at all from the standard prompt and hit the generate image button to see if it works.  It doesnt.  The stdout told me to open an issue with this log, so here goes.

```
PS C:\Users\jgidd\Downloads\nodai> & '.\nodai_shark_studio_20230713_819 (1).exe'
shark_tank local cache is located at C:\Users\jgidd\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
gradio temporary image cache located at C:\Users\jgidd\Downloads\nodai\shark_tmp/gradio. You may change this by setting the GRADIO_TEMP_DIR environment variable.
No temporary images files to clear.
vulkan devices are available.
shark_tank local cache is located at C:\Users\jgidd\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
metal devices are not available.
cuda devices are not available.
local-sync devices are available.
shark_tank local cache is located at C:\Users\jgidd\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
local-task devices are available.
shark_tank local cache is located at C:\Users\jgidd\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
diffusers\models\cross_attention.py:30: FutureWarning: Importing from cross_attention is deprecated. Please import from diffusers.models.attention_processor instead.
['12th Gen Intel(R) Core(TM) i7-12700 => local-task://0', 'AMD Radeon RX 7900 XTX => vulkan://0']
shark_tank local cache is located at C:\Users\jgidd\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
Found device AMD Radeon RX 7900 XTX. Using target triple rdna3-7900-windows.
Using tuned models for stabilityai/stable-diffusion-2-1-base(fp16) on device vulkan://00000000-0300-0000-0000-000000000000.
failed to download model, falling back and using import_mlir
loading existing vmfb from: C:\Users\jgidd\Downloads\nodai\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb
Loading flatbuffer at C:\Users\jgidd\Downloads\nodai\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb as a mmapped file
loading existing vmfb from: C:\Users\jgidd\Downloads\nodai\euler_step_1_512_512_vulkan_fp16.vmfb
Loading flatbuffer at C:\Users\jgidd\Downloads\nodai\euler_step_1_512_512_vulkan_fp16.vmfb as a mmapped file
use_tuned? sharkify: True
_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading flatbuffer at C:\Users\jgidd\Downloads\nodai\clip_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Loading flatbuffer at C:\Users\jgidd\Downloads\nodai\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\native_executable.cc:51: UNAVAILABLE; VK_ERROR_INITIALIZATION_FAILED; vkCreateShaderModule; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode module@1:1404 -
Retrying with a different base model configuration
Loading flatbuffer at C:\Users\jgidd\Downloads\nodai\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\native_executable.cc:51: UNAVAILABLE; VK_ERROR_INITIALIZATION_FAILED; vkCreateShaderModule; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode module@1:1404 -
Retrying with a different base model configuration
Loading flatbuffer at C:\Users\jgidd\Downloads\nodai\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\native_executable.cc:51: UNAVAILABLE; VK_ERROR_INITIALIZATION_FAILED; vkCreateShaderModule; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode module@1:1404 -
Retrying with a different base model configuration
Loading flatbuffer at C:\Users\jgidd\Downloads\nodai\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\native_executable.cc:51: UNAVAILABLE; VK_ERROR_INITIALIZATION_FAILED; vkCreateShaderModule; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode module@1:1404 -
Retrying with a different base model configuration
Loading flatbuffer at C:\Users\jgidd\Downloads\nodai\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\native_executable.cc:51: UNAVAILABLE; VK_ERROR_INITIALIZATION_FAILED; vkCreateShaderModule; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode module@1:1404 -
Retrying with a different base model configuration
Traceback (most recent call last):
  File "gradio\routes.py", line 439, in run_predict
  File "gradio\blocks.py", line 1384, in process_api
  File "gradio\blocks.py", line 1103, in call_function
  File "gradio\utils.py", line 343, in async_iteration
  File "gradio\utils.py", line 336, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 319, in run_sync_iterator_async
  File "gradio\utils.py", line 688, in gen_wrapper
  File "ui\txt2img_ui.py", line 186, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 134, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 235, in produce_img_latents
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 114, in load_unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 826, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 821, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 63, in check_compilation
SystemExit: Could not compile Unet. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues
```

**Comment by monorimet** [comment]
[AMD Official Use Only - General]

Hi there, thanks for posting! You might have a Vulkan driver that isn’t compatible with the instructions compiled through the exe. Can you check for a vulkan version in Adrenalin software?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: jgiddens ***@***.***>
Sent: Saturday, March 23, 2024 3:08:24 PM
To: nod-ai/SHARK ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nod-ai/SHARK] "Could not compile Unet. Please create an issue with the detailed log...." (Issue #2107)

Caution: This message originated from an External Source. Use proper caution when opening attachments, clicking links, or responding.


Hi there. Just installed NODAI Shark today.. i am on Windows 11 with a RX7900xtx.

I can start the EXE from the powershell prompt and you see the terminal output below. The interface opens and/or i can lose https://localhost:8080 just fine. I dont change anything at all from the standard prompt and hit the generate image button to see if it works. It doesnt. The stdout told me to open an issue with this log, so here goes.

PS C:\Users\jgidd\Downloads\nodai> & '.\nodai_shark_studio_20230713_819 (1).exe'
shark_tank local cache is located at C:\Users\jgidd\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
gradio temporary image cache located at C:\Users\jgidd\Downloads\nodai\shark_tmp/gradio. You may change this by setting the GRADIO_TEMP_DIR environment variable.
No temporary images files to clear.
vulkan devices are available.
shark_tank local cache is located at C:\Users\jgidd\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
metal devices are not available.
cuda devices are not available.
local-sync devices are available.
shark_tank local cache is located at C:\Users\jgidd\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
local-task devices are available.
shark_tank local cache is located at C:\Users\jgidd\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
diffusers\models\cross_attention.py:30: FutureWarning: Importing from cross_attention is deprecated. Please import from diffusers.models.attention_processor instead.
['12th Gen Intel(R) Core(TM) i7-12700 => local-task://0', 'AMD Radeon RX 7900 XTX => vulkan://0']
shark_tank local cache is located at C:\Users\jgidd\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
Found device AMD Radeon RX 7900 XTX. Using target triple rdna3-7900-windows.
Using tuned models for stabilityai/stable-diffusion-2-1-base(fp16) on device vulkan://00000000-0300-0000-0000-000000000000.
failed to download model, falling back and using import_mlir
loading existing vmfb from: C:\Users\jgidd\Downloads\nodai\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb
Loading flatbuffer at C:\Users\jgidd\Downloads\nodai\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb as a mmapped file
loading existing vmfb from: C:\Users\jgidd\Downloads\nodai\euler_step_1_512_512_vulkan_fp16.vmfb
Loading flatbuffer at C:\Users\jgidd\Downloads\nodai\euler_step_1_512_512_vulkan_fp16.vmfb as a mmapped file
use_tuned? sharkify: True
_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading flatbuffer at C:\Users\jgidd\Downloads\nodai\clip_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Loading flatbuffer at C:\Users\jgidd\Downloads\nodai\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\native_executable.cc:51: UNAVAILABLE; VK_ERROR_INITIALIZATION_FAILED; vkCreateShaderModule; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode ***@***.***:1404 -
Retrying with a different base model configuration
Loading flatbuffer at C:\Users\jgidd\Downloads\nodai\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\native_executable.cc:51: UNAVAILABLE; VK_ERROR_INITIALIZATION_FAILED; vkCreateShaderModule; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode ***@***.***:1404 -
Retrying with a different base model configuration
Loading flatbuffer at C:\Users\jgidd\Downloads\nodai\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\native_executable.cc:51: UNAVAILABLE; VK_ERROR_INITIALIZATION_FAILED; vkCreateShaderModule; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode ***@***.***:1404 -
Retrying with a different base model configuration
Loading flatbuffer at C:\Users\jgidd\Downloads\nodai\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\native_executable.cc:51: UNAVAILABLE; VK_ERROR_INITIALIZATION_FAILED; vkCreateShaderModule; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode ***@***.***:1404 -
Retrying with a different base model configuration
Loading flatbuffer at C:\Users\jgidd\Downloads\nodai\unet_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\native_executable.cc:51: UNAVAILABLE; VK_ERROR_INITIALIZATION_FAILED; vkCreateShaderModule; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode ***@***.***:1404 -
Retrying with a different base model configuration
Traceback (most recent call last):
  File "gradio\routes.py", line 439, in run_predict
  File "gradio\blocks.py", line 1384, in process_api
  File "gradio\blocks.py", line 1103, in call_function
  File "gradio\utils.py", line 343, in async_iteration
  File "gradio\utils.py", line 336, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 319, in run_sync_iterator_async
  File "gradio\utils.py", line 688, in gen_wrapper
  File "ui\txt2img_ui.py", line 186, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 134, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 235, in produce_img_latents
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 114, in load_unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 826, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 821, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 63, in check_compilation
SystemExit: Could not compile Unet. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues

**Comment by jgiddens** [comment]
Here is what my system looks like in Adrenalin:

Vulkan Driver is 2.0.294

![image](https://github.com/nod-ai/SHARK/assets/2255444/ddb84fce-50cf-4ec9-bb78-3aecfb449893)

**Comment by AndreiSager** [comment]
I have the same problem.

```
shark_tank local cache is located at C:\Users\andre\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
gradio temporary image cache located at A:\A.I. Sidehustle\shark-nod-ai\shark_tmp/gradio. You may change this by setting the GRADIO_TEMP_DIR environment variable.
No temporary images files to clear.
vulkan devices are available.
metal devices are not available.
cuda devices are not available.
rocm devices are not available.
local-sync devices are available.
shark_tank local cache is located at C:\Users\andre\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
local-task devices are available.
shark_tank local cache is located at C:\Users\andre\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Running on local URL:  http://0.0.0.0:8080
shark_tank local cache is located at C:\Users\andre\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag

To create a public link, set `share=True` in `launch()`.
Found device AMD Radeon(TM) RX Vega 11 Graphics. Using target triple rdna2-unknown-windows.
Using tuned models for stabilityai/stable-diffusion-2-1-base(fp16) on device vulkan://29000000-0000-0000-0000-000000000000.
saving euler_scale_model_input_1_512_512_vulkan_fp16_torch_linalg.mlir to C:\Users\andre\AppData\Local\Temp
loading existing vmfb from: A:\A.I. Sidehustle\shark-nod-ai\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb
WARNING: [Loader Message] Code 0 : ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
Loading module A:\A.I. Sidehustle\shark-nod-ai\euler_scale_model_input_1_512_512_vulkan_fp16.vmfb...
        Compiling Vulkan shaders. This may take a few minutes.
saving euler_step_1_512_512_vulkan_fp16_torch_linalg.mlir to C:\Users\andre\AppData\Local\Temp
loading existing vmfb from: A:\A.I. Sidehustle\shark-nod-ai\euler_step_1_512_512_vulkan_fp16.vmfb
Loading module A:\A.I. Sidehustle\shark-nod-ai\euler_step_1_512_512_vulkan_fp16.vmfb...
        Compiling Vulkan shaders. This may take a few minutes.
use_tuned? sharkify: True
_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base
Loading module A:\A.I. Sidehustle\shark-nod-ai\clip_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb...
        Compiling Vulkan shaders. This may take a few minutes.
torch\fx\node.py:263: UserWarning: Trying to prepend a node to itself. This behavior has no effect on the graph.
  warnings.warn("Trying to prepend a node to itself. This behavior has no effect on the graph.")
Loading Winograd config file from  C:\Users\andre\.local/shark_tank/configs\unet_winograd_vulkan.json
100%|█████████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 1.76kB/s]

Retrying with a different base model configuration
mat1 and mat2 shapes cannot be multiplied (128x768 and 1024x320)
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead
Retrying with a different base model configuration
Given groups=1, weight of size [320, 4, 3, 3], expected input[4, 7, 512, 512] to have 4 channels, but got 7 channels instead
Retrying with a different base model configuration
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 640, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 607, in run_forever
  File "asyncio\base_events.py", line 1922, in _run_once
  File "asyncio\events.py", line 80, in _run
  File "gradio\queueing.py", line 431, in process_events
  File "gradio\queueing.py", line 388, in call_prediction
  File "gradio\route_utils.py", line 219, in call_process_api
  File "gradio\blocks.py", line 1437, in process_api
  File "gradio\blocks.py", line 1123, in call_function
  File "gradio\utils.py", line 503, in async_iteration
  File "gradio\utils.py", line 496, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 479, in run_sync_iterator_async
  File "gradio\utils.py", line 629, in gen_wrapper
  File "ui\txt2img_ui.py", line 195, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 134, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 235, in produce_img_latents
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 114, in load_unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 858, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 853, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 63, in check_compilation
SystemExit: Could not compile Unet. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uvicorn\protocols\websockets\websockets_impl.py", line 247, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 84, in __call__
  File "fastapi\applications.py", line 292, in __call__
  File "starlette\applications.py", line 122, in __call__
  File "starlette\middleware\errors.py", line 149, in __call__
  File "starlette\middleware\cors.py", line 75, in __call__
  File "starlette\middleware\exceptions.py", line 68, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 17, in __call__
  File "starlette\routing.py", line 718, in __call__
  File "starlette\routing.py", line 341, in handle
  File "starlette\routing.py", line 82, in app
  File "fastapi\routing.py", line 324, in app
  File "gradio\routes.py", line 578, in join_queue
  File "asyncio\tasks.py", line 639, in sleep
asyncio.exceptions.CancelledError
ERROR:    Traceback (most recent call last):
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 640, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 607, in run_forever
  File "asyncio\base_events.py", line 1922, in _run_once
  File "asyncio\events.py", line 80, in _run
  File "gradio\queueing.py", line 431, in process_events
  File "gradio\queueing.py", line 388, in call_prediction
  File "gradio\route_utils.py", line 219, in call_process_api
  File "gradio\blocks.py", line 1437, in process_api
  File "gradio\blocks.py", line 1123, in call_function
  File "gradio\utils.py", line 503, in async_iteration
  File "gradio\utils.py", line 496, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 479, in run_sync_iterator_async
  File "gradio\utils.py", line 629, in gen_wrapper
  File "ui\txt2img_ui.py", line 195, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 134, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 235, in produce_img_latents
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 114, in load_unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 858, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 853, in unet
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 63, in check_compilation
**SystemExit: Could not compile Unet. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "starlette\routing.py", line 686, in lifespan
  File "uvicorn\lifespan\on.py", line 137, in receive
  File "asyncio\queues.py", line 158, in get
asyncio.exceptions.CancelledError
```
