### ISSUE TITLE
Error Device Unknown, AMD GPU rocm not recognized on an RX7600XT

### ISSUE THREAD

**Issue by Dabigboythe2nd** [nod-ai/SHARK#2160]
As you can see in the title, GPU not recognized. Using the latest drivers for AMD (24.5.1) on a RX7600 XT

``rocm` devices are available.
local-sync devices are available.
local-task devices are available.
vulkan devices are available.
metal devices are not available.
cuda devices are not available.
hip devices are available.
Clearing .mlir temporary files from a prior run. This may take some time...
Clearing .mlir temporary files took 0.0010 seconds.
gradio temporary image cache located at C:\Users\vicmo\OneDrive\Documents\SHARK\shark_tmp\gradio. You may change this by setting the GRADIO_TEMP_DIR environment variable.
Clearing gradio UI temporary image files from a prior run. This may take some time...
Clearing gradio UI temporary image files took 0.0010 seconds.
gradio temporary image cache located at C:\Users\vicmo\OneDrive\Documents\SHARK\shark_tmp\gradio. You may change this by setting the GRADIO_TEMP_DIR environment variable.
No temporary images files to clear.
diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
To create a public link, set `share=True` in `launch()`.

[LOG] Submitting Request...

Traceback (most recent call last):
  File "C:\Users\vicmo\AppData\Local\Temp\_MEI94362\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vicmo\AppData\Local\Temp\_MEI94362\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vicmo\AppData\Local\Temp\_MEI94362\gradio\blocks.py", line 1847, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vicmo\AppData\Local\Temp\_MEI94362\gradio\blocks.py", line 1445, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vicmo\AppData\Local\Temp\_MEI94362\gradio\utils.py", line 629, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vicmo\AppData\Local\Temp\_MEI94362\gradio\utils.py", line 622, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "anyio\to_thread.py", line 56, in run_sync
  File "anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 859, in run
  File "C:\Users\vicmo\AppData\Local\Temp\_MEI94362\gradio\utils.py", line 605, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "C:\Users\vicmo\AppData\Local\Temp\_MEI94362\gradio\utils.py", line 788, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "apps\shark_studio\api\sd.py", line 309, in shark_sd_fn_dict_input
  File "apps\shark_studio\api\utils.py", line 169, in parse_device
  File "apps\shark_studio\api\utils.py", line 194, in get_rocm_target_chip
AssertionError: Device Unknown AMD GPU => rocm not recognized. Please file an issue at https://github.com/nod-ai/SHARK/issues.``

**Comment by Dabigboythe2nd** [comment]
Update, it's the same with hip as well. Only Vulcan seems to work

**Comment by Jake012345** [comment]
Nothing so far?
