### ISSUE TITLE
Device not recognized error for Radeon RX 580

### ISSUE THREAD

**Issue by IdleJuffowup** [nod-ai/SHARK#2167]
[LOG] Submitting Request...

Traceback (most recent call last):
  File "C:\Users\Boys\AppData\Local\Temp\_MEI66762\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boys\AppData\Local\Temp\_MEI66762\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boys\AppData\Local\Temp\_MEI66762\gradio\blocks.py", line 1847, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boys\AppData\Local\Temp\_MEI66762\gradio\blocks.py", line 1445, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boys\AppData\Local\Temp\_MEI66762\gradio\utils.py", line 629, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boys\AppData\Local\Temp\_MEI66762\gradio\utils.py", line 622, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "anyio\to_thread.py", line 56, in run_sync
  File "anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 859, in run
  File "C:\Users\Boys\AppData\Local\Temp\_MEI66762\gradio\utils.py", line 605, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "C:\Users\Boys\AppData\Local\Temp\_MEI66762\gradio\utils.py", line 788, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "apps\shark_studio\api\sd.py", line 309, in shark_sd_fn_dict_input
  File "apps\shark_studio\api\utils.py", line 169, in parse_device
  File "apps\shark_studio\api\utils.py", line 194, in get_rocm_target_chip
AssertionError: Device Radeon RX 580 Series => rocm not recognized. Please file an issue at https://github.com/nod-ai/SHARK/issues.

Error happens using the latest stable build (1300)

**Comment by Amexsos** [comment]
I am also getting same error when running newest version for AMD Radeon RX 6750 XT.  Just did a AMD software uninstall, restarted, ran AMD cleaner tool, restarted, installed latest AMD Software Minimum install with latest driver 

[LOG] Summting Request

Traceback (most recent call last):
  File "C:\Users\Steve\AppData\Local\Temp\_MEI23882\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steve\AppData\Local\Temp\_MEI23882\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steve\AppData\Local\Temp\_MEI23882\gradio\blocks.py", line 1847, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steve\AppData\Local\Temp\_MEI23882\gradio\blocks.py", line 1445, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steve\AppData\Local\Temp\_MEI23882\gradio\utils.py", line 629, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steve\AppData\Local\Temp\_MEI23882\gradio\utils.py", line 622, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "anyio\to_thread.py", line 56, in run_sync
  File "anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 859, in run
  File "C:\Users\Steve\AppData\Local\Temp\_MEI23882\gradio\utils.py", line 605, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "C:\Users\Steve\AppData\Local\Temp\_MEI23882\gradio\utils.py", line 788, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "apps\shark_studio\api\sd.py", line 309, in shark_sd_fn_dict_input
  File "apps\shark_studio\api\utils.py", line 169, in parse_device
  File "apps\shark_studio\api\utils.py", line 194, in get_rocm_target_chip
AssertionError: Device AMD Radeon RX 6750 XT => rocm not recognized. Please file an issue at https://github.com/nod-ai/SHARK/issues.

**Comment by brsh1** [comment]
have you tried running using vulkan? 
first check you have vulkan with vulkaninfo from PS or cmd.
run EXE with --device="vulkan" please report if it works for you
you can also try and run with --device="hip"

**Comment by davenport651** [comment]
Hello,
I have an AMD Radeon RX570 8GB and I am having the same issue on Windows 10 using the latest available binary release `nod.ai SHARK 20240531.1300`. My current AMD Adrenalin drivers are at 23.11.1.

I tried these commands but all have the same result:

`nodai_shark_studio_20240531_1300.exe`
`nodai_shark_studio_20240531_1300.exe --device="vulkan"`
`nodai_shark_studio_20240531_1300.exe --device="hip"`

...but each time I get the following traceback:

> Traceback (most recent call last):
>   File "C:\Users\DAVENP\AppData\Local\Temp\_MEI129482\gradio\queueing.py", line 527, in process_events
>     response = await route_utils.call_process_api(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\DAVENP\AppData\Local\Temp\_MEI129482\gradio\route_utils.py", line 270, in call_process_api
>     output = await app.get_blocks().process_api(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\DAVENP\AppData\Local\Temp\_MEI129482\gradio\blocks.py", line 1847, in process_api
>     result = await self.call_function(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\DAVENP\AppData\Local\Temp\_MEI129482\gradio\blocks.py", line 1445, in call_function
>     prediction = await utils.async_iteration(iterator)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\DAVENP\AppData\Local\Temp\_MEI129482\gradio\utils.py", line 629, in async_iteration
>     return await iterator.__anext__()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\DAVENP\AppData\Local\Temp\_MEI129482\gradio\utils.py", line 622, in __anext__
>     return await anyio.to_thread.run_sync(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "anyio\to_thread.py", line 56, in run_sync
>   File "anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
>   File "anyio\_backends\_asyncio.py", line 859, in run
>   File "C:\Users\DAVENP\AppData\Local\Temp\_MEI129482\gradio\utils.py", line 605, in run_sync_iterator_async
>     return next(iterator)
>            ^^^^^^^^^^^^^^
>   File "C:\Users\DAVENP\AppData\Local\Temp\_MEI129482\gradio\utils.py", line 788, in gen_wrapper
>     response = next(iterator)
>                ^^^^^^^^^^^^^^
>   File "apps\shark_studio\api\sd.py", line 309, in shark_sd_fn_dict_input
>   File "apps\shark_studio\api\utils.py", line 169, in parse_device
>   File "apps\shark_studio\api\utils.py", line 194, in get_rocm_target_chip
> AssertionError: Device Radeon RX 570 Series => rocm not recognized. Please file an issue at https://github.com/nod-ai/SHARK/issues.

Please let me know if there are any other suggestions.
