### ISSUE TITLE
PyTorch DistilBERT fails to lower in torch-mlir (aten.view op)

### ISSUE THREAD

**Issue by monorimet** [nod-ai/SHARK#354]
```
Traceback (most recent call last):
  File "/data/anush/actions-runner/_work/SHARK/SHARK/generate_sharktank.py", line 240, in <module>
    save_torch_model(args.torch_model_csv)
  File "/data/anush/actions-runner/_work/SHARK/SHARK/generate_sharktank.py", line 94, in save_torch_model
    mlir_importer.import_debug(
  File "/data/anush/actions-runner/_work/SHARK/SHARK/shark/shark_importer.py", line 163, in import_debug
    imported_mlir = self.import_mlir(
  File "/data/anush/actions-runner/_work/SHARK/SHARK/shark/shark_importer.py", line 109, in import_mlir
    return self._torch_mlir(is_dynamic, tracing_required), func_name
  File "/data/anush/actions-runner/_work/SHARK/SHARK/shark/shark_importer.py", line 74, in _torch_mlir
    return get_torch_mlir_module(
  File "/data/anush/actions-runner/_work/SHARK/SHARK/shark/torch_mlir_utils.py", line 69, in get_torch_mlir_module
    module = torch_mlir.compile(
  File "/data/anush/actions-runner/_work/SHARK/SHARK/shark.venv/lib/python3.10/site-packages/torch_mlir/__init__.py", line 273, in compile
    run_pipeline_with_repro_report(
  File "/data/anush/actions-runner/_work/SHARK/SHARK/shark.venv/lib/python3.10/site-packages/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering Torch Backend IR -> Linalg-on-Tensors Backend IR failed with the following diagnostics:
error: failed to legalize operation 'torch.aten.view' that was explicitly marked illegal
note: see current operation: %683 = "torch.aten.view"(%681, %682) : (!torch.vtensor<[?,?,768],f32>, !torch.list<int>) -> !torch.vtensor<[?,?,12,64],f32>


Error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='torch-backend-to-linalg-on-tensors-backend-pipeline' ./shark_tmp/HuggingFaceLanguage.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
```

**Comment by vivekkhandelwal1** [comment]
Hi @monorimet, I think the lowering for the `aten.view` op for this case is not supported in the torch-mlir. @JakopinA can comment more on this.
