### ISSUE TITLE
DistilGPT2 to TOSA

### ISSUE THREAD

**Issue by AmosLewis** [nod-ai/SHARK#494]
The script to run:
https://gist.github.com/AmosLewis/465795bfa1a4004fb96c742666515027

THE FINAL TOSA FILE:
[distilgpt2_tosa_20230123.mlir](https://storage.googleapis.com/shark_tank/chi-nod/distilgpt2/20230123/distilgpt_torch_tosa_0123_transformers4.21.2_elide.mlir)

Other bugs to fix:
> RefineTypes1 crash **[MERGED]** https://github.com/llvm/torch-mlir/issues/1599
> RefineTypes2  unk **[MERGED]** 
>>aten.amax : Has a decompose for it, but doesnot work for distilgpt2. DecomposeAtenAmaxOp 
>> torch.aten.select.int : Has a decompose for it, but doesnot work for distilgpt2. DecomposeAtenSelectIntOp 
>>>The 2 decomposed bugs are fixed by Ramiro: **[MERGED]** https://github.com/llvm/torch-mlir/pull/1750+https://github.com/llvm/torch-mlir/pull/1769 + **[MERGED]** https://github.com/llvm/torch-mlir/pull/1742
select.int negative index support https://github.com/llvm/torch-mlir/pull/1787

Ops to Fix:
> aten.view **[Merged]**  https://github.com/llvm/torch-mlir/pull/1768
> torch.aten.slice.Tensor/select.int **[Merged]**  https://github.com/llvm/torch-mlir/pull/1787
> torch.prim.NumToTensor.Scalar f64  **[TOSA NOT SUPPORT F64]** https://github.com/llvm/torch-mlir/pull/1802

Ops to add:
> torch.ops.prims.convert_element_type **MERGED** https://github.com/llvm/torch-mlir/pull/1619 Added a decompose 
> aten.as_stride: Fixed by deleting decomposition of the torch.ops.aten.slice.Tensor in python make_fx code. The as_strided is generated by [slice decompostion](https://github.com/pytorch/pytorch/blob/8f3600b966d896986e334b9a22c43e937ee0169d/torch/_decomp/decompositions.py#L663)
>> Deprecated Chi patch https://github.com/llvm/torch-mlir/pull/1742,
>> Deprecated Alec patch:[tosa WIP](https://github.com/llvm/torch-mlir/pull/1621) ,  [linalg wip](https://github.com/llvm/torch-mlir/pull/1656)

> torch.aten.index.Tensor/torch.prim.ListConstruct **[MERGED]** https://github.com/llvm/torch-mlir/pull/1771, need to add convert for ListConstruct with non-const value.

**Comment by AmosLewis** [comment]
Bug
```
/home/alec/Nod/torch-mlir/mlir_venv/lib/python3.10/site-packages/torch/jit/_check.py:181: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
python: /home/alec/Nod/torch-mlir/externals/llvm-project/llvm/include/llvm/Support/Casting.h:648: decltype(auto) llvm::dyn_cast(const From &) [To = mlir::IntegerType, From = mlir::Type]: Assertion `detail::isPresent(Val) && "dyn_cast on a non-existent value"' failed.
Aborted (core dumped)
```

**Comment by JakopinA** [comment]
Currently working on the op aten.as_strided

**Comment by JakopinA** [comment]
Still working on the op. Here's the draft PR: https://github.com/llvm/torch-mlir/pull/1656

**Comment by AmosLewis** [comment]
https://github.com/llvm/torch-mlir/compare/main...JakopinA:torch-mlir:jakopina-asstrided-tosa

**Comment by AmosLewis** [comment]
Bug
```
➜  distillGPT2 git:(main) ✗ python distillgpt2.py
Some weights of the model checkpoint at distilgpt2 were not used when initializing GPT2ForSequenceClassification: ['lm_head.weight']
- This IS expected if you are initializing GPT2ForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing GPT2ForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at distilgpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
model(test_input): 
tensor([[0.8815, 0.0087]], grad_fn=<IndexBackward0>)
/home/chi/src/ubuntu20/shark/SHARK/shark.venv/lib/python3.10/site-packages/torch/jit/_check.py:181: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
python3.10: /home/chi/src/ubuntu20/shark/torch-mlir/include/torch-mlir/Dialect/Torch/IR/TorchTypes.h:77: mlir::Type mlir::torch::Torch::BaseTensorType::getDtype() const: Assertion `hasDtype() && "must have a dtype"' failed.
[24]    1539869 abort (core dumped)  python3.10 distillgpt2.py

```

**Comment by AmosLewis** [comment]
After the up 2 bug, got convert to tosa bug:
```
//===-------------------------------------------===//
Legalizing operation : 'torch.aten.view'(0x9533eb0) {
  %128 = "torch.aten.view"(%arg1, %127) : (!torch.tensor, !torch.list<int>) -> !torch.tensor

  * Fold {
  } -> FAILURE : unable to fold

  * Pattern : 'torch.aten.view -> ()' {
Trying to match "(anonymous namespace)::ConvertAtenOp<mlir::torch::Torch::AtenViewOp>"
    ** Failure : Only tensor types are currently supported
"(anonymous namespace)::ConvertAtenOp<mlir::torch::Torch::AtenViewOp>" result 0
  } -> FAILURE : pattern failed to match
} -> FAILURE : no matched legalization pattern
```

**Comment by AmosLewis** [comment]
With the as_stride and decompose bug fixed, then we got **torch.aten.slice.Tensor** bug:
```
error: failed to legalize operation 'torch.aten.slice.Tensor' that was explicitly marked illegal
note: see current operation: %1652 = "torch.aten.slice.Tensor"(%1648, %1, %5, %3, %1) : (!torch.vtensor<[1,128,2],f32>, !torch.int, !torch.int, !torch.int, !torch.int) -> !torch.vtensor<[1,1,2],f32>
```
The weird thing is:
I use the ```torch-mlir-opt -pass-pipeline='builtin.module(torch-backend-to-tosa-backend-pipeline)' /tmp/_lambda.mlir -mlir-print-ir-after-all -mlir-disable-threading --debug``` to get the final mlir file mixed with tosa and torch ops. https://gist.github.com/AmosLewis/01e4eaaab7f57940251679b8c818e932 . The torch.aten.slice.Tensor is the last few ops in this mlir. But before it, there is plenty of torch.ops still there, which means their rewrite pattern fails. But they didn't output a pattern mismatch error. This doesn't make sense to me. Because those ops, say aten.view lower to tosa code is there. If its rewrite fails, shouldn't it output error before torch.aten.slice.Tensor?
I am planning to fix the 'torch.aten.slice.Tensor'  first.

**Comment by AmosLewis** [comment]
This is all the 34 ops that are not converted successfully in distilgpt
```
torch.aten.as_strided
torch.aten.view
torch.aten.arange.start_step 
torch.aten.unsqueeze
torch.aten.embedding
torch.aten.add.Tensor
torch.aten.native_layer_norm
torch.aten.mm
torch.aten.mul.Scalar
torch.aten.add.Tensor
torch.aten.permute 
torch.aten.transpose.int
torch.aten.broadcast_to
torch.aten.bmm
torch.aten.clone
torch.aten.div.Tensor
torch.aten.to.dtype
torch.aten.clone
torch.aten.where.self
torch.aten.max.dim
torch.aten.sub.Tensor
torch.aten.exp
torch.aten.sum.dim_IntList
torch.aten.div.Tensor
torch.aten.broadcast_to
torch.aten.bmm
torch.aten.pow.Tensor_Scalar
torch.aten.mul.Scalar
torch.aten.sum.dim_IntList
torch.aten.tanh
torch.aten.transpose.int 

torch.aten.slice.Tensor
torch.aten.squeeze.dim
torch.aten.index.Tensor
```

**Comment by AmosLewis** [comment]
After the slice tensor fix, only  torch.aten.index.Tensor left:
```
  %530 = torch_c.from_builtin_tensor %24 : tensor<1xi64> -> !torch.vtensor<[1],si64>
  %531 = "tosa.slice"(%529) {size = [1, 1, 2], start = [0, 127, 0]} : (tensor<1x128x2xf32>) -> tensor<1x1x2xf32>
  %532 = "tosa.reshape"(%531) {new_shape = [1, 2]} : (tensor<1x1x2xf32>) -> tensor<1x2xf32>
  %533 = torch_c.from_builtin_tensor %532 : tensor<1x2xf32> -> !torch.vtensor<[1,2],f32>
  %534 = torch.prim.ListConstruct %530 : (!torch.vtensor<[1],si64>) -> !torch.list<vtensor>
  %535 = torch.aten.index.Tensor %533, %534 : !torch.vtensor<[1,2],f32>, !torch.list<vtensor> -> !torch.vtensor<[1,2],f32>
  %536 = torch_c.to_builtin_tensor %535 : !torch.vtensor<[1,2],f32> -> tensor<1x2xf32>
```

**Comment by AmosLewis** [comment]
New ops to be fixed. `torch.prim.NumToTensor.Scalar`
```
Traceback (most recent call last):
  File "/home/chi/src/ubuntu20/shark/torch-mlir/distillGPT2/distillgpt2.py", line 92, in <module>
    module = torch_mlir.compile(
  File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 386, in compile
    run_pipeline_with_repro_report(
  File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering Torch Backend IR -> TOSA Backend IR failed with the following diagnostics:
error: failed to legalize operation 'torch.prim.NumToTensor.Scalar' that was explicitly marked illegal
note: see current operation: %318 = "torch.prim.NumToTensor.Scalar"(%188) : (!torch.float) -> !torch.vtensor<[],f64>


For Torch-MLIR developers, the error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='builtin.module(torch-backend-to-tosa-backend-pipeline)' /tmp/_lambda.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.

```

**Comment by AmosLewis** [comment]
After the `torch.prim.NumToTensor.Scalar` fix, the t`orch.aten.to.dtype` shown

```
Traceback (most recent call last):
  File "/home/chi/src/ubuntu20/shark/torch-mlir/distillGPT2/distillgpt2.py", line 92, in <module>
    module = torch_mlir.compile(
  File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 386, in compile
    run_pipeline_with_repro_report(
  File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering Torch Backend IR -> TOSA Backend IR failed with the following diagnostics:
error: failed to legalize operation 'torch.aten.to.dtype' that was explicitly marked illegal
note: see current operation: %321 = "torch.aten.to.dtype"(%320, %8, %9, %9, %11) : (!torch.vtensor<[],f64>, !torch.int, !torch.bool, !torch.bool, !torch.none) -> !torch.vtensor<[],f32>
```

**Comment by AmosLewis** [comment]
f64 is a know issue for tosa, there is not a easy solution to fix it right now. https://github.com/llvm/torch-mlir/issues/1615
So I am planning to downgrade the transformers=4.21.2

**Comment by AmosLewis** [comment]
```
func.func @torch.aten.slice(%arg1: !torch.tensor {torch.type_bound = !torch.vtensor<[1,128],si64>}) -> !torch.tensor {
  %int-1 = torch.constant.int -1
  %int128 = torch.constant.int 128
  %0 = torch.prim.ListConstruct %int-1, %int128 : (!torch.int, !torch.int) -> !torch.list<int>
  %1 = torch.aten.view %arg1, %0 : !torch.tensor, !torch.list<int> -> !torch.tensor
  return %1 : !torch.tensor
}
```

```
//===-------------------------------------------===//
Legalizing operation : 'torch.aten.view'(0x563996c2d170) {
  %3 = "torch.aten.view"(%arg0, %2) : (!torch.tensor, !torch.list<int>) -> !torch.tensor

  * Fold {
  } -> FAILURE : unable to fold

  * Pattern : 'torch.aten.view -> ()' {
Trying to match "(anonymous namespace)::ConvertAtenOp<mlir::torch::Torch::AtenViewOp>"
    ** Failure : Only tensor types are currently supported
"(anonymous namespace)::ConvertAtenOp<mlir::torch::Torch::AtenViewOp>" result 0
  } -> FAILURE : pattern failed to match
} -> FAILURE : no matched legalization pattern
//===-------------------------------------------===//
/tmp/view.mlir:5:8: error: failed to legalize operation 'torch.aten.view' that was explicitly marked illegal
  %1 = torch.aten.view %arg1, %0 : !torch.tensor, !torch.list<int> -> !torch.tensor
       ^
/tmp/view.mlir:5:8: note: see current operation: %3 = "torch.aten.view"(%arg0, %2) : (!torch.tensor, !torch.list<int>) -> !torch.tensor
ImplicitTypeIDRegistry::lookupOrInsert(mlir::detail::PreservedAnalyses::AllAnalysesType)

```

**Comment by AmosLewis** [comment]
https://gist.github.com/AmosLewis/f69629625defdcd9105c3216226e5e9f
