### ISSUE TITLE
Precompiled resnet50 model uses removed MLIR op `linalg.init_tensor`

### ISSUE THREAD

**Issue by sogartar** [nod-ai/SHARK#599]
On commit b62ee3fcb978571f7eec93140abe59dc20ae895f
```
import iree.runtime
from shark.shark_downloader import download_model
from shark.shark_inference import SharkInference

mlir_model, func_name, inputs, golden_out = download_model(
  "resnet50", frontend="torch"
)

shark_module = SharkInference(mlir_model, func_name, mlir_dialect="linalg")
shark_module.compile()
```
Result
```
Traceback (most recent call last):
  File "/home/petkantchin/ws/intel-stress-test/shark/stress-test.py", line 10, in <module>
    shark_module.compile()
  File "/home/petkantchin/ws/nodlabs/shark/repo/shark/shark_inference.py", line 123, in compile
    self.shark_runner = SharkRunner(
  File "/home/petkantchin/ws/nodlabs/shark/repo/shark/shark_runner.py", line 86, in __init__
    ) = get_iree_compiled_module(
  File "/home/petkantchin/ws/nodlabs/shark/repo/shark/iree_utils/compile_utils.py", line 294, in get_iree_compiled_module
    flatbuffer_blob = compile_module_to_flatbuffer(
  File "/home/petkantchin/ws/nodlabs/shark/repo/shark/iree_utils/compile_utils.py", line 264, in compile_module_to_flatbuffer
    flatbuffer_blob = ireec.compile_str(
  File "/home/petkantchin/ws/iree/iree_venv/lib/python3.10/site-packages/iree/compiler/tools/core.py", line 278, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/home/petkantchin/ws/iree/iree_venv/lib/python3.10/site-packages/iree/compiler/tools/binaries.py", line 196, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
<stdin>:277:10: error: custom op 'linalg.init_tensor' is unknown
    %0 = linalg.init_tensor [1, 64, 112, 112] : tensor<1x64x112x112xf32>
```

I think this op got deprecated and removed from the linalg dialect.
We have to retranslate the model in Torch-MLIR. This may have to be done for all other models as well because there is a high chance they also use this op.
It seems this model is not auto tested. It is desirable all models to be under test to catch regressions.

**Comment by monorimet** [comment]
Thanks for the issue -- this model is in the testing framework but there's been some problems with false passes when running pytests with multiprocessing, a fix for which is top priority on my end.

**Comment by monorimet** [comment]
Closing this as the issue was fixed upstream.
