### ISSUE TITLE
Is there a braindead-level guide to installing this GUI?

### ISSUE THREAD

**Issue by Jamesedward11** [nod-ai/SHARK#637]
i uh... need help.
I get this message when i execute this `(shark.venv)PS C:\Windows\system32\SHARK\web> python index.py`

`Traceback (most recent call last):
  File "C:\Windows\system32\SHARK\web\index.py", line 3, in <module>
    from models.stable_diffusion.main import stable_diff_inf
  File "C:\Windows\system32\SHARK\web\models\stable_diffusion\main.py", line 4, in <module>
    from models.stable_diffusion.cache_objects import (
  File "C:\Windows\system32\SHARK\web\models\stable_diffusion\cache_objects.py", line 52, in <module>
    ) = (get_vae(args), get_unet(args), get_clip(args))
  File "C:\Windows\system32\SHARK\web\models\stable_diffusion\opt_params.py", line 69, in get_vae
    return get_shark_model(args, bucket, model_name, iree_flags)
  File "C:\Windows\system32\SHARK\web\models\stable_diffusion\utils.py", line 52, in get_shark_model
    return _compile_module(args, shark_module, model_name, extra_args)
  File "C:\Windows\system32\SHARK\web\models\stable_diffusion\utils.py", line 30, in _compile_module
    shark_module.load_module(vmfb_path)
  File "C:\Windows\System32\SHARK\shark\shark_inference.py", line 209, in load_module
    ) = load_flatbuffer(
  File "C:\Windows\System32\SHARK\shark\iree_utils\compile_utils.py", line 308, in load_flatbuffer
    return get_iree_module(flatbuffer_blob, device, func_name)
  File "C:\Windows\System32\SHARK\shark\iree_utils\compile_utils.py", line 281, in get_iree_module
    ctx.add_vm_module(vm_module)
  File "C:\Windows\system32\SHARK\shark.venv\lib\site-packages\iree\runtime\system_api.py", line 255, in add_vm_module
    self.add_vm_modules((vm_module,))
  File "C:\Windows\system32\SHARK\shark.venv\lib\site-packages\iree\runtime\system_api.py", line 252, in add_vm_modules
    self._vm_context.register_modules(vm_modules)
RuntimeError: Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\native_executable.cc:157: UNKNOWN; VkResult=4294967283; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode module.__init:3000 <stdin>:667:12
      at <stdin>:21:3`
      
What, do I do? I've been digging through the whole internet looking for some way to run this on my 5700XT and it;s given me so much grief that i'm near giving up

**Comment by Jamesedward11** [comment]
I'm going to try obliterating the directory and reattempting install

**Comment by Jamesedward11** [comment]
Okay, Getting further,
Git clone to Directory and then shove the executable inside it and run it

**Comment by Jamesedward11** [comment]
Attempting to see if Updating AMD Adrenalin helps at all

**Comment by Jamesedward11** [comment]
I should probably actually print out the whole vulkaninfo
Jank solution to it but 
[vulkaninfo.txt](https://github.com/nod-ai/SHARK/files/10233403/vulkaninfo.txt)

**Comment by Jamesedward11** [comment]
Yay.
(shark.venv) PS C:\Users\Dire\Desktop\S H A R K Y> python generate_sharktank.py
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at microsoft/MiniLM-L12-H384-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "C:\Users\Dire\Desktop\S H A R K Y\generate_sharktank.py", line 240, in <module>
    save_torch_model(args.torch_model_csv)
  File "C:\Users\Dire\Desktop\S H A R K Y\generate_sharktank.py", line 80, in save_torch_model
    mlir_importer.import_debug(
  File "C:\Users\Dire\Desktop\S H A R K Y\shark\shark_importer.py", line 169, in import_debug
    imported_mlir = self.import_mlir(
  File "C:\Users\Dire\Desktop\S H A R K Y\shark\shark_importer.py", line 113, in import_mlir
    return self._torch_mlir(is_dynamic, tracing_required), func_name
  File "C:\Users\Dire\Desktop\S H A R K Y\shark\shark_importer.py", line 72, in _torch_mlir
    from shark.torch_mlir_utils import get_torch_mlir_module
  File "C:\Users\Dire\Desktop\S H A R K Y\shark\torch_mlir_utils.py", line 15, in <module>
    from torch_mlir.ir import StringAttr
  File "C:\Users\Dire\Desktop\S H A R K Y\shark.venv\lib\site-packages\torch_mlir\__init__.py", line 15, in <module>
    from torch_mlir.passmanager import PassManager
  File "C:\Users\Dire\Desktop\S H A R K Y\shark.venv\lib\site-packages\torch_mlir\passmanager.py", line 5, in <module>
    from ._mlir_libs._mlir.passmanager import *
  File "C:\Users\Dire\Desktop\S H A R K Y\shark.venv\lib\site-packages\torch_mlir\_mlir_libs\__init__.py", line 107, in <module>
    _site_initialize()
  File "C:\Users\Dire\Desktop\S H A R K Y\shark.venv\lib\site-packages\torch_mlir\_mlir_libs\__init__.py", line 56, in _site_initialize
    from ._mlir import ir
ImportError: DLL load failed while importing _mlir: The specified module could not be found.

**Comment by Jamesedward11** [comment]
Something is missing from Hugging Face...

**Comment by Jamesedward11** [comment]
i have come to the conclusion that i am helplessly stranded

**Comment by averad** [comment]
Try:

https://github.com/nod-ai/SHARK/blob/main/shark/examples/shark_inference/stable_diffusion/stable_diffusion_amd.md
