### ISSUE TITLE
Strange error after trying to generate image using amd(Radeon RX6600m)

### ISSUE THREAD

**Issue by yoou3-cyber** [nod-ai/SHARK#727]
Ayoo everyone i did everything like it was in instruction:
1. installed provided AMD driver
2. Opened foled with exe in the CMD
3. started exe and while installing necessaries i got strange errors:
```
torchvision\io\image.py:13: UserWarning: Failed to load image Python extension:
torch\_jit_internal.py:839: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x000002AF78A7A560>.
  warnings.warn(
torch\_jit_internal.py:839: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x000002AF78A9C8B0>.
  warnings.warn(
```
and
`WARNING: [Loader Message] Code 0 : windows_read_data_files_in_registry: Registry lookup failed to get layer manifest fil`
as an instruction said i will get a reauest for port from windows if successfull, and i got, i opened localhost:8080 in the browser and it looked cool but after i pressed "generate image" i got "error" text in the image panel and got this error code in the CMD:
```
0it [00:02, ?it/s]
Traceback (most recent call last):
  File "gradio\routes.py", line 321, in run_predict
  File "gradio\blocks.py", line 1006, in process_api
  File "gradio\blocks.py", line 847, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "models\stable_diffusion\main.py", line 107, in stable_diff_inf
  File "shark\shark_inference.py", line 142, in forward
  File "shark\shark_runner.py", line 95, in run
  File "shark\iree_utils\compile_utils.py", line 356, in get_results
  File "iree\runtime\function.py", line 130, in __call__
  File "iree\runtime\function.py", line 154, in _invoke
RuntimeError: Error invoking function: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\native_semaphore.cc:155: RESOURCE_EXHAUSTED; overflowed timeline semaphore max value; while invoking native function hal.fence.await; while calling import;
[ 1]   native hal.fence.await:0 -
[ 0] bytecode module.forward:142382 [
    <stdin>:822:11
      at <stdin>:28:3,
    <stdin>:810:11
      at <stdin>:28:3,
    <stdin>:786:10
      at <stdin>:28:3,
    <stdin>:761:10
      at <stdin>:28:3,
    <stdin>:766:10...
```
full error code looks too long if it will be neded i will send it but it looks like 
```
    <stdin>:822:11
      at <stdin>:28:3,
    <stdin>:810:11
      at <stdin>:28:3,
    <stdin>:786:10
      at <stdin>:28:3,
    <stdin>:761:10
for a billion times
      at <stdin>:28:
```3,

**Comment by Barneq** [comment]
I just produced the same error trying to use [Redshift-WD12-SD14-NAI-FMD_Checkpoint_Merger_-_Hyper-Versatile_Stable_Diffusion_Model]

ValueError: Error invoking function: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\modules\hal\utils\buffer_diagnostics.c:220: INVALID_ARGUMENT; tensor shape dimension 1 mismatch; expected 77 but have 64; expected shape 2x77, actual shape 2x64; while invoking native function hal.buffer_view.assert; while calling import;
[ 1]   native hal.buffer_view.assert:0 -
[ 0] bytecode module.forward:2580 <stdin>:16:3
