### ISSUE TITLE
Getting "Connection errored out." error in web GUI

### ISSUE THREAD

**Issue by SheeUn** [nod-ai/SHARK#737]
I have Win10 and Radeon RX 570, I did everything the guide says, tried setting up virtual environment as well as launching from shark .exe and still get this error, where did I miss?

**Comment by SheeUn** [comment]
This is what I get using command line

Traceback (most recent call last):
  File "C:\SHARK\SHARK\shark\examples\shark_inference\stable_diffusion\main.py", line 104, in <module>
    unet = get_unet()
  File "C:\SHARK\SHARK\shark\examples\shark_inference\stable_diffusion\opt_params.py", line 72, in get_unet
    return get_shark_model(bucket, model_name, iree_flags)
  File "C:\SHARK\SHARK\shark\examples\shark_inference\stable_diffusion\utils.py", line 58, in get_shark_model
    return _compile_module(shark_module, model_name, extra_args)
  File "C:\SHARK\SHARK\shark\examples\shark_inference\stable_diffusion\utils.py", line 23, in _compile_module
    shark_module.load_module(vmfb_path, extra_args=extra_args)
  File "C:\SHARK\SHARK\shark\shark_inference.py", line 209, in load_module
    ) = load_flatbuffer(
  File "C:\SHARK\SHARK\shark\iree_utils\compile_utils.py", line 314, in load_flatbuffer
    return get_iree_module(flatbuffer_blob, device, func_name)
  File "C:\SHARK\SHARK\shark\iree_utils\compile_utils.py", line 288, in get_iree_module
    ModuleCompiled = ctx.modules.module[func_name]
  File "C:\SHARK\SHARK\shark.venv\lib\site-packages\iree\runtime\system_api.py", line 168, in __getitem__
    raise KeyError(f"Function '{name}' not found in module '{self}'")
KeyError: "Function 'forward' not found in module '<BoundModule <VmModule module : []>>'"
