### ISSUE TITLE
Having this error while launching the model from command prompt

### ISSUE THREAD

**Issue by SheeUn** [nod-ai/SHARK#765]
When I try to generate images from the command prompt, I get this error.
What can be the issue?

 File "C:\SHARK\shark\examples\shark_inference\stable_diffusion\main.py", line 104, in <module>
    unet = get_unet()
  File "C:\SHARK\shark\examples\shark_inference\stable_diffusion\opt_params.py", line 72, in get_unet
    return get_shark_model(bucket, model_name, iree_flags)
  File "C:\SHARK\shark\examples\shark_inference\stable_diffusion\utils.py", line 58, in get_shark_model
    return _compile_module(shark_module, model_name, extra_args)
  File "C:\SHARK\shark\examples\shark_inference\stable_diffusion\utils.py", line 23, in _compile_module
    shark_module.load_module(vmfb_path, extra_args=extra_args)
  File "C:\SHARK\shark\shark_inference.py", line 209, in load_module
    ) = load_flatbuffer(
  File "C:\SHARK\shark\iree_utils\compile_utils.py", line 314, in load_flatbuffer
    return get_iree_module(flatbuffer_blob, device, func_name)
  File "C:\SHARK\shark\iree_utils\compile_utils.py", line 288, in get_iree_module
    ModuleCompiled = ctx.modules.module[func_name]
  File "C:\SHARK\shark.venv\lib\site-packages\iree\runtime\system_api.py", line 168, in __getitem__
    raise KeyError(f"Function '{name}' not found in module '{self}'")
KeyError: "Function 'forward' not found in module '<BoundModule <VmModule module : []>>'"

**Comment by Galantha** [comment]
similar issue for me:
Traceback (most recent call last):
  File "gradio\routes.py", line 337, in run_predict
  File "gradio\blocks.py", line 1015, in process_api
  File "gradio\blocks.py", line 833, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "models\stable_diffusion\main.py", line 221, in stable_diff_inf
  File "shark\shark_inference.py", line 136, in __call__
  File "shark\shark_runner.py", line 90, in run
  File "shark\iree_utils\compile_utils.py", line 362, in get_results
  File "iree\runtime\system_api.py", line 168, in __getitem__
KeyError: "Function 'forward' not found in module '<BoundModule <VmModule module : []>>'"
Keyboard interruption in main thread... closing server.

**Comment by powderluv** [comment]
Typically means your compile failed. Does your system have 16G or less system RAM ? 

We are making some improvements to reduce memory usage

**Comment by Yacnnn** [comment]
the shark_tank folder to delete can be found at 
C:\Users<Your_USERNAME>\.local\shark_tank

**Comment by SheeUn** [comment]
Everything works fine now, thanks for the updates and improvements!
