### ISSUE TITLE
google.auth.exceptions.InvalidOperation: Anonymous credentials cannot be refreshed.

### ISSUE THREAD

**Issue by Coderx7** [nod-ai/SHARK#830]
After installing the SHARK and upon trying it out using the webui provided, it crashed with this error: 
```
(py310) hossein@hossein-pc:~/SHARK$ cd web/
(py310) hossein@hossein-pc:~/SHARK/web$ python index.py 
vulkan devices are available.
cuda devices are available.
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
[WARNING] Only 14.41GB space available in /home/hossein/SHARK/web.
Found device NVIDIA GeForce RTX 3080. Using target triple .
Tuned models are currently not supported for this setting.
shark_tank local cache is located at /home/hossein/.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Downloading artifacts for model euler_scale_model_input_fp16...
Traceback (most recent call last):
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/hossein/SHARK/web/models/stable_diffusion/main.py", line 161, in stable_diff_inf
    model_cache.set_models(device_key)
  File "/home/hossein/SHARK/web/models/stable_diffusion/cache_objects.py", line 104, in set_models
    self.schedulers = get_schedulers(args.version)
  File "/home/hossein/SHARK/web/models/stable_diffusion/cache_objects.py", line 65, in get_schedulers
    schedulers["SharkEulerDiscrete"].compile()
  File "/home/hossein/SHARK/web/models/stable_diffusion/schedulers.py", line 99, in compile
    self.scaling_model = get_shark_model(
  File "/home/hossein/SHARK/web/models/stable_diffusion/utils.py", line 50, in get_shark_model
    mlir_model, func_name, inputs, golden_out = download_model(
  File "/home/hossein/SHARK/shark/shark_downloader.py", line 156, in download_model
    download_public_file(full_gs_url, model_dir)
  File "/home/hossein/SHARK/shark/shark_downloader.py", line 49, in download_public_file
    for blob in blobs:
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 208, in _items_iter
    for page in self._page_iter(increment=False):
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 244, in _page_iter
    page = self._next_page()
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 373, in _next_page
    response = self._get_next_page_response()
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/google/api_core/page_iterator.py", line 432, in _get_next_page_response
    return self.api_request(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 482, in api_request
    response = self._make_request(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 341, in _make_request
    return self._do_request(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/google/cloud/_http/__init__.py", line 379, in _do_request
    return self.http.request(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/google/auth/transport/requests.py", line 585, in request
    self.credentials.refresh(auth_request)
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/google/auth/credentials.py", line 196, in refresh
    raise exceptions.InvalidOperation("Anonymous credentials cannot be refreshed.")
google.auth.exceptions.InvalidOperation: Anonymous credentials cannot be refreshed.
[WARNING] Only 14.42GB space available in /home/hossein/SHARK/web.
Tuned models are currently not supported for this setting.
Traceback (most recent call last):
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/hossein/SHARK/web/models/stable_diffusion/main.py", line 161, in stable_diff_inf
    model_cache.set_models(device_key)
  File "/home/hossein/SHARK/web/models/stable_diffusion/cache_objects.py", line 98, in set_models
    del self.schedulers
AttributeError: schedulers
[WARNING] Only 14.42GB space available in /home/hossein/SHARK/web.
Traceback (most recent call last):
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/hossein/SHARK/web/models/stable_diffusion/main.py", line 162, in stable_diff_inf
    tokenizer = model_cache.tokenizer
AttributeError: 'ModelCache' object has no attribute 'tokenizer'
[WARNING] Only 14.42GB space available in /home/hossein/SHARK/web.
Found device NVIDIA GeForce RTX 3080. Using target triple .
Tuned models are currently not supported for this setting.
Traceback (most recent call last):
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/hossein/SHARK/web/models/stable_diffusion/main.py", line 161, in stable_diff_inf
    model_cache.set_models(device_key)
  File "/home/hossein/SHARK/web/models/stable_diffusion/cache_objects.py", line 98, in set_models
    del self.schedulers
AttributeError: schedulers
[WARNING] Only 14.42GB space available in /home/hossein/SHARK/web.
Traceback (most recent call last):
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/hossein/SHARK/web/models/stable_diffusion/main.py", line 162, in stable_diff_inf
    tokenizer = model_cache.tokenizer
AttributeError: 'ModelCache' object has no attribute 'tokenizer'

^CKeyboard interruption in main thread... closing server.
^CTraceback (most recent call last):
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/blocks.py", line 1636, in block_thread
    time.sleep(0.1)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hossein/SHARK/web/index.py", line 166, in <module>
    shark_web.launch(
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/blocks.py", line 1556, in launch
    self.block_thread()
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/blocks.py", line 1639, in block_thread
    self.server.close()
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/site-packages/gradio/networking.py", line 43, in close
    self.thread.join()
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/home/hossein/anaconda3/envs/py310/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt

```
whats wrong?

**Comment by powderluv** [comment]
Would it be possible to try with python venv instead of conda ? We haven't tested conda much

**Comment by powderluv** [comment]
This should be resolved. Please reopen if it is still happening.
