### ISSUE TITLE
No module named shark

### ISSUE THREAD

**Issue by DuckersMcQuack** [nod-ai/SHARK#850]
I cd to web, then paste "python index.py", press enter, and i get this error:

(deck@steamdeck web)$ python index.py
Traceback (most recent call last):
  File "index.py", line 8, in <module>
    from models.stable_diffusion.main import stable_diff_inf
  File "/home/deck/git/automatic1111/Shark/SHARK/web/models/stable_diffusion/main.py", line 6, in <module>
    from models.stable_diffusion.cache_objects import model_cache
  File "/home/deck/git/automatic1111/Shark/SHARK/web/models/stable_diffusion/cache_objects.py", line 10, in <module>
    from models.stable_diffusion.opt_params import get_unet, get_vae, get_clip
  File "/home/deck/git/automatic1111/Shark/SHARK/web/models/stable_diffusion/opt_params.py", line 2, in <module>
    from models.stable_diffusion.model_wrappers import (
  File "/home/deck/git/automatic1111/Shark/SHARK/web/models/stable_diffusion/model_wrappers.py", line 3, in <module>
    from models.stable_diffusion.utils import compile_through_fx
  File "/home/deck/git/automatic1111/Shark/SHARK/web/models/stable_diffusion/utils.py", line 3, in <module>
    from shark.shark_inference import SharkInference
ModuleNotFoundError: No module named 'shark'
(1)(deck@steamdeck web)$ ^C
(130)(deck@steamdeck web)$

**Comment by powderluv** [comment]
we haven't tested on steamdeck. What GPU does it have ?  Also the checkout path seems funny. Do you have a venv created ?

**Comment by DuckersMcQuack** [comment]
Here's the gpu specs

https://www.techpowerup.com/gpu-specs/steam-deck-gpu.c3897#:~:text=Recommended%20Gaming%20Resolutions%3A&text=The%20Steam%20Deck%20GPU%20is,the%20device%20supports%20DirectX%2012.

Pretty much a custom 6000 RDNA2 APU, but with 8 CU's

**Comment by powderluv** [comment]
What does vulkaninfo report?

**Comment by DuckersMcQuack** [comment]
> What does vulkaninfo report?

https://pastebin.com/6xgbHnEs

**Comment by powderluv** [comment]
Ah it uses RADV ? That would be a lot of work to get the driver to work. Can the AMD drivers work?

**Comment by powderluv** [comment]
Lets close this issue. It is unlikely we can support on Steamdeck without official drivers for vulkan.
