### ISSUE TITLE
"RuntimeError: mat1 and mat2 shapes cannot be multiplied (128x1024 and 768x320)" when using custom .ckpt file

### ISSUE THREAD

**Issue by AQtun81** [nod-ai/SHARK#855]
After running with: (powershell script)

```powershell
python main.py --use_base_vae --vulkan_large_heap_block_size=0 --prompt="tajmahal, oil on canvas, sunflowers, 4k, uhd" --max_length=64 --import_mlir --ckpt_loc=$ckptPath --local_tank_cache=$SharkTankPath
```

I'm getting `RuntimeError: mat1 and mat2 shapes cannot be multiplied (128x1024 and 768x320)`

```
Windows 11 Version 22H2 (OS Build 22621.1105)
16GB RAM
AMD RX 5600XT (6GB VRAM)
```

vulkaninfo reported driver
```
driverInfo      = 22.40.01.10 (AMD proprietary shader compiler)
```

<details>
  <summary>Reveal Traceback</summary>
  <p>

  ```python
  Traceback (most recent call last):
  File "F:\Stable_Diffusion\SHARK\shark\examples\shark_inference\stable_diffusion\main.py", line 113, in <module>
    clip, unet, vae = mlir_import()
  File "F:\Stable_Diffusion\SHARK\shark\examples\shark_inference\stable_diffusion\model_wrappers.py", line 209, in __call__
    compiled_unet = self.get_unet()
  File "F:\Stable_Diffusion\SHARK\shark\examples\shark_inference\stable_diffusion\model_wrappers.py", line 175, in get_unet
    shark_unet = compile_through_fx(
  File "F:\Stable_Diffusion\SHARK\shark\examples\shark_inference\stable_diffusion\utils.py", line 76, in compile_through_fx
    mlir_module, func_name = import_with_fx(
  File "F:\Stable_Diffusion\SHARK\shark\shark_importer.py", line 366, in import_with_fx
    fx_g = make_fx(
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 700, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 439, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 756, in trace
    (self.create_arg(fn(*args)),),
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 455, in wrapped
    out = f(*tensors)
  File "<string>", line 1, in <lambda>
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 734, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 405, in call_module
    return forward(*args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 727, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark\examples\shark_inference\stable_diffusion\model_wrappers.py", line 162, in forward
    unet_out = self.unet.forward(
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 424, in forward
    sample, res_samples = downsample_block(
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 734, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 405, in call_module
    return forward(*args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 727, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 777, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 734, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 405, in call_module
    return forward(*args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 727, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\diffusers\models\attention.py", line 216, in forward
    hidden_states = block(hidden_states, encoder_hidden_states=encoder_hidden_states, timestep=timestep)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 734, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 405, in call_module
    return forward(*args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 727, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\diffusers\models\attention.py", line 498, in forward
    self.attn2(
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 734, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 405, in call_module
    return forward(*args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 727, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\diffusers\models\attention.py", line 619, in forward
    key = self.to_k(encoder_hidden_states)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 734, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 405, in call_module
    return forward(*args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 727, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 482, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 507, in inner_torch_dispatch
    out = proxy_call(self, func, args, kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 341, in proxy_call
    out = func(*args, **kwargs)
  File "F:\Stable_Diffusion\SHARK\shark.venv\lib\site-packages\torch\_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: mat1 and mat2 shapes cannot be multiplied (128x1024 and 768x320)
  ```

  </p>
</details>

**Comment by njsharpe** [comment]
This happened to me. My temporary solution was this:

* Delete shark.venv
* Re-run `setup-venv.ps1` as Administrator (just in case)
* Re-activate your venv
* Re-install accelerate (optional, `pip install accelerate`)

I did attempt to re-install / update torch & torchvision explicitly, but that did not seem to work. Let me know how this works out for you.

**Comment by AQtun81** [comment]
I have previously tried reinstalling shark with no success, today this changed, it seems like recent commits have fixed this error.

For reinstalling I have specifically:
- cleared vulkan cache `%LocalAppData%\AMD\VkCache`
- cleared huggingface cache `%username%\.cache\huggingface`
- cleared pip cache `python -m pip cache purge`
- deleted entire shark folder and shark tank cache
- cloned this repository
- installed with `setup-venv.ps1`
- installed pip modules that were missing (`pip install safetensors omegaconf accelerate`) (for some reason I had to install more modules)
