### ISSUE TITLE
OPT to TOSA

### ISSUE THREAD

**Issue by AmosLewis** [nod-ai/SHARK#865]
```
  %411 = "tosa.cast"(%410) : (tensor<1x128xi32>) -> tensor<1x128xi1>
  %412 = torch.aten.ones %409, %int11, %none, %cpu, %false : !torch.list<int>, !torch.int, !torch.none, !torch.Device, !torch.bool -> !torch.vtensor<[1,128],i1>
  %413 = torch.aten.to.dtype %412, %int4, %false, %false, %none : !torch.vtensor<[1,128],i1>, !torch.int, !torch.bool, !torch.bool, !torch.none -> !torch.vtensor<[1,128],si64>
  %414 = torch.aten.cumsum %413, %int1, %none : !torch.vtensor<[1,128],si64>, !torch.int, !torch.none -> !torch.vtensor<[1,128],si64>
  %415 = torch.aten.mul.Tensor %414, %413 : !torch.vtensor<[1,128],si64>, !torch.vtensor<[1,128],si64> -> !torch.vtensor<[1,128],si64>
  %416 = torch.aten.sub.Scalar %415, %int1, %int1 : !torch.vtensor<[1,128],si64>, !torch.int, !torch.int -> !torch.vtensor<[1,128],si64>
  %417 = torch.aten.add.Scalar %416, %int2, %int1 : !torch.vtensor<[1,128],si64>, !torch.int, !torch.int -> !torch.vtensor<[1,128],si64>
  %418 = torch.aten.embedding %396, %417, %int-1, %false, %false : !torch.vtensor<[2050,768],f32>, !torch.vtensor<[1,128],si64>, !torch.int, !torch.bool, !torch.bool -> !torch.vtensor<[1,128,768],f32>
  %419 = torch.prim.ListConstruct %int128, %int128 : (!torch.int, !torch.int) -> !torch.list<int>
  %420 = torch.prim.NumToTensor.Scalar %float-3.402820e38 : !torch.float -> !torch.vtensor<[],f64>

```

**Comment by AmosLewis** [comment]
```
➜  opt git:(mix) ✗ python opt.py 
Some weights of the model checkpoint at facebook/opt-125m were not used when initializing OPTForSequenceClassification: ['lm_head.weight']
- This IS expected if you are initializing OPTForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing OPTForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of OPTForSequenceClassification were not initialized from the model checkpoint at facebook/opt-125m and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
model(test_input): 
tensor([[0.4479, 0.5788]], grad_fn=<IndexBackward0>)
/home/chi/src/ubuntu20/shark/SHARK/shark.venv/lib/python3.10/site-packages/torch/jit/_check.py:181: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
Traceback (most recent call last):
  File "/home/chi/src/ubuntu20/shark/torch-mlir/opt/opt.py", line 86, in <module>
    module = torch_mlir.compile(
  File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 386, in compile
    run_pipeline_with_repro_report(
  File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering Torch Backend IR -> TOSA Backend IR failed with the following diagnostics:
error: failed to legalize operation 'torch.aten.to.dtype' that was explicitly marked illegal
note: see current operation: %722 = "torch.aten.to.dtype"(%721, %11, %9, %9, %8) : (!torch.vtensor<[],f64>, !torch.int, !torch.bool, !torch.bool, !torch.none) -> !torch.vtensor<[],f32>


For Torch-MLIR developers, the error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='builtin.module(torch-backend-to-tosa-backend-pipeline)' /tmp/_lambda.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.

```

**Comment by AmosLewis** [comment]
```
➜  opt git:(mix) ✗ python opt.py                     
Some weights of the model checkpoint at facebook/opt-125m were not used when initializing OPTForSequenceClassification: ['lm_head.weight']
- This IS expected if you are initializing OPTForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing OPTForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of OPTForSequenceClassification were not initialized from the model checkpoint at facebook/opt-125m and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
model(test_input): 
tensor([[-0.4341, -0.4664]], grad_fn=<IndexBackward0>)
/home/chi/src/ubuntu20/shark/SHARK/shark.venv/lib/python3.10/site-packages/torch/jit/_check.py:181: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
Traceback (most recent call last):
  File "/home/chi/src/ubuntu20/shark/torch-mlir/opt/opt.py", line 86, in <module>
    module = torch_mlir.compile(
  File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 386, in compile
    run_pipeline_with_repro_report(
  File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering Torch Backend IR -> TOSA Backend IR failed with the following diagnostics:
error: failed to legalize operation 'torch.aten.broadcast_to' that was explicitly marked illegal
note: see current operation: %757 = "torch.aten.broadcast_to"(%756, %751) : (!torch.vtensor<[1,1,1,128],i1>, !torch.list<int>) -> !torch.vtensor<[1,1,128,128],i1>


For Torch-MLIR developers, the error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='builtin.module(torch-backend-to-tosa-backend-pipeline)' /tmp/_lambda.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.

```

**Comment by AmosLewis** [comment]
```
func.func @torch.aten.broadcast_to(%arg0: !torch.vtensor<[1,1,1,128],i1>) -> !torch.vtensor<[1,1,128,128],i1> {
  %int1 = torch.constant.int 1
  %int128 = torch.constant.int 128
  %1 = torch.prim.ListConstruct %int1, %int1, %int128, %int128 : (!torch.int, !torch.int, !torch.int, !torch.int) -> !torch.list<int>
  %0 = torch.aten.broadcast_to %arg0 %1 : !torch.vtensor<[1,1,1,128],i1>, !torch.list<int> -> !torch.vtensor<[1,1,128,128],i1>
  return %0 : !torch.vtensor<[1,1,128,128],i1>
}
```

**Comment by AmosLewis** [comment]
New broadcast to fail
```
  %700 = torch.prim.ListConstruct %int128, %int128 : (!torch.int, !torch.int) -> !torch.list<int>
  %701 = "tosa.const"() {value = dense<-3.40282347E+38> : tensor<f32>} : () -> tensor<f32>
  %702 = "tosa.cast"(%701) : (tensor<f32>) -> tensor<f64>
  %703 = torch.prim.NumToTensor.Scalar %float-3.402820e38 : !torch.float -> !torch.vtensor<[],f64>
  %704 = "tosa.cast"(%702) : (tensor<f64>) -> tensor<f32>
  %705 = torch.aten.to.dtype %703, %int6, %false, %false, %none : !torch.vtensor<[],f64>, !torch.int, !torch.bool, !torch.bool, !torch.none -> !torch.vtensor<[],f32>
  %706 = torch.aten.broadcast_to %705, %700 : !torch.vtensor<[],f32>, !torch.list<int> -> !torch.vtensor<[128,128],f32>
```

**Comment by AmosLewis** [comment]
`%3742 = "torch.aten.index.Tensor"(%3723, %3741) : (!torch.vtensor<[1,128,2],f32>, !torch.list<vtensor>) -> !torch.vtensor<[1,2],f32>`
