### ISSUE TITLE
RX 5600 XT Resource Exhausted, Out Of Memory

### ISSUE THREAD

**Issue by MrNehr** [nod-ai/SHARK#877]
Every time i tried to generate an image i got this error (i tried --use_base_vae to prevent the out of memory but same error):
`20it [00:14,  1.38it/s]
Traceback (most recent call last):
  File "C:\WINDOWS\system32\SHARK\shark.venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\WINDOWS\system32\SHARK\shark.venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\WINDOWS\system32\SHARK\shark.venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\WINDOWS\system32\SHARK\shark.venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\WINDOWS\system32\SHARK\shark.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\WINDOWS\system32\SHARK\shark.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\WINDOWS\system32\SHARK\web\models\stable_diffusion\main.py", line 251, in stable_diff_inf
    images = vae("forward", (latents_numpy,))
  File "C:\Windows\System32\SHARK\shark\shark_inference.py", line 136, in __call__
    return self.shark_runner.run(function_name, inputs, send_to_host)
  File "C:\Windows\System32\SHARK\shark\shark_runner.py", line 90, in run
    return get_results(
  File "C:\Windows\System32\SHARK\shark\iree_utils\compile_utils.py", line 362, in get_results
    result = compiled_vm[function_name](*device_inputs)
  File "C:\WINDOWS\system32\SHARK\shark.venv\lib\site-packages\iree\runtime\function.py", line 130, in __call__
    self._invoke(arg_list, ret_list)
  File "C:\WINDOWS\system32\SHARK\shark.venv\lib\site-packages\iree\runtime\function.py", line 154, in _invoke
    self._vm_context.invoke(self._vm_function, arg_list, ret_list)
RuntimeError: Error invoking function: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\vma_allocator.cc:316: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.device.queue.alloca; while calling import;
[ 1]   native hal.device.queue.alloca:0 -
[ 0] bytecode module.forward:3080 [
    <stdin>:189:10
      at <stdin>:20:3,
    <stdin>:190:15
      at <stdin>:20:3,
    <stdin>:199:10
      at <stdin>:20:3,
    <stdin>:203:10
      at <stdin>:20:3,
    <stdin>:221:11
      at <stdin>:20:3,
    <stdin>:226:11
      at <stdin>:20:3,
    <stdin>:236:11
      at <stdin>:20:3,
    <stdin>:280:11
      at <stdin>:20:3,
    <stdin>:315:11
      at <stdin>:20:3,
    <stdin>:320:19
      at <stdin>:20:3,
    <stdin>:328:11
      at <stdin>:20:3,
    <stdin>:346:11
      at <stdin>:20:3,
    <stdin>:351:11
      at <stdin>:20:3,
    <stdin>:361:11
      at <stdin>:20:3,
    <stdin>:403:11
      at <stdin>:20:3,
    <stdin>:437:11
      at <stdin>:20:3,
    <stdin>:450:11
      at <stdin>:20:3,
    <stdin>:456:11
      at <stdin>:20:3,
    <stdin>:479:11
      at <stdin>:20:3,
    <stdin>:484:11
      at <stdin>:20:3,
    <stdin>:494:11
      at <stdin>:20:3,
    <stdin>:536:11
      at <stdin>:20:3,
    <stdin>:564:11
      at <stdin>:20:3,
    <stdin>:597:11
      at <stdin>:20:3,
    <stdin>:639:12
      at <stdin>:20:3,
    <stdin>:584:11
      at <stdin>:20:3,
    <stdin>:657:12
      at <stdin>:20:3,
    <stdin>:690:12
      at <stdin>:20:3,
    <stdin>:700:12
      at <stdin>:20:3,
    <stdin>:612:11
      at <stdin>:20:3,
    <stdin>:709:12
      at <stdin>:20:3,
    <stdin>:723:12
      at <stdin>:20:3,
    <stdin>:740:12
      at <stdin>:20:3,
    <stdin>:735:12
      at <stdin>:20:3,
    <stdin>:767:12
      at <stdin>:20:3,
    <stdin>:772:12
      at <stdin>:20:3,
    <stdin>:782:12
      at <stdin>:20:3,
    <stdin>:824:12
      at <stdin>:20:3,
    <stdin>:858:12
      at <stdin>:20:3,
    <stdin>:871:12
      at <stdin>:20:3,
    <stdin>:889:12
      at <stdin>:20:3,
    <stdin>:894:12
      at <stdin>:20:3,
    <stdin>:904:12
      at <stdin>:20:3,
    <stdin>:946:12
      at <stdin>:20:3,
    <stdin>:980:12
      at <stdin>:20:3,
    <stdin>:993:12
      at <stdin>:20:3,
    <stdin>:999:12
      at <stdin>:20:3,
    <stdin>:1026:12
      at <stdin>:20:3,
    <stdin>:1031:12
      at <stdin>:20:3,
    <stdin>:1041:12
      at <stdin>:20:3,
    <stdin>:1083:12
      at <stdin>:20:3,
    <stdin>:1117:12
      at <stdin>:20:3,
    <stdin>:1130:12
      at <stdin>:20:3,
    <stdin>:1148:12
      at <stdin>:20:3,
    <stdin>:1153:12
      at <stdin>:20:3,
    <stdin>:1163:12
      at <stdin>:20:3,
    <stdin>:1205:12
      at <stdin>:20:3,
    <stdin>:1239:12
      at <stdin>:20:3,
    <stdin>:1252:12
      at <stdin>:20:3,
    <stdin>:1258:12
      at <stdin>:20:3,
    <stdin>:1285:12
      at <stdin>:20:3,
    <stdin>:1290:12
      at <stdin>:20:3,
    <stdin>:1300:12
      at <stdin>:20:3,
    <stdin>:1342:12
      at <stdin>:20:3,
    <stdin>:1376:12
      at <stdin>:20:3,
    <stdin>:1389:12
      at <stdin>:20:3,
    <stdin>:1407:12
      at <stdin>:20:3,
    <stdin>:1412:12
      at <stdin>:20:3,
    <stdin>:1422:12
      at <stdin>:20:3,
    <stdin>:1464:12
      at <stdin>:20:3,
    <stdin>:1498:12
      at <stdin>:20:3,
    <stdin>:1511:12
      at <stdin>:20:3,
    <stdin>:1517:12
      at <stdin>:20:3,
    <stdin>:1544:12
      at <stdin>:20:3,
    <stdin>:1549:12
      at <stdin>:20:3,
    <stdin>:1559:12
      at <stdin>:20:3,
    <stdin>:1601:12
      at <stdin>:20:3,
    <stdin>:1635:12
      at <stdin>:20:3,
    <stdin>:1648:12
      at <stdin>:20:3,
    <stdin>:1666:12
      at <stdin>:20:3,
    <stdin>:1671:12
      at <stdin>:20:3,
    <stdin>:1681:12
      at <stdin>:20:3,
    <stdin>:1723:12
      at <stdin>:20:3,
    <stdin>:1757:12
      at <stdin>:20:3,
    <stdin>:1770:12
      at <stdin>:20:3,
    <stdin>:1771:12
      at <stdin>:20:3,
    <stdin>:1794:19
      at <stdin>:20:3,
    <stdin>:1783:12
      at <stdin>:20:3,
    <stdin>:1802:12
      at <stdin>:20:3,
    <stdin>:1806:12
      at <stdin>:20:3,
    <stdin>:1822:12
      at <stdin>:20:3,
    <stdin>:1827:12
      at <stdin>:20:3,
    <stdin>:1837:12
      at <stdin>:20:3,
    <stdin>:1879:12
      at <stdin>:20:3,
    <stdin>:1914:12
      at <stdin>:20:3,
    <stdin>:1927:12
      at <stdin>:20:3,
    <stdin>:1945:12
      at <stdin>:20:3,
    <stdin>:1950:12
      at <stdin>:20:3,
    <stdin>:1960:12
      at <stdin>:20:3,
    <stdin>:2002:12
      at <stdin>:20:3,
    <stdin>:2036:12
      at <stdin>:20:3,
    <stdin>:2049:12
      at <stdin>:20:3,
    <stdin>:2055:12
      at <stdin>:20:3,
    <stdin>:2078:12
      at <stdin>:20:3,
    <stdin>:2083:12
      at <stdin>:20:3,
    <stdin>:2093:12
      at <stdin>:20:3,
    <stdin>:2135:12
      at <stdin>:20:3,
    <stdin>:2169:12
      at <stdin>:20:3,
    <stdin>:2182:12
      at <stdin>:20:3,
    <stdin>:2200:12
      at <stdin>:20:3,
    <stdin>:2205:12
      at <stdin>:20:3,
    <stdin>:2215:12
      at <stdin>:20:3,
    <stdin>:2257:12
      at <stdin>:20:3,
    <stdin>:2291:12
      at <stdin>:20:3,
    <stdin>:2304:12
      at <stdin>:20:3,
    <stdin>:2310:12
      at <stdin>:20:3,
    <stdin>:2333:12
      at <stdin>:20:3,
    <stdin>:2338:12
      at <stdin>:20:3,
    <stdin>:2348:12
      at <stdin>:20:3,
    <stdin>:2390:12
      at <stdin>:20:3,
    <stdin>:2424:12
      at <stdin>:20:3,
    <stdin>:2437:12
      at <stdin>:20:3,
    <stdin>:2455:12
      at <stdin>:20:3,
    <stdin>:2460:12
      at <stdin>:20:3,
    <stdin>:2470:12
      at <stdin>:20:3,
    <stdin>:2512:12
      at <stdin>:20:3,
    <stdin>:2546:12
      at <stdin>:20:3,
    <stdin>:2559:12
      at <stdin>:20:3,
    <stdin>:2560:12
      at <stdin>:20:3,
    <stdin>:2583:19
      at <stdin>:20:3,
    <stdin>:2572:12
      at <stdin>:20:3,
    <stdin>:2591:12
      at <stdin>:20:3,
    <stdin>:2595:12
      at <stdin>:20:3,
    <stdin>:2611:12
      at <stdin>:20:3,
    <stdin>:2616:12
      at <stdin>:20:3,
    <stdin>:2626:12
      at <stdin>:20:3,
    <stdin>:2668:12
      at <stdin>:20:3,
    <stdin>:2703:12
      at <stdin>:20:3,
    <stdin>:2717:12
      at <stdin>:20:3,
    <stdin>:2721:12
      at <stdin>:20:3,
    <stdin>:2737:12
      at <stdin>:20:3,
    <stdin>:2742:12
      at <stdin>:20:3,
    <stdin>:2752:12
      at <stdin>:20:3,
    <stdin>:2794:12
      at <stdin>:20:3,
    <stdin>:2829:12
      at <stdin>:20:3,
    <stdin>:2834:19
      at <stdin>:20:3,
    <stdin>:2847:12
      at <stdin>:20:3,
    <stdin>:2842:12
      at <stdin>:20:3,
    <stdin>:2853:12
      at <stdin>:20:3,
    <stdin>:2876:12
      at <stdin>:20:3,
    <stdin>:2881:12
      at <stdin>:20:3,
    <stdin>:2891:12
      at <stdin>:20:3,
    <stdin>:2933:12
      at <stdin>:20:3,
    <stdin>:2967:12
      at <stdin>:20:3,
    <stdin>:2980:12
      at <stdin>:20:3,
    <stdin>:2998:12
      at <stdin>:20:3,
    <stdin>:3003:12
      at <stdin>:20:3,
    <stdin>:3013:12
      at <stdin>:20:3,
    <stdin>:3055:12
      at <stdin>:20:3,
    <stdin>:3089:12
      at <stdin>:20:3,
    <stdin>:3102:12
      at <stdin>:20:3,
    <stdin>:3108:12
      at <stdin>:20:3,
    <stdin>:3131:12
      at <stdin>:20:3,
    <stdin>:3136:12
      at <stdin>:20:3,
    <stdin>:3146:12
      at <stdin>:20:3,
    <stdin>:3188:12
      at <stdin>:20:3,
    <stdin>:3222:12
      at <stdin>:20:3,
    <stdin>:3235:12
      at <stdin>:20:3,
    <stdin>:3253:12
      at <stdin>:20:3,
    <stdin>:3258:12
      at <stdin>:20:3,
    <stdin>:3268:12
      at <stdin>:20:3,
    <stdin>:3310:12
      at <stdin>:20:3,
    <stdin>:3344:12
      at <stdin>:20:3,
    <stdin>:3357:12
      at <stdin>:20:3,
    <stdin>:3358:12
      at <stdin>:20:3,
    <stdin>:3381:19
      at <stdin>:20:3,
    <stdin>:3370:12
      at <stdin>:20:3,
    <stdin>:3389:12
      at <stdin>:20:3,
    <stdin>:3393:12
      at <stdin>:20:3,
    <stdin>:3409:12
      at <stdin>:20:3,
    <stdin>:3414:12
      at <stdin>:20:3,
    <stdin>:3424:12
      at <stdin>:20:3,
    <stdin>:3466:12
      at <stdin>:20:3,
    <stdin>:3501:12
      at <stdin>:20:3,
    <stdin>:3515:12
      at <stdin>:20:3,
    <stdin>:3535:12
      at <stdin>:20:3,
    <stdin>:3540:12
      at <stdin>:20:3,
    <stdin>:3550:12
      at <stdin>:20:3,
    <stdin>:3592:12
      at <stdin>:20:3,
    <stdin>:3627:12
      at <stdin>:20:3,
    <stdin>:3632:19
      at <stdin>:20:3,
    <stdin>:3645:12
      at <stdin>:20:3,
    <stdin>:3640:12
      at <stdin>:20:3,
    <stdin>:3651:12
      at <stdin>:20:3,
    <stdin>:3674:12
      at <stdin>:20:3,
    <stdin>:3679:12
      at <stdin>:20:3,
    <stdin>:3689:12
      at <stdin>:20:3,
    <stdin>:3731:12
      at <stdin>:20:3,
    <stdin>:3765:12
      at <stdin>:20:3,
    <stdin>:3778:12
      at <stdin>:20:3,
    <stdin>:3796:12
      at <stdin>:20:3,
    <stdin>:3801:12
      at <stdin>:20:3,
    <stdin>:3811:12
      at <stdin>:20:3,
    <stdin>:3853:12
      at <stdin>:20:3,
    <stdin>:3887:12
      at <stdin>:20:3,
    <stdin>:3900:12
      at <stdin>:20:3,
    <stdin>:3906:12
      at <stdin>:20:3,
    <stdin>:3929:12
      at <stdin>:20:3,
    <stdin>:3934:12
      at <stdin>:20:3,
    <stdin>:3944:12
      at <stdin>:20:3,
    <stdin>:3986:12
      at <stdin>:20:3,
    <stdin>:4020:12
      at <stdin>:20:3,
    <stdin>:4033:12
      at <stdin>:20:3,
    <stdin>:4051:12
      at <stdin>:20:3,
    <stdin>:4056:12
      at <stdin>:20:3,
    <stdin>:4066:12
      at <stdin>:20:3,
    <stdin>:4108:12
      at <stdin>:20:3,
    <stdin>:4142:12
      at <stdin>:20:3,
    <stdin>:4155:12
      at <stdin>:20:3,
    <stdin>:4156:12
      at <stdin>:20:3,
    <stdin>:4184:12
      at <stdin>:20:3,
    <stdin>:4189:12
      at <stdin>:20:3,
    <stdin>:4199:12
      at <stdin>:20:3,
    <stdin>:4241:12
      at <stdin>:20:3,
    <stdin>:4275:12
      at <stdin>:20:3,
    <stdin>:4289:12
      at <stdin>:20:3,
    <stdin>:4280:19
      at <stdin>:20:3
  ]`

**Comment by tuomotalvitie** [comment]
`RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY;`

Perhaps there are options (FP16?) that can be used to save memory?
