### ISSUE TITLE
PermissionError: [WinError 10013] Intento de acceso a un socket no permitido por sus permisos de acceso

### ISSUE THREAD

**Issue by exel-ar** [nod-ai/SHARK#965]
Hello, I have had the following error when trying to run shark_sd_20230206_501 , without having made any changes to the directory.

Could you help me with this?

```
D:\Stable Diffusion>shark_sd_20230206_501.exe
shark_tank local cache is located at C:\Users\Usuario\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
vulkan devices are available.
cuda devices are not available.
Traceback (most recent call last):
  File "gradio\networking.py", line 119, in start_server
PermissionError: [WinError 10013] Intento de acceso a un socket no permitido por sus permisos de acceso

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "index.py", line 265, in <module>
  File "gradio\blocks.py", line 1371, in launch
  File "gradio\networking.py", line 122, in start_server
OSError: Port 8080 is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all().
[12380] Failed to execute script 'index' due to unhandled exception!
```

**Comment by powderluv** [comment]
You can change the port with --server_port=8081
