### ISSUE TITLE
undefined symbol: _ZN3c1022getCustomClassTypeImplERKSt10type_index when running resnet50_script.py

### ISSUE THREAD

**Issue by sogartar** [nod-ai/SHARK#97]
I just made a fresh Python venv and followed the readme instructions to run `resnet50_script.py`.

```
curl -O https://raw.githubusercontent.com/nod-ai/SHARK/main/shark/examples/shark_inference/resnet50_script.py
#Install deps for test script
pip install pillow requests tqdm torch --extra-index-url https://download.pytorch.org/whl/nightly/cpu
python ./resnet50_script.py --device="cpu"  #use cuda or vulkan or metal 
```

I got this error:
```
Traceback (most recent call last):
  File "./resnet50_script.py", line 7, in <module>
    from shark.shark_inference import SharkInference
  File "/home/petkantchin/ws/nodlabs/shark/shark_venv/lib/python3.8/site-packages/shark/shark_inference.py", line 12, in <module>
    from shark.torch_mlir_utils import get_torch_mlir_module, run_on_refbackend
  File "/home/petkantchin/ws/nodlabs/shark/shark_venv/lib/python3.8/site-packages/shark/torch_mlir_utils.py", line 22, in <module>
    from torch_mlir.dialects.torch.importer.jit_ir import (
  File "/home/petkantchin/ws/nodlabs/shark/shark_venv/lib/python3.8/site-packages/torch_mlir/__init__.py", line 13, in <module>
    from torch_mlir.dialects.torch.importer.jit_ir import ClassAnnotator, ModuleBuilder
  File "/home/petkantchin/ws/nodlabs/shark/shark_venv/lib/python3.8/site-packages/torch_mlir/dialects/torch/importer/jit_ir/__init__.py", line 14, in <module>
    from ....._mlir_libs._jit_ir_importer import *
ImportError: /home/petkantchin/ws/nodlabs/shark/shark_venv/lib/python3.8/site-packages/torch_mlir/_mlir_libs/_jit_ir_importer.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c1022getCustomClassTypeImplERKSt10type_index
```

**Comment by powderluv** [comment]
Can you please share the pip list

**Comment by sogartar** [comment]
```
Package            Version     
------------------ ------------
certifi            2022.5.18.1 
charset-normalizer 2.0.12      
filelock           3.7.1       
huggingface-hub    0.7.0       
idna               3.3         
iree-compiler      20220604.24 
iree-runtime       20220604.24 
nodai-SHARK        20220606.49 
numpy              1.22.4      
packaging          21.3        
Pillow             9.1.1       
pip                20.0.2      
pkg-resources      0.0.0       
pyparsing          3.0.9       
PyYAML             6.0         
regex              2022.6.2    
requests           2.27.1      
setuptools         44.0.0      
tokenizers         0.12.1      
torch              1.11.0      
torch-mlir         20220606.495
torchvision        0.12.0      
tqdm               4.64.0      
transformers       4.19.2      
typing-extensions  4.2.0       
urllib3            1.26.9  
```

**Comment by sogartar** [comment]
I installed
```
pip install --pre torch==1.13.0.dev20220606+cpu torchvision==0.14.0.dev20220606+cpu -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
```

Then it ran fine and got

```
The top 3 results obtained via shark_runner is:
[('Labrador retriever', 52.365936279296875), ('Chesapeake Bay retriever', 7.188110828399658), ('golden retriever', 5.128644943237305)]

The top 3 results obtained via torch is:
[('Labrador retriever', 52.3659782409668), ('Chesapeake Bay retriever', 7.188116073608398), ('golden retriever', 5.128646373748779)]
```
It is matching up to the 4th decimal place.

**Comment by powderluv** [comment]
can you try this

```pip install --pre torch torchvision torchaudio tqdm pillow --extra-index-url https://download.pytorch.org/whl/nightly/cpu
```

I have updated the instructions too in case it works.

**Comment by sogartar** [comment]
That worked OK.
